### ISSUE TITLE
GLFW vs SDL depth buffer inconsistency

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1053]
Windows 10

So I was trying to play with the depth buffer and do zbuffer, come to find out SDL sets up a depth buffer (and potentially a stencil buffer, not sure) but GLFW doesn't. When you don't explicitly set the depth buffer to lets say 24 bits in WindowOptions, no depth effects take place on orthographic projections.

I was taking a look at #927 and noticed @HurricanKai mentioned that, "This is likely an issue with you not setting the bit depths on the window options you are passing. This is known to have bad defaults especially on AMD hardware."

GLFW and SDL on windows would use wgl. This happens via a choose pixel format function https://github.com/glfw/glfw/blob/c18851f52ec9704eb06464058a600845ec1eada1/src/wgl_context.c#L65 . The driver would offer up available display modes, and your preferred depth would likely be in it. By not supplying it, it doesn't mean that a hardware accelerated color buffer only window doesn't exist. So glfw would simply just match said depthless window and roll with it. SDL likely has hard defaults in place.

Honestly, its an inconsistency between the two which is easiest avoided by just having the library specify default 24 bits, or to force SDL to use 0 bits defaultly for depth (and maybe stencil). I prefer the former.

Recommended:
Depth 24
Stencil 8

**Comment by Perksey** [comment]
The default values for the depth bits and stencil bits are left intentionally undefined and shouldn’t be depended on.

**Comment by tilkinsc** [comment]
The last thing anyone wants its to deal with inconsistency.

**Comment by Beyley** [comment]
> The last thing anyone wants is to deal with inconsistency.

The main thing is that you should not depend on it unless you explicitly set it, this likely will be explained in any documentation, that we just have yet to write, we dont want to set the settings silently for the user, if you dont set stencil/depth bits manually, we wont set it for you

**Comment by tilkinsc** [comment]
But you will swap buffers for the user?

**Comment by Beyley** [comment]
> But you will swap buffers for the user?

That's something that caused a *lot* of problems for new users, while depth+stencil buffers are a lot further down the line of things to learn

**Comment by Beyley** [comment]
Plus not all users use a depth+stencil buffer, i know i dont, while nearly *everyone* wants to swap buffers every frame

**Comment by HurricanKai** [comment]
I think these are clearly documented to default to the system default. While it's unfortunate that those defaults don't always make sense, it is not something we can fix.
We can also not safely set this to any value, given that could lead to users who don't need depth or stencil buffers experiencing crashes on older hardware.
