### ISSUE TITLE
Add interface with static abstract for `NativeExtension<Vk>.ExtensionName`

### ISSUE THREAD

**Issue by Khitiara** [dotnet/Silk.NET#1054]
# Summary of feature
Add an interface implemented by all native extensions with a `public static abstract string ExtensionName { get; }` for helping with assembling the list of required extensions when constructing a vulkan instance or device.

**Comment by Perksey** [comment]
I don't think we can actually do this on anything other than .NET 7, as SAII is in preview until that version.

**Comment by Perksey** [comment]
I don't think we can implement this at this time.

SAII requires .NET 7 in both the package where the interface is defined (Core) and where the interface is implemented (all the bindings). To implement this, we will need to retarget every single package to also target .NET 7 which will increase package size quite a bit. I don't think this small change can justify that at the moment.

**Comment by Perksey** [comment]
Outdated comment! I changed my mind between writing the comment and forgetting I wrote the comment and thinking "oh I was midway writing a comment"

**Comment by Perksey** [comment]
Update I changed my mind again: this will considerably increase iteration time by building all for all those extra target frameworks and once again this is such a small addition that I don't think we can justify it given the resources we have available to us at this time.
