### ISSUE TITLE
OpenAL Enumeration and EXT Capture Devices

### ISSUE THREAD

**Issue by Syncaidius** [dotnet/Silk.NET#1068]
While developing the audio system for my game engine project, I came across some pretty ugly separation with regards to `Silk.NET.OpenAL.Extensions.Enumeration`. 

Everything that is needed to retrieve the default and available audio outputs is in the `Silk.NET.OpenAL.Extensions.Enumeration.Enumeration` class. 

However, to retrieve capture/input devices, you have to reference the `Silk.NET.OpenAL.Extensions.EXT` package and pass `Silk.NET.OpenAL.Extensions.EXT.Enumeration.GetCaptureEnumerationContextString` to `Silk.NET.OpenAL.Extensions.Enumeration.GetString()` by casting it to a `GetEnumerationContextString` enum value.

To get the list of available capture/input devices, it's equally as akward, passing a casted `Silk.NET.OpenAL.Extensions.EXT.Enumeration.GetEnumerationContextStringList` value to `Silk.NET.OpenAL.Extensions.Enumeration.GetStringList()`.

This is exacerbated by the fact that they're split into two separate nuget packages: `Silk.NET.OpenAL.Extensions.EXT` and `Silk.NET.OpenAL.Extensions.Enumeration`, but seem like they're meant to be rolled into a single package, as `Extensions.EXT.Enumeration` is useless without the `Extensions.Enumeration` package

Do `GetEnumerationContextString` and `GetCaptureEnumerationContextString` (and their list variants) need consolidating?

I was able to get the following after much fumbling around:
```
Default audio output: OpenAL Soft
Available audio outputs:
	0: OpenAL Soft

Default audio input: OpenAL Soft on Mic in at rear panel (Pink) (Realtek(R) Audio)
Available audio inputs:
	0: OpenAL Soft on Mic in at rear panel (Pink) (Realtek(R) Audio)
```

Here is the source in a self-contained method:
```csharp
        private unsafe void TestOpenALEnumeration()
        {
            // Start OpenAL-Soft
            AL _al = AL.GetApi(true);
            ALContext _context = ALContext.GetApi(true);

            // Check if enumeration extension is available.
            if (_context.TryGetExtension(null, out Enumeration enumeration))
            {
                // Get output devices
                string defaultOutputName = enumeration.GetString(null, GetEnumerationContextString.DefaultDeviceSpecifier);
                Debug.WriteLine($"Default audio output: {defaultOutputName}");

                Debug.WriteLine($"Available audio outputs:");
                IEnumerable<string> outputList = enumeration.GetStringList(GetEnumerationContextStringList.DeviceSpecifiers);

                int id = 0;
                foreach (string outputName in outputList)
                    Debug.WriteLine($"\t{id++}: {outputName}");

                // Get input devices. Here, we have to cast our enums from the EXT package to work with the Enumeration extension package
                string defaultInputName = enumeration.GetString(null, 
                    (GetEnumerationContextString)Silk.NET.OpenAL.Extensions.EXT.Enumeration.GetCaptureEnumerationContextString.DefaultCaptureDeviceSpecifier);

                Debug.WriteLine($"Default audio input: {defaultOutputName}");

                Debug.WriteLine($"Available audio inputs:");
                IEnumerable<string> inputList = enumeration.GetStringList(
                    (GetEnumerationContextStringList)Silk.NET.OpenAL.Extensions.EXT.Enumeration.GetCaptureContextStringList.CaptureDeviceSpecifiers);

                id = 0;
                foreach (string inputName in inputList)
                    Debug.WriteLine($"\t{id++}: {inputName}");
            }
            else
            {
                string oal_ext = ExtensionAttribute.GetExtensionAttribute(typeof(Enumeration)).Name;
                Debug.WriteLine($"Unable to detect audio devices due to missing extension: {oal_ext}");
            }

            _context.Dispose();
            _al.Dispose();
        }
```

Please let me know if any more info is needed!

**Comment by HurricanKai** [comment]
I'm not sure what you want us to do here. This is just how OpenAL works. For reference, here is some C++ code that also jumps these hoops.
https://stackoverflow.com/questions/28960638/listing-all-devices-open-al-does-not-work

**Comment by Syncaidius** [comment]
Ah, thank you. This is the first time I'm using OpenAL in a long while, so finding things has been a bit of a challenge so far.

Thanks for the link!

**Comment by Beyley** [comment]
Closing as resolved
