### ISSUE TITLE
ImGui on macOS

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/Silk.NET#1069]
# Summary

Application that uses `ImGui` crash in runtime (macOS) with exception

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'cimgui' or one of its 
dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES 
environment variable: dlopen(libcimgui, 0x0001): tried: 'libcimgui' (no such file), '/usr/local/lib/libcimgui' 
(no such file), '/usr/lib/libcimgui' (no such file), '/Users/sergey_tihon/git/SuperSDG/tests/Playground/bin/Debug/net6.0/libcimgui' (no such file)
   at ImGuiNET.ImGuiNative.igShowDemoWindow(Byte* p_open)
   at ImGuiNET.ImGui.ShowDemoWindow()
```

# Steps to reproduce
- Platform: Desktop / macOS
- Framework Version: .NET 6
- API: ImGui

Should be reproducible with official example
https://github.com/dotnet/Silk.NET/tree/main/examples/CSharp/OpenGL%20Demos/ImGui

**Comment by HurricanKai** [comment]
We use ImGui.NET in those samples for ImGui support. Loading & Distributing the native lib `cimgui` is part of their code, please report upstream.

**Comment by roeyskoe** [comment]
This has already been fixed upstream, but updated package with the fix has not yet been released.

**Comment by sergey-tihon** [comment]
@roeyskoe most, likely you are talking about https://github.com/mellinoe/ImGui.NET/pull/318 

It is not released indeed, but am still not 100% that this fix embed correct native binary for `osx-x64`
