### ISSUE TITLE
WindowOptions.Position is not respected

### ISSUE THREAD

**Issue by DarthAffe** [dotnet/Silk.NET#1070]
# Summary
Setting the Position in the WindowOptions used to create a window does not change anything. 
Other Options work fine.

# Steps to reproduce
- Platform: Desktop (Win 10)
- Framework Version: .NET6

It's 100% reproducible for me using this code in the Program.cs of a ConsoleApplication referencing the current NuGet (2.16.0) of Silk.NET

```csharp
using Silk.NET.Maths;
using Silk.NET.Windowing;

WindowOptions options = WindowOptions.Default;
options.Position = new Vector2D<int>(1000, 0);

// These two work as expected (they don't have any impact on the problem)
options.Size = new Vector2D<int>(1280, 1440);
options.WindowBorder = WindowBorder.Hidden;

Window.Create(options).Run();
```

# Comments
A borderless window appears always in the top left (0,0), the position of windows with border seems to be somehow dependant of the mouse position on startup.

Checking the Position of the Window in the debugger before running it returns the expected value:
![image](https://user-images.githubusercontent.com/1094841/187307076-d2fd0970-99b1-492f-92ab-164ae17d8855.png)

**Comment by copygirl** [comment]
This also happens to me on Linux with a regular window. If I want to center the window, I have to do it after `Initialize()`, but then there'll be a brief moment where it appears in the "wrong" place - one of the corners of my monitor.

**Comment by DarthAffe** [comment]
Ohh, that's a good hint. Indeed this works:
```csharp
using Silk.NET.Maths;
using Silk.NET.Windowing;

WindowOptions options = WindowOptions.Default;
//options.Position = new Vector2D<int>(2000, 0);
options.Size = new Vector2D<int>(1280, 1440);
options.WindowBorder = WindowBorder.Hidden;

IWindow window = Window.Create(options);
window.Initialize();
window.Position = new Vector2D<int>(2000, 0);
window.Run();
```
without the Initialize setting the position does not work for me (even after it's running).

**Comment by copygirl** [comment]
Alternatively, instead of calling `Initialize` yourself, you can set the position in the `Load` event.

**Comment by DarthAffe** [comment]
I tried to set it in the Load event and it does not work.
