### ISSUE TITLE
Add support for DX11On12

### ISSUE THREAD

**Issue by CXCubeHD** [dotnet/Silk.NET#1075]
# Summary of feature
This feature adds support for the DirectX11On12 layer. (`ID3D11On12Device`)

# Comments
DX11On12 allows to use a DirectX11 device on  top of a DirectX12 device. This can be used to overcome some limitations where the application is being forced to use DX12 while the 2D graphics library only supports DirectX11.

# Does this have a proposal?
No.

**Comment by Perksey** [comment]
Resolved in #1193
