### ISSUE TITLE
TextureWrapMode enum contains LinearMipmapLinear

### ISSUE THREAD

**Issue by ohtrobinson** [dotnet/Silk.NET#1076]
# Summary
The `TextureWrapMode` enum contains `LinearMipmapLinear` which isn't in the GL spec.

# Steps to reproduce
It's in the `Silk.NET.OpenGL` namespace, repro is simply writing `TextureWrapMode.LinearMipmapLinear`. I haven't seen what behaviour it causes though.

**Comment by Perksey** [comment]
This needs to be fixed upstream.

**Comment by Perksey** [comment]
Going to close as "won't fix", as this is an upstream issue. If this should be fixed, then the fix is simple: just ctrl+f for GL_LINEAR_MIPMAP_LINEAR in gl.xml and PR a fix for the declaration line.
