### ISSUE TITLE
Potential typo in Vulkan `ColorSpaceKHR`

### ISSUE THREAD

**Issue by MarchingCube** [dotnet/Silk.NET#1079]
# Summary
When porting our app to use Silk Vulkan binding I've noticed that one enum member in `ColorSpaceKHR` looks a bit off. Probably due to some automatic conversion a letter was dropped. I have no idea how it gets generated so I can't fix it myself :)

https://github.com/dotnet/Silk.NET/blob/b5dda6dd59cb10bcca6fd5aca7556f0bfc08bad9/src/Vulkan/Silk.NET.Vulkan/Enums/ColorSpaceKHR.gen.cs#L71-L72

One can see that instead of `SpaceSrgbNonlinearKhr` (which already exists) it is generating `PaceSrgbNonlinearKhr`. 
It is a low severity issue but perhaps rename caused more quirks like that.

# Comments

**__If you know how to fix this issue, please submit a pull request instead!__**

**Comment by HurricanKai** [comment]
It's really just a legacy name from 1.0, maybe we can just special case this one to ignore. I'm not aware of any other typos that made it in.

**Comment by MarchingCube** [comment]
Yeah, this name dates back to 2016 which is well before this wrapper was a thing. I would suggest to just ignore it since it just there for backwards compat for Vulkan apps written several years ago.

![image](https://user-images.githubusercontent.com/2588062/189480864-37ebb6f6-e67f-4d4b-9ae9-dc48732711c1.png)
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkColorSpaceKHR.html

**Comment by Perksey** [comment]
Given the above, closing this and we'll just have to live with the back compat enum. Users are free to use the `Space` version instead of the `Pace` version.
