### ISSUE TITLE
Implement multi-lang font support for ImGui

### ISSUE THREAD

**Issue by Breadp4ck** [dotnet/Silk.NET#1092]
# Summary of feature

Add smth like `GlyphRange` property to `ImGuiFontConfig` to use non-English languages.

In ImGui exists function `AddFontFromFileTTF`, that works like this:

```cpp
ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("NotoSansCJKjp-Medium.otf", 20.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
```

# Comments

I think implementation may look like that:

```csharp
using System;

// <...>

{
    public readonly struct ImGuiFontConfig
    {
        public ImGuiFontConfig(string fontPath, int fontSize)
        {
            // <...>
        }

        public ImGuiFontConfig(string fontPath, int fontSize, IntPtr glyphRange)
        {
            // <...>
            GlyphRange = glyphRange;
        }

        public string FontPath { get; }
        public int FontSize { get; }
        public IntPtr GlyphRange { get; } = IntPtr.Zero;
    }
}
``` 
So the using of `AddFontFromFileTTF` in `ImGuiController`, if  `imGuiFontConfig.Value.GlyphRange != IntPtr.Zero`, can be like that:

```csharp
io.Fonts.AddFontFromFileTTF(
    imGuiFontConfig.Value.FontPath,
    imGuiFontConfig.Value.FontSize,
    null,
    imGuiFontConfig.Value.GlyphRange
);
```

I tried to implement it by myself, but I'm C# noob :-(

# Does this have a proposal?
ImGui shows just "???? ??????" instead of "всем привет". I can't use any language other than English in simple scenario like:

```csharp
ImGuiFontConfig config = new ImGuiFontConfig(source, fontSize, io.Fonts.GetGlyphRangesCyrillic());
_controller = new ImGuiController(_gl, _window, _input);
```

And I don't find the way to bind config to controller, I think is doesn't exist.

**Comment by KingRikkie** [comment]
This seems like a deeper problem with the font implementation. No glyph beyond 0x00ff (ANSI range) will be shown on any element. Just try to show any letters > 0x000FF.
```cs
Silk.NET.OpenGL.Extensions.ImGui.ImGuiFontConfig fontConfDefault = new("ui-font.ttf", 16);
    _Controller = new ImGuiController(
    _Gl = _Window.CreateOpenGL(),
    _Window,
    _InputContext = _Window.CreateInput(), 
    fontConfDefault
;
...
ImGuiNET.ImGui.Text("\u0166"); // Ŧ (T-Bar symbol) from unicode.
```
Shuws up as **?** on UI.

**Comment by Beyley** [comment]
> This seems to be a deeper problem with the font implementation. No glyph beyond 0x00ff (ANSI range) will be shown on any element. Just try to show any letters > 0x000FF.
> 
> ```cs
> Silk.NET.OpenGL.Extensions.ImGui.ImGuiFontConfig fontConfDefault = new("ui-font.ttf", 16);
> _Controller = new ImGuiController(
>     _Gl = _Window.CreateOpenGL(),
>     _Window,
>     _InputContext = _Window.CreateInput(), 
>     fontConfDefault
> ;
> ...
> ImGuiNET.ImGui.Text("\u0166"); // Ŧ (T-Bar symbol) from unicode.
> ```
> 
> Shows up as **?** on UI. Worth mentioning: the regular ImGUI.NET library can show these characters just fine.

As stated within the original issue message, this is due to a lack of user-definable glyph range support, also 'Worth mentioning: the regular ImGUI.NET library can show these characters just fine.' doesnt make too much sense, since ImGui.NET doesnt display anything on its own, it needs a controller, and our controller does not have user-definable glyph ranges
