### ISSUE TITLE
SetWindowIcon not working on MacOS (Apple Silicon)

### ISSUE THREAD

**Issue by efeozyer** [dotnet/Silk.NET#1103]
# Summary
I just started using Silk.Net and I created basic window. As a developer I want to be able to set window icon for MacOS.

# Steps to reproduce
- Platform: Desktop (macOS Silicon)
- Framework Version: .NET 6
- API: OpenGL
- API Version: OpenGL 4.5 Core
1. Create Window
2. Initialize Window
3. SetWindowIcon

SetWindow icon not working in MacOS. I tried these extensions .png, .ico, .icns

@Beyley here is code example;

```csharp
var bytes = File.ReadAllBytes(".//assets//icons//icon.icns");
var rawImage = new RawImage(64, 64, new Memory<byte>(bytes));
window.Initialize();
window.SetWindowIcon(ref rawImage);
window.Run();
```

**Comment by Beyley** [comment]
> # Summary
> 
> I just started using Silk.Net and I created basic window. As a developer I want to be able to set window icon for MacOS.
> # Steps to reproduce
> 
>     * Platform: Desktop (macOS Silicon)
> 
>     * Framework Version: .NET 6
> 
>     * API: OpenGL
> 
>     * API Version: OpenGL 4.5 Core
> 
> 
>     1. Create Window
> 
>     2. Initialize Window
> 
>     3. SetWindowIcon
> 
> 
> SetWindow icon not working in MacOS. I tried these extensions .png, .ico, .icns

can you give us your example code? you likely are making a mistake when loading the image

**Comment by Beyley** [comment]
RawImage does not take in files, it takes in the raw bytes of a continuous section of color data, you need to read the image file, get the color data, the give only the color data to the RawImage constructor

**Comment by efeozyer** [comment]
Hey @Beyley unfortunately still not working here is my code snippet. If you have an example please share with us :)

```csharp
        var fileBytes = File.ReadAllBytes(".//assets//icons//icon.ico");
        var bitmap = SKBitmap.Decode(fileBytes);

        byte[] bytes = new byte[bitmap.Pixels.Length * 4];

        int index = 0;
        foreach (var pixel in bitmap.Pixels)
        {
            bytes[index++] = pixel.Red;
            bytes[index++] = pixel.Green;
            bytes[index++] = pixel.Blue;
            bytes[index++] = pixel.Alpha;
            Console.WriteLine(pixel.ToString());
        }

        var rawImage = new RawImage(128, 128, new Memory<byte>(bytes));

        window.Initialize();
        window.SetWindowIcon(ref rawImage);
        window.Run();
```

**Comment by Beyley** [comment]
Dont call `IWindow.Initialize()`, and set the window after the window runs, using the `Load` event

**Comment by efeozyer** [comment]
Hey @Beyley unfortunately doesn't work.. What I tried so far?

- I used different libraries in order to get raw bytes of image (SixLabors.ImageSharp & SkBitmap)
- I tried different formats (icns, ico, png, bmp)
- I tried different resolutions here is the list

- Icon_128x128.png
- Icon_128x128@2x.png
- Icon_16x16.png
- Icon_16x16@2x.png
- Icon_256x256.png
- Icon_256x256@2x.png
- Icon_32x32.png
- Icon_32x32@2x.png
- Icon_512x512.png
- Icon_512x512@2x.png

Here is entire console application code.

```csharp
using Silk.NET.Core;
using Silk.NET.Windowing;
using SkiaSharp;

class Program
{
    private static IWindow window;

    private static void Main(string[] args)
    {
        //Create a window.
        var options = WindowOptions.Default;
        options.Title = "LearnOpenGL with Silk.NET";
        options.WindowState = WindowState.Maximized;

        window = Window.Create(options);

        //Assign events.
        window.Load += OnLoad;

        //Run the window.
        window.Run();
    }

    private static void OnLoad()
    {
        var fileBytes = File.ReadAllBytes(".//assets//icons//icon.png");
        var bitmap = SKBitmap.Decode(fileBytes);

        byte[] bytes = new byte[bitmap.Pixels.Length * 4];

        int index = 0;
        foreach (var pixel in bitmap.Pixels)
        {
            bytes[index++] = pixel.Red;
            bytes[index++] = pixel.Green;
            bytes[index++] = pixel.Blue;
            bytes[index++] = pixel.Alpha;
        }

        var rawImage = new RawImage(128, 128, new Memory<byte>(bytes));

        window.SetWindowIcon(ref rawImage);
    }
}
```

**Comment by Beyley** [comment]
I can recreate this on Wayland too, this may be a bug upstream with GLFW/SDL, as i can see it works on windows, what windowing backend is in use in your code? (you can print the type of your `IWindow`)

**Comment by Beyley** [comment]
> I can recreate this on Wayland too, this may be a bug upstream with GLFW/SDL, as i can see it works on windows, what windowing backend is in use in your code? (you can print the type of your `IWindow`)

uhhhh nevermind i guess, the issue has magically disappeared, and icons now are working in Wayland (i just updated so thats probably it)

**Comment by Beyley** [comment]
Confirmed to be an upstream issue, see [remarks](https://www.glfw.org/docs/latest/group__window.html#gadd7ccd39fe7a7d1f0904666ae5932dc5) 
Not sure why wayland works now, i assume its just that the docs havent been updated yet (or maybe im running under Xwayland and thats whats giving it the icon?)
