### ISSUE TITLE
Register HotKey

### ISSUE THREAD

**Issue by efeozyer** [dotnet/Silk.NET#1104]
# Summary of feature
As a developer I want to be able to register hotkeys.(CMD + T, CMD + R etc.)

I couldn't find a way to register HotKey from InputContext. WndProc [supports](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-hotkey) hot key definition.

Could you please implement this feature?

**Comment by Beyley** [comment]
This is code the user is expected to implement, you listen for key presses, and act accordingly, in this case, you would listen for a CMD down, then your T or R press, check if CMD is down, and act accordingly

**Comment by Beyley** [comment]
Also you linked a win32 API, yet seem to be on MacOS, so it would not apply to you, we use GLFW and SDL for windowing, we do not directly talk with win32
