### ISSUE TITLE
SilkBackedSkiaRendering crashes on Linux

### ISSUE THREAD

**Issue by Jspa2** [dotnet/Silk.NET#1109]
# Summary
The [SilkBackedSkiaRendering](https://github.com/dotnet/Silk.NET/blob/main/src/Lab/Experiments/SilkBackedSkiaRendering/Program.cs) experiment crashes on my Linux installation.

A blank, black window briefly pops up, and then closes.

# Steps to reproduce
- Platform: Desktop Linux
- Framework Version: .NET 6.0.10
- API: OpenGL
- API Version: OpenGL 4.6
1. Run the SilkBackedSkiaRendering project in /src/Lab/Experiments/SilkBackedSkiaRendering.

# Comments
Additional information:
Silk.NET version 2.16.0
SkiaSharp version 2.88.3
Distro: Arch Linux
Wayland

**Comment by Beyley** [comment]
Stack trace?

**Comment by JsphA** [comment]
> Stack trace?

It simply exits with code 0 after `GRGlInterface.Create`.

**Comment by Beyley** [comment]
> > Stack trace?
> 
> It simply exits with code 0 after `GRGlInterface.Create`.

Run it under GDB and see if it can catch anything

**Comment by Perksey** [comment]
It's worth noting a more complete example of using Silk.NET with Skia is available in Trains.NET: https://github.com/davidwengier/Trains.NET/blob/main/src/SilkTrains/Program.cs

**Comment by JsphA** [comment]
> > > Stack trace?
> > 
> > 
> > It simply exits with code 0 after `GRGlInterface.Create`.
> 
> Run it under GDB and see if it can catch anything

GDB shows:
```
[New Thread 0x7fff7d60f6c0 (LWP 7952)]
[New Thread 0x7fff7ce0e6c0 (LWP 7953)]
[New Thread 0x7fff77fff6c0 (LWP 7954)]
[New Thread 0x7fff777fe6c0 (LWP 7955)]
[New Thread 0x7fff76ffd6c0 (LWP 7956)]
[New Thread 0x7fff763ff6c0 (LWP 7957)]
[New Thread 0x7fff74a2c6c0 (LWP 7958)]
[New Thread 0x7fff34dff6c0 (LWP 7959)]
[New Thread 0x7fff2ffff6c0 (LWP 7960)]
[New Thread 0x7fff2f7fe6c0 (LWP 7961)]
[New Thread 0x7fff2effd6c0 (LWP 7962)]

Thread 1 "app" received signal SIGSEGV, Segmentation fault.
0x00007fff2deebf63 in ?? () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
```

**Comment by Beyley** [comment]
> > > > Stack trace?
> > > 
> > > 
> > > It simply exits with code 0 after `GRGlInterface.Create`.
> > 
> > Run it under GDB and see if it can catch anything
> 
> GDB shows:
> ```
> [New Thread 0x7fff7d60f6c0 (LWP 7952)]
> [New Thread 0x7fff7ce0e6c0 (LWP 7953)]
> [New Thread 0x7fff77fff6c0 (LWP 7954)]
> [New Thread 0x7fff777fe6c0 (LWP 7955)]
> [New Thread 0x7fff76ffd6c0 (LWP 7956)]
> [New Thread 0x7fff763ff6c0 (LWP 7957)]
> [New Thread 0x7fff74a2c6c0 (LWP 7958)]
> [New Thread 0x7fff34dff6c0 (LWP 7959)]
> [New Thread 0x7fff2ffff6c0 (LWP 7960)]
> [New Thread 0x7fff2f7fe6c0 (LWP 7961)]
> [New Thread 0x7fff2effd6c0 (LWP 7962)]
> 
> Thread 1 "app" received signal SIGSEGV, Segmentation fault.
> 0x00007fff2deebf63 in ?? () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
> ```

type `bt` to get a stack trace

**Comment by JsphA** [comment]
> type `bt` to get a stack trace

@Beyley, this is the stack trace from GDB:
```
(gdb) bt
#0  0x00007fff2deebf63 in ?? () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
#1  0x00007fff2dee8de8 in ?? () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
#2  0x00007fff2deebba0 in ?? () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
#3  0x00007fff2dc77def in gr_glinterface_assemble_interface () from /home/user/app/bin/Debug/net6.0/runtimes/linux-x64/native/libSkiaSharp.so
#4  0x00007fff7e7d399a in ?? ()
#5  0x00007fffffffd010 in ?? ()
#6  0x0000000000000000 in ?? ()
```

**Comment by Perksey** [comment]
This looks like a Skia bug, but failing that this is a bug report against strictly experimental code (assume that everything in src/Lab is broken).

This code is probably a better reference for silk backed skia rendering:  https://github.com/davidwengier/Trains.NET/blob/main/src/SilkTrains/Program.cs

Hope this helps.

**Comment by peteruhnak** [comment]
Just a note since I ran into this issue as well -- it seems to be enough to just let it create itself.

Can create a PR, but have no clue if this breaks on Windows/Mac.

```diff
- using var grGlInterface = GRGlInterface.Create((name => window.GLContext!.TryGetProcAddress(name, out var addr) ? addr : (IntPtr) 0));
+ using var grGlInterface = GRGlInterface.Create();
```

**Comment by Perksey** [comment]
You can create a PR if you’d like, but do note that we do not maintain any code in src/Lab so it’s probably all broken.

If you omit that parameter, where does Skia get the GL functions from?
