### ISSUE TITLE
WebGPU bindings

### ISSUE THREAD

**Issue by Beyley** [dotnet/Silk.NET#1113]
# Summary of feature
Add bindings to WebGPU through the [universal webgpu.h native header](https://github.com/webgpu-native/webgpu-headers/)

# Comments
This is something i want to look into for 2.X personally
It is possible to use WebGPU outside of a browser using either [Dawn](https://dawn.googlesource.com/dawn) or [wgpu](https://wgpu.rs/), so the goal would be to support both of those, along with it *in* the web using emscripten (once emscripten/web support is further along and merged)

**Comment by xtuzy** [comment]
Hello, it will supprt android or ios?

**Comment by Beyley** [comment]
@xtuzy Android should work (but is untested), iOS is not supported, and may not be for an extended period of time, as Silk.NET itself does not run under iOS without many hacks (and its never been gotten to work on real hardware)
