### ISSUE TITLE
Using AOT Native gives System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by byte-0x74** [dotnet/Silk.NET#1122]
When building project with AOT it gives System.PlatformNotSupportedException

- Platform: Desktop
- Framework Version: .NET 7.0.0-RC2
- API: OpenGL
- API Version: (Not sure which version im using the Silk.NET.OpenGL.Extensions.ImGui example
1. Builded project with AOT enabled x64
2. Runned it

Not sure if this is bug or silk just dont have support to aot yet.

**Comment by Beyley** [comment]
Can you give a full stack trace?

**Comment by byte-0x74** [comment]
Sure
`Unhandled Exception: System.PlatformNotSupportedException: Couldn't find a suitable window platform. (none registered) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html
   at Silk.NET.Windowing.Window.Create(WindowOptions) + 0x19d
   at Plutonium.Rendering.TestWindow.Run() + 0x90
   at Plutonium!<BaseAddress>+0x1c4b83`

**Comment by Beyley** [comment]
Ah it's that problem, you need to run RegisterPlatform on SdlWindowing, SdlInput, GlfwWindowing, GlfwInput

**Comment by byte-0x74** [comment]
Oh okay thanks that solved it.

**Comment by BTOdell** [comment]
Is there a way for Silk.NET to handle this automatically? Ideally, the application code shouldn't need to be different when publishing to AOT vs normal.

**Comment by Perksey** [comment]
Applications don't need to be different between AOT vs normal, however applications do need to be compatible with AOT. Adding the following lines
```cs
if (OperatingSystem.IsAndroid() || OperatingSystem.IsIOS())
{
    SdlWindowing.Use();
    SdlInput.Use();
}
else
{
    GlfwWindowing.Use();
    GlfwInput.Use();
}
```
is enough to make your applications fully AOT compliant. This will work on both AOT and non-AOT, you can just leave the code in there so the application is the same regardless of what mode you publish in. Silk by default does something similar to the above using reflection magic which is unavailable on AOT, hence the extra effort.
