### ISSUE TITLE
alBufferData has no overload for FloatBufferFormat

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1149]
# Summary of feature
AL::BufferFormat should have an overload which accepts FloatBufferFormat (when a wav or ogg or etc has float data). 

# Comments
https://github.com/openalext/openalext/blob/master/AL_EXT_float32.txt
This is a feature request for Silk.NET.OpenAL.Extensions.EXT.

# Does this have a proposal?
No.

**Comment by Beyley** [comment]
Since the OpenAL bindings are manually generated, you should add an extension method in [here](https://github.com/dotnet/Silk.NET/blob/main/src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/FloatFormat.cs), that just casts down to the base enum

**Comment by tilkinsc** [comment]
So something like this?
```cs

namespace Silk.NET.OpenAL.Extensions.EXT
{
    /// <summary>
    /// Exposes the multi-channel buffers extension by Creative Labs.
    /// </summary>
    [Extension("AL_EXT_float32")]
    [NativeApi(Prefix = "al")]
    public partial class FloatFormat : FormatExtensionBase<FloatBufferFormat>
    {
        /// <inheritdoc cref="ExtensionBase" />
        public FloatFormat(INativeContext ctx)
            : base(ctx)
        {
        }
        
        public static implicit operator BufferFormat(FloatFormat format) => (BufferFormat) format;
}
```

**Comment by Beyley** [comment]
thats not exactly what i meant, i meant an extension method over the methods that can take FloatFormat, not an operator override from FloatFormat -> BufferFormat

**Comment by ohtrobinson** [comment]
This is part of the Silk.NET.OpenAL.Extensions.EXT nuget. You can just cast `FloatBufferFormat.XYZ` to `BufferFormat` when calling `BufferData()` and it should work fine.

**Comment by tilkinsc** [comment]
> This is part of the Silk.NET.OpenAL.Extensions.EXT nuget. You can just cast `FloatBufferFormat.XYZ` to `BufferFormat` when calling `BufferData()` and it should work fine.

alBufferData will accept the enums, therefore it shall without explicit casts.

> thats not exactly what i meant, i meant an extension method over the methods that can take FloatFormat, not an operator override from FloatFormat -> BufferFormat

```cs
namespace Silk.NET.OpenAL.Extensions.EXT
{
    /// <summary>
    /// Exposes the multi-channel buffers extension by Creative Labs.
    /// </summary>
    [Extension("AL_EXT_float32")]
    [NativeApi(Prefix = "al")]
    public partial class FloatFormat : FormatExtensionBase<FloatBufferFormat>
    {
        /// <inheritdoc cref="ExtensionBase" />
        public FloatFormat(INativeContext ctx)
            : base(ctx)
        {
        }
    }
    
    public static class FloatFormatALExtensions
    {
        public unsafe static void BufferData(this AL al, uint buffer, FloatBufferFormat format, void* data, int size, int frequency)
        {
            return al.BufferData(buffer, (BufferFormat) format, data, size, frequency);
        }
    }
}
```

So something like this?

**Comment by Beyley** [comment]
Something like that yeah, make sure to do this for all functions that may take in a FloatBufferFormat

**Comment by tilkinsc** [comment]
The spec only mentions alBufferData and I am not aware of any other functions.

**Comment by ohtrobinson** [comment]
> alBufferData will accept the enums, therefore it shall without explicit casts.

it does not support this, I just tested it, you will need to cast it to BufferFormat, however it should work like normal

**Comment by Beyley** [comment]
> > alBufferData will accept the enums, therefore it shall without explicit casts.
> 
> it does not support this, I just tested it, you will need to cast it to BufferFormat, however it should work like normal

They are talking about in C, not Silk.NET

**Comment by ohtrobinson** [comment]
ah, I misread the original issue.

**Comment by tilkinsc** [comment]
> The spec only mentions alBufferData and I am not aware of any other functions. There is capture. I am not sure if capture can do floats though.

I won't be testing the possibility of capture being able to take and emit floats.

**Comment by tilkinsc** [comment]
Do you know if inheritdoc is smart enough to transcend extension methods?
