### ISSUE TITLE
Native symbol not found (Symbol: glCreateProgram)

### ISSUE THREAD

**Issue by Desync3** [dotnet/Silk.NET#1188]
![image](https://user-images.githubusercontent.com/49792134/209861741-139d8bf4-1339-4939-99f7-8b73dbb667cd.png)

The program works for me on my windows machine but on my vps it gave an error "Silk.NET.Core.Loader.SymbolLoadingException: 'Native symbol not found (Symbol: glCreateProgram)'" so i tried installing visual studio to see the issue and i get this. I have no idea how to solve it, im guessing the vps needs a library thats not installed?

**Comment by Beyley** [comment]
well, theres a few things, one, you should create only 1 opengl object and save that, not create one to directly pass into ImGui, also its possible that the VPS is like GL1.x or smthn and doesnt have shaders, and/or doesnt have OpenGL at all

**Comment by Perksey** [comment]
The VPS likely doesn't have a GPU and/or OpenGL driver, thus it will be defaulting to OpenGL 1.1 (from 1997). You could use something like ANGLE as a software emulator, but this can be problematic to setup.

**Comment by Beyley** [comment]
If your VPS supports Direct3D12, you also have the option of GLonD3D12 (built into modern windows), and if it doesnt support D3D12, you can enable WARP
