### ISSUE TITLE
Silk.Net.Windowing.Glfw.GlfwWindow.Create<T>() Broken on Apple Silicon MacOsX Ventura

### ISSUE THREAD

**Issue by viniciusmiguel** [dotnet/Silk.NET#1192]
# Summary
When trying to create a surface for Vulkan the CreateWindowSurface native call crashes the runtime.

# Steps to reproduce
- Platform: Desktop MacOsX Ventura 13.1
[crashreport.txt](https://github.com/dotnet/Silk.NET/files/10325640/crashreport.txt)

- Framework Version: .NET Core 3.1
- API: Vulkan
- API Version: Vulkan 1.2.236
1. Testing the ImGuiVulkan Lab on Mac or other projects using Silk.Net with Vulkan, which works on windows.
The validation layer needs to be disabled to work on Apple Silicon.

# Comments
Attached is the crash report.

Please fix this since Silk + Vulkan is unusable with a mac.

**Comment by Perksey** [comment]
The lab projects are not intended for general consumption, and are strictly experimental applications for usage by the Silk.NET team only for testing purposes.

Do you have an example of this error using your own code?

**Comment by viniciusmiguel** [comment]
> The lab projects are not intended for general consumption, and are strictly experimental applications for usage by the Silk.NET team only for testing purposes.
> 
> Do you have an example of this error using your own code?

https://github.com/dfkeenan/SilkVulkanTutorial

This should do the trick :)

**Comment by Perksey** [comment]
Have you tried using Vulkan without validation layers? It seems this is a Vulkan Loader/Layer bug (not a Silk.NET bug), but these days you shouldn't really be configuring Validation Layers in code (preferring tools like vkconfig instead).

**Comment by viniciusmiguel** [comment]
Yes, validation layers do not work and I am disabling them on the Mac to test.

**Comment by Perksey** [comment]
To clarify, it works when you've turned off validation layers? Or does it not work whatsoever?

**Comment by viniciusmiguel** [comment]
This error shows up when validation layers are disabled and the solution proceeds to the point where CreateWindowSurface  is called, that crashes the runtime generating the error report attached.

**Comment by Perksey** [comment]
This doesn't appear to be a Silk.NET bug. Judging by the stack trace this is getting lost in the MoltenVK driver, so I would open an issue on [MoltenVK](https://github.com/KhronosGroup/MoltenVK).

Alternatively, you can try using without Rosetta (i.e. trying arm64 native .NET). Hope this helps.
