### ISSUE TITLE
Vk.GetPhysicalDeviceProperties2 Error

### ISSUE THREAD

**Issue by Syncaidius** [dotnet/Silk.NET#1194]
When trying to call the following method:

```csharp
PhysicalDeviceProperties2 dProperties;
Vk.GetPhysicalDeviceProperties2(*devices, &dProperties);
```

I get the following error:
`vkGetPhysicalDeviceProperties2: parameter pProperties->sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2. The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPhysicalDeviceProperties2-sType-sType)`

I have tried manually setting sType to the stated value, in the `dProperties` variable above, but I then get a silent crash with no validation error or C# exception.

From what I can tell so far, it may be due to it getting the parameterless struct constructor mixed up with 
```csharp 
public unsafe PhysicalDeviceProperties2(StructureType? sType = StructureType.PhysicalDeviceProperties2Khr, void* pNext = null, PhysicalDeviceProperties? properties = null)
```
If it defaults to using the parameterless constructor, the sType will not be correctly set.

EDIT: I'm using Silk.NET 2.16

Any other advice/ideas on this?

**Comment by Beyley** [comment]
You can set the type manually, this seems like a problem with the compiler itself just picking the wrong constructor

**Comment by Perksey** [comment]
Yep, the problem here is not initialising your variable before taking its address (which implicitly zero initialises)

Try `var dProperties = new PhysicalDeviceProperties2()`

**Comment by Syncaidius** [comment]
I think the example I gave wasn't good, but I have tried initializing the variable and also setting the struct type, but then the `GetPhysicalDeviceProperties2` call silently crashes the application without any validation errors or C# exceptions.

I'm not sure where I'm going wrong with this?

**Comment by Perksey** [comment]
Have you set the correct version when creating your instance?

If this is not the issue, then you will need to find a way to get the stack trace so we can discern the problem. Usually this is either using Visual Studio with native debugging enabled, or WinDbg (very difficult)

**Comment by Syncaidius** [comment]
Ah I'll check the version during instance creation as soon as Im back at a computer.

If it isn't that, I'll post the stack trace. I'll let you guys know either way.

Thanks for the help so far. Greatly appreciated!

**Comment by Perksey** [comment]
Awesome, glad that's working now.
