### ISSUE TITLE
Silk.Net.Input.Key doesn't implement a lot of the special keys

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1236]
# Summary of feature
The Key class is missing a lot of keys, like volume, OEM keys, Media keys (a huge one), perhaps AltBr (german) which might be World1/World2.

# Comments
The limited amount of keys make it impossible to adopt media keys without depending on input elsewhere.

# Does this have a proposal?
No

**Comment by Beyley** [comment]
Any missing keys can be added to the `Silk.NET.Input.Keys` enum, provided at least one of the windowing backends actually sends out keycodes for those (eg. GLFW/SDL)

**Comment by Perksey** [comment]
I'm going to close this as not planned I think. `Key` is designed to be the lowest common denominator and has a known bias to en-GB. Our advice to people who need language-specific input handling is always to use scancodes. The Working Group would like a proposal for retrieving the current keyboard layout ([as discussed here](https://github.com/dotnet/Silk.NET/pull/397#issuecomment-791635417)) in the future to make using scancodes easier, but this is out of scope of this issue.
