### ISSUE TITLE
Could we get the readme to list the nuget packages

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1248]
# Summary of feature
Its a nightmare browsing nuget to collect packages that I will use. There are so many that span multiple pages mixed in with some other packages that are similar to silk.net. An archive of link references would be very welcome.

**Comment by Perksey** [comment]
The README is quite strategically crafted to be as marketing-y as possible, but it’s possible that we could make a page on the website or some other document containing this

**Comment by tilkinsc** [comment]
Yeah theres no wiki so lol, perhaps another readme file in the root dir?

**Comment by Perksey** [comment]
@dotnet/silk-dotnet how do we feel about this one? Seems like a lot of maintenance effort, that document will get out of date easily and it's not much hardship for the user to just go to https://www.nuget.org/profiles/Silk.NET

**Comment by tilkinsc** [comment]
Well linking to the nugets is different than having the package configure. It's write once add entry for each new library added.

**Comment by Perksey** [comment]
Yeah that is a lot of maintenance effort, the document *will* get out to date quickly.

**Comment by Beyley** [comment]
I feel like this is just unnecessary to maintain, when there are multiple perfectly fine ways of seeing all nuget packages (ie. your IDE of choice can search and view them, you can view our nuget profile, or search for `csproj` files in the repo) The amount of packages that exist in the repo is quite large, and changes rapidly as new extensions are added to GL/VK/CL/XR/etc, as we add new bindings/extensions, its small, but still a maintenance burden we'd have to carry into the future, and would likely be forgotten about and non-updated

**Comment by Beyley** [comment]
feel free to re-open if there is something else to this we aren't understanding, as the team seems in general agreement that this isnt really necessary given the other resources to browse the catalogue of packages
