### ISSUE TITLE
Add IWindow.IsResizing

### ISSUE THREAD

**Issue by desiwko** [dotnet/Silk.NET#1265]
# Summary of feature
Proposal to add a boolean flag to IWindow to support application detection of the resizing event lifetime.

# Comments
When using IWindow.Resize an application has no insight into when a resizing operation ultimately ends.  The IWindow.Resize event is triggered multiple times during the lifespan of what ultimately amounts to an individual resizing operation.  This has undesirable size effects when resource allocations must occur during resizes, such as using a shared OpenGL context and having to regenerate framebuffer objects which can be very resource intensive.  

It would be very useful to know when a resize starts since the initial MouseDown event for a resize operation is NOT captured by the API, and also when it ended so that aforementioned allocations can be orchestrated to only happen once during an aggregate resize event.

As a flag it would allow IWindow.Resize to maintain existing functionality and purpose if so desired.

# Does this have a proposal?
No.

**Comment by Beyley** [comment]
I dont think either GLFW or SDL exposes this information, unless im missing something, this is possible to do on our side

**Comment by Perksey** [comment]
I recommend just doing these updates in the Update callback. The frequency by which Resize is called (other than on resize that is) is undefined (as it is in our underlying window platforms)

**Comment by desiwko** [comment]
> I dont think either GLFW or SDL exposes this information, unless im missing something, this is not possible to do on our side

Fair enough.  After looking through both glfw and SDL I don't see any trivial mechanisms to detect the begin and end of a resize.

> I recommend just doing these updates in the Update callback. The frequency by which Resize is called (other than on resize that is) is undefined (as it is in our underlying window platforms)

I know the update frequency is adjustable, but still being tied to a constant stream of resize events this really wouldn't resolve the issue in a sane manner.  Sounds like a limitation based on underlying constraints that can't be resolved in an elegant manner.

**Comment by Perksey** [comment]
Update won’t run until the event queue is unclogged (i.e. when the window has been dropped)

**Comment by Perksey** [comment]
Same with render

**Comment by Perksey** [comment]
Going to close this as "won't fix" I think, behaviour here is not consistent across platforms (and can't be really) and I don't think we're ready to do anything other than leave this undefined. Good enough workarounds are provided above.
