### ISSUE TITLE
Silk.NET.SDL RWops functions missing

### ISSUE THREAD

**Issue by tadeokondrak** [dotnet/Silk.NET#1297]
Silk.NET.SDL is missing the following functions and macros from `SDL_rwops.h`. The header is excluded from the build process because the `SDL_RWops` structure itself is platform specific, but pointers to it work fine, so these functions would work too.

I would have liked to submit a PR fixing this but it looks like I'd have to sign a CLA to do so.
```
SDL_RWFromFile
SDL_RWFromFP
SDL_RWFromMem
SDL_RWFromConstMem
SDL_AllocRW
SDL_FreeRW
SDL_RWsize
SDL_RWseek (RW_SEEK_SET, RW_SEEK_CUR, RW_SEEK_END)
SDL_RWtell
SDL_RWread
SDL_RWwrite
SDL_RWclose
SDL_LoadFile_RW
SDL_LoadFile
SDL_ReadU8
SDL_ReadLE16
SDL_ReadBE16
SDL_ReadLE32
SDL_ReadBE32
SDL_ReadLE64
SDL_ReadBE64
SDL_WriteU8
SDL_WriteLE16
SDL_WriteBE16
SDL_WriteLE32
SDL_WriteBE32
SDL_WriteLE64
SDL_WriteBE64
```

**Comment by Beyley** [comment]
the SDL bindings are not *really* built for external consumption, they are only meant to include what is needed for Silk.NET.Windowing's uses, this isnt something the team is likely to fix on their own, but i dont think we would be against a PR adding said functions

**Comment by Perksey** [comment]
I think we'll accept a PR for this but the SDL bindings are pretty much as widely scoped as they're going to be for now.
