### ISSUE TITLE
IsInstanceExtensionPresent/TryGetInstanceExtension and layers

### ISSUE THREAD

**Issue by konstantinegorov** [dotnet/Silk.NET#1298]
The IsInstanceExtensionPresent/TryGetInstanceExtension functions don't take into account a layer, and report only core extensions (or extensions from implicitly enabled layers), but there are some extensions, that may not provided by core implementation, but are provided in layer. For example, VK_EXT_debug_utils may not be present in core, but is present in VK_LAYER_KHRONOS_validation

**Comment by Perksey** [comment]
I don’t think this is the case? @Beyley have you seen this? Layers should override the GetInstanceExtensionProperties (or whatever it’s called) function to denote their extensions.

**Comment by konstantinegorov** [comment]
Will the code below work if the core implementation doesn't provide VK_EXT_debug_utils?

InstanceCreateInfo instance_info = {
  enabled_layers = [] { "VK_LAYER_KHRONOS_validation" },
  enabled_extensions = [] { "VK_EXT_debug_utils" }
}

vk.CreateInstance(instance_info, out var instance);

instance.TryGetExtension<EXTDebugUtils>(out var debugUtils)

debugUtils != null ??

**Comment by Perksey** [comment]
Should do yes but you’ll have to try it to be sure.

**Comment by konstantinegorov** [comment]
from the spec about vkEnumerateInstanceExtensionProperties:

> When pLayerName parameter is NULL, only extensions provided by the Vulkan implementation or by implicitly enabled layers are returned. When pLayerName is the name of a layer, the instance extensions provided by that layer are returned.

So IsInstanceExtensionPresent will most likely return false for extensions provided only by layers.

**Comment by Perksey** [comment]
Thanks. If a community member added support for explicit layers (probably just an optional parameter in the respective methods) we’d be happy to accept a PR.
