### ISSUE TITLE
Android OpenGL Sample did not start

### ISSUE THREAD

**Issue by rodrigovaras** [dotnet/Silk.NET#1307]
# Summary
Tried to build and run the Android demo sample and I get:
I did some research and I notice somebody open a similar bug that was closed.
It seems the situation has not changed since I get this (problems with bluetooth permissions):

Java.Lang.RuntimeException: 'Unable to start activity ComponentInfo{com.companyname.AndroidDemo/crc640cc520f458eee55e.MainActivity}: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@a7e74ba0: AdapterService getBondedDevices'

**Comment by Beyley** [comment]
this is an SDL thing to my knowledge, you need to add the BLUETOOTH_CONNECT permission to the manifest

**Comment by rodrigovaras** [comment]
I did several attempts none of them worked.
I added this to Android manifest without any luck:
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

**Comment by HurricanKai** [comment]
You didn't attach anything.
But as another hint, on older versions the permission might just be called BLUETOOH, maybe that applies? See [the official docs](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter)

**Comment by rodrigovaras** [comment]
here is the log:
I'm just running the sample from the app which definitely does not work. Adding all the bluetooth permission still does not make it work:

Loaded assembly: /data/data/com.companyname.AndroidDemo/files/.__override__/System.Runtime.InteropServices.RuntimeInformation.dll [External]
[SDL] Device: sargo
[SDL] Model: Pixel 3a
[SDL] onCreate()
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.AndroidDemo/files/.__override__/System.Collections.Concurrent.dll [External]
[SDL] nativeSetupJNI()
[SDL] AUDIO nativeSetupJNI()
[SDL] CONTROLLER nativeSetupJNI()
[hidapi] Initializing Bluetooth
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: SDLActivity
[AndroidRuntime] Process: com.companyname.AndroidDemo, PID: 14031
[AndroidRuntime] java.lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.AndroidDemo/crc640cc520f458eee55e.MainActivity}: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@322238cb: AdapterService getBondedDevices
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)

**Comment by Perksey** [comment]
We've had a similar report in January. Basically:
- Use .NET 7
- Ensure your android manifest has BLUETOOTH_CONNECT.
- Use Android API 31 for best results.
- Build in release mode
- Uninstall the app before reinstalling the freshly built one
- Do a dotnet clean before building if the issue persists.

If the issue persists with this same specific error there is something very wrong outside of our control.

**Comment by rodrigovaras** [comment]
> We've had a similar report in January. Basically:
> 
> * Use .NET 7
> * Ensure your android manifest has BLUETOOTH_CONNECT.
> * Use Android API 31 for best results.
> * Build in release mode
> * Uninstall the app before reinstalling the freshly built one
> * Do a dotnet clean before building if the issue persists.
> 
> If the issue persists with this same specific error there is something very wrong outside of our control.

Why the Silk.NET repo hasn't been updated then ? The issue is around using the same repo and running the supported sample which clearly does not work. I have replicate the same problem outside the repo using the Silk.NET packages to use the SilkActivity

**Comment by Perksey** [comment]
If you would like to see the repo updated we would welcome a PR.

**Comment by LloydJHowarth** [comment]
@Perksey I have the same issue. I've added all the permissions, followed your steps in the previous reply and still nothing is working. It just keeps stating in the log that I need the bluetooth_connect permission even though it's already set

**Comment by Perksey** [comment]
Which android version is being used?

**Comment by LloydJHowarth** [comment]
@Perksey Android 12.0 (API 31) .NET 7

**Comment by LloydJHowarth** [comment]
@Perksey Android 12.0 (API 31) .NET 7

I've managed to get the permissions resolved.. But now the application loads the window with the SILK.NET Title then closes because of error

"[ERROR] FATAL UNHANDLED EXCEPTION: Silk.NET.SDL.SdlException: Could not create EGL context (call to eglCreateContext failed, reporting an error of EGL_BAD_CONFIG)
   at Silk.NET.SDL.Sdl.ThrowError()
   at Silk.NET.SDL.SdlContext.Create(ValueTuple`2[] attributes)
   at Silk.NET.Windowing.Sdl.SdlView.CoreInitialize(ViewOptions opts, Nullable`1 additionalFlags, Nullable`1 x, Nullable`1 y, Nullable`1 w, Nullable`1 h, String title, IGLContext sharedContext)
   at Silk.NET.Windowing.Sdl.SdlView.CoreInitialize(ViewOptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at AndroidDemo.GLActivity.OnRun()
   at Silk.NET.Windowing.Sdl.Android.SilkActivity.Run()
   at Silk.NET.Windowing.Sdl.Android.SilkActivity.Main()"

**Comment by LloydJHowarth** [comment]
@Perksey

# Android 12.0 (API 31) .NET 7

# Problem 1
- Need android.permission.BLUETOOTH_CONNECT permission for android

# Solution to problem 1
- Ensure your android manifest has BLUETOOTH_CONNECT
- Request BLUETOOTH_CONNECT permission at runtime using code below (This needs to be done in OnCreate)


        // Code Example in MainActivity.cs
        protected override void OnCreate(Bundle savedInstanceState)
        {
            // Check if the BLUETOOTH_CONNECT permission is granted
            if (CheckSelfPermission(Android.Manifest.Permission.BluetoothConnect) != Android.Content.PM.Permission.Granted)
            {
                RequestPermissions(new string[] { Android.Manifest.Permission.BluetoothConnect }, 0);
            }

            // ENSURE YOU DO PERMISSION BEFORE THIS LINE
            base.OnCreate(savedInstanceState);

            // Create another "Activity" use the SILK.NET Example code and name it "GLActivity"
            // This will get the permissions first, then launch the SILK.NET Demo window
            Intent glActivity = new Intent(this, typeof(GLActivity));
            StartActivity(glActivity);
            Finish();
        }

# Problem 2
"[ERROR] FATAL UNHANDLED EXCEPTION: Silk.NET.SDL.SdlException: Could not create EGL context (call to eglCreateContext failed, reporting an error of EGL_BAD_CONFIG)
at Silk.NET.SDL.Sdl.ThrowError()
at Silk.NET.SDL.SdlContext.Create(ValueTuple2[] attributes) at Silk.NET.Windowing.Sdl.SdlView.CoreInitialize(ViewOptions opts, Nullable1 additionalFlags, Nullable1 x, Nullable1 y, Nullable1 w, Nullable1 h, String title, IGLContext sharedContext)
at Silk.NET.Windowing.Sdl.SdlView.CoreInitialize(ViewOptions opts)
at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
at Silk.NET.Windowing.WindowExtensions.Run(IView view)
at AndroidDemo.GLActivity.OnRun()
at Silk.NET.Windowing.Sdl.Android.SilkActivity.Run()
at Silk.NET.Windowing.Sdl.Android.SilkActivity.Main()"

# Solution to problem 2
- Device doesn't support APIVersion 3 (OpenGL ES 3.0) so I used new APIVersion(2, 0)); (OpenGL ES 2.0)

All problems are now solved, there is the solution for anyone else having a similar problem

**Comment by Perksey** [comment]
Ah excellent, thank you so much for the detail. I’ll look at making the user experience better here.

**Comment by Beyley** [comment]
Closed by #1372
