### ISSUE TITLE
Missing GLFW_ANGLE_PLATFORM_TYPE ?

### ISSUE THREAD

**Issue by cyraid** [dotnet/Silk.NET#1317]
# Summary
Can you add GLFW_ANGLE_PLATFORM_TYPE for the shared initialization hints for InitHint? (glfwInitHint). The second value should be an int, to support for example GLFW_ANGLE_PLATFORM_TYPE.

You could add:

```csharp
public enum InitHint {
  // ...
  AnglePlatformType = 0x00050002
  // ...
}
```

And perhaps changing bool to int for second parameter of `InitHint`, like this:
```csharp
public partial void InitHint(InitHint hint, int value);
```

Since this is the official code from glfw3:

```c
GLFWAPI void glfwInitHint(int hint, int value);
```

# Steps to reproduce
- Platform: Mobile/Desktop
- Framework Version: .NET Core 7
- API: OpenGL
- API Version: OpenGLES/ANGLE
1. Trying with `GlfwProvider.UninitializedGLFW.Value.InitHint()` and with `WindowHint(WindowHintContextApi.ContextCreationApi, ContextApi.EglContextApi);`
2. Cannot specify InitHint to use ANGLE.

I'm also attempting to use the Silk.NET.OpenGLES.ANGLE.Native binaries.

**Comment by ohtrobinson** [comment]
This looks like it was added in GLFW 3.4 (that's when the docs mention it anyway), however currently Silk uses 3.3. This should be automatically added when Silk's GLFW bindings are updated to 3.4.

**Comment by Perksey** [comment]
@ohtrobinson This is incorrect, our GLFW bindings are hand-written.

@cyraid Thanks, I agree this would be useful. We'd happily welcome a PR for this.

**Comment by ohtrobinson** [comment]
> @ohtrobinson This is incorrect, our GLFW bindings are hand-written.

Oh my bad. I thought they were auto generated.

**Comment by Perksey** [comment]
Don't be silly, that'd be too sensible!

**Comment by cyraid** [comment]
> This looks like it was added in GLFW 3.4 (that's when the docs mention it anyway), however currently Silk uses 3.3. This should be automatically added when Silk's GLFW bindings are updated to 3.4.

Indeed, ANGLE type is for GLFW 3.4. But regardless, `GLFWAPI void glfwInitHint(int hint, int value);` is for 3.3 stable as well so it'd be needed anyway. The library will just throw an InvalidEnum when using ANGLE and 3.3 stable anyway. Also GLFW technically uses GLFW_FALSE (=0) and GLFW_TRUE (=1) for their truthy values for InitHint.

**Comment by cyraid** [comment]
Added the Pull Request, let me know what you think @Perksey 
Take care.
