### ISSUE TITLE
Using `Silk.NET.Windowing` with `SkiaSharp` generates a `Native symbol not found` exception

### ISSUE THREAD

**Issue by bmitc** [dotnet/Silk.NET#1337]
# Summary
I was trying to create a simple example of drawing with SkiaSharp and Silk.NET Windowing. If I directly use the GLFW bindings in `Silk.NET.GLFW`, then everything works correctly. However, if I use the higher level `Silk.NET.Windowing` abstraction, I get an error.

For the attached code, the window opens, but then the following exception is generated:
> Unhandled exception. Silk.NET.Core.Loader.SymbolLoadingException: Native symbol not found (Symbol: eglQueryString)
   at Silk.NET.GLFW.GlfwContext.<GetProcAddress>g__Throw|3_0(String proc)
   at Silk.NET.GLFW.GlfwContext.GetProcAddress(String proc, Nullable`1 slot)
   at SilkNETWindowingBug.grGlInterface@16.Invoke(String name) in <path-to-project>\SilkNETWindowingBug\SilkNETWindowingBug.fs:line 16
   at SkiaSharp.DelegateProxies.GRGlGetProcDelegateProxyImplementation(Void* context, Void* name)
   at SkiaSharp.SkiaApi.gr_glinterface_assemble_interface(Void* ctx, GRGlGetProcProxyDelegate get)
   at SkiaSharp.GRGlInterface.Create(GRGlGetProcedureAddressDelegate get)
   at <StartupCode$SilkNETWindowingBug>.$SilkNETWindowingBug.main@() in <path-to-project>\SilkNETWindowingBug\SilkNETWindowingBug.fs:line 16
> <path-to-project>\SilkNETWindowingBug\bin\Debug\net7.0\SilkNETWindowingBug.exe (process 25860) exited with code -532462766.
Press any key to close this window . . .

The issue appears to be in this line:
```fsharp
let grGlInterface = GRGlInterface.Create(fun name -> window.GLContext.GetProcAddress name)
```

But in another project file where only the GLFW bindings are used, like this:
```fsharp
let grGlInterface = GRGlInterface.Create(fun name -> glfw.GetProcAddress name)
```
everything works fine.

So it appears that there's a possible issue in the Silk.NET Windowing abstraction. I did try and force `Silk.NET.Windowing` to use GLFW, which I understood to be the default anyway, but I either didn't do it correctly or the issue still exists in the abstraction as it had no effect.

# Steps to reproduce
- Platform: Desktop, Windows 11
- Framework Version: .NET 7, F# 7
- API: OpenGL
- API Version: OpenGL 4.6 Core

1. Download the attached code.
2. Run the program.

[SilkNETWindowingBug.zip](https://github.com/dotnet/Silk.NET/files/10998596/SilkNETWindowingBug.zip)

# Comments
None at the moment.

**Comment by Beyley** [comment]
Given the error "eglQueryString" it seems like you need to force EGL to be used, but on most systems, EGL generally is not the default, WGL on windows, and GLX on linux (x11), could you show the raw GLFW version?

**Comment by bmitc** [comment]
I threw this print statement in:
```fsharp
printfn "Major: %A, Minor: %A, Profile: %A, API: %A"
    window.API.Version.MajorVersion
    window.API.Version.MinorVersion
    window.API.Profile
    window.API.API
```
and got:
> Major: 3, Minor: 3, Profile: Core, Other: OpenGL

So I assume that means GLFW 3.3 is being used, which makes sense since it's the latest. OpenGL 4.6 is installed on the machine, confirmed via OpenGL Extensions Viewer.

**Comment by bmitc** [comment]
In the project that only uses the Silk.NET GLFW bindings directly and works properly, I placed a print statement for the name passed in and passed to `GetProcAddress`:
```fsharp
let grGlInterface = GRGlInterface.Create(fun name ->
    printfn "%s" name
    glfw.GetProcAddress name)
```

The following are printed out, and `eglQueryString` is among those printed.

<details>
glGetString
glGetString
glGetStringi
glGetIntegerv
eglQueryString
glActiveTexture
glAttachShader
glBindAttribLocation
glBindBuffer
glBindTexture
glBlendColor
glBlendEquation
glBlendFunc
glBufferData
glBufferSubData
glClear
glClearColor
glClearStencil
glColorMask
glCompileShader
glCompressedTexImage2D
glCompressedTexSubImage2D
glCopyTexSubImage2D
glCreateProgram
glCreateShader
glCullFace
glDeleteBuffers
glDeleteProgram
glDeleteShader
glDeleteTextures
glDepthMask
glDisable
glDisableVertexAttribArray
glDrawArrays
glDrawElements
glEnable
glEnableVertexAttribArray
glFinish
glFlush
glFrontFace
glGenBuffers
glGenTextures
glGetBufferParameteriv
glGetError
glGetIntegerv
glGetProgramInfoLog
glGetProgramiv
glGetShaderInfoLog
glGetShaderiv
glGetString
glGetUniformLocation
glIsTexture
glLineWidth
glLinkProgram
glPixelStorei
glReadPixels
glScissor
glShaderSource
glStencilFunc
glStencilFuncSeparate
glStencilMask
glStencilMaskSeparate
glStencilOp
glStencilOpSeparate
glTexImage2D
glTexParameterf
glTexParameterfv
glTexParameteri
glTexParameteriv
glTexSubImage2D
glUniform1f
glUniform1fv
glUniform1i
glUniform1iv
glUniform2f
glUniform2fv
glUniform2i
glUniform2iv
glUniform3f
glUniform3fv
glUniform3i
glUniform3iv
glUniform4f
glUniform4fv
glUniform4i
glUniform4iv
glUniformMatrix2fv
glUniformMatrix3fv
glUniformMatrix4fv
glUseProgram
glVertexAttrib1f
glVertexAttrib2fv
glVertexAttrib3fv
glVertexAttrib4fv
glVertexAttribPointer
glViewport
glDrawBuffer
glPolygonMode
glGetStringi
glMemoryBarrier
glBindVertexArray
glDeleteVertexArrays
glGenVertexArrays
glPatchParameteri
glBindFragDataLocation
glBindFragDataLocationIndexed
glBlendBarrierKHR
glClearTexImage
glClearTexSubImage
glDrawArraysInstanced
glDrawElementsInstanced
glDrawArraysInstancedBaseInstance
glDrawElementsInstancedBaseVertexBaseInstance
glDrawBuffers
glReadBuffer
glDrawArraysIndirect
glDrawElementsIndirect
glDrawRangeElements
glGetMultisamplefv
glGetTexLevelParameteriv
glMultiDrawArraysIndirect
glMultiDrawElementsIndirect
glTexBuffer
glTexBufferRange
glTexStorage2D
glTextureBarrier
glVertexAttribDivisor
glVertexAttribIPointer
glBindFramebuffer
glBindRenderbuffer
glCheckFramebufferStatus
glDeleteFramebuffers
glDeleteRenderbuffers
glFramebufferRenderbuffer
glFramebufferTexture2D
glGenFramebuffers
glGenRenderbuffers
glGenerateMipmap
glGetFramebufferAttachmentParameteriv
glGetRenderbufferParameteriv
glRenderbufferStorage
glBlitFramebuffer
glRenderbufferStorageMultisample
glMapBuffer
glUnmapBuffer
glFlushMappedBufferRange
glMapBufferRange
glGetProgramResourceLocation
glMatrixLoadIdentityEXT
glMatrixLoadfEXT
glCoverFillPathNV
glCoverFillPathInstancedNV
glCoverStrokePathNV
glCoverStrokePathInstancedNV
glDeletePathsNV
glGenPathsNV
glIsPathNV
glPathCommandsNV
glPathParameterfNV
glPathParameteriNV
glPathStencilFuncNV
glProgramPathFragmentInputGenNV
glStencilFillPathNV
glStencilFillPathInstancedNV
glStencilStrokePathNV
glStencilStrokePathInstancedNV
glStencilThenCoverFillPathNV
glStencilThenCoverFillPathInstancedNV
glStencilThenCoverStrokePathNV
glStencilThenCoverStrokePathInstancedNV
glCoverageModulationNV
glDebugMessageCallback
glDebugMessageControl
glDebugMessageInsert
glGetDebugMessageLog
glObjectLabel
glPopDebugGroup
glPushDebugGroup
glWindowRectanglesEXT
glClientWaitSync
glDeleteSync
glFenceSync
glIsSync
glWaitSync
glGetInternalformativ
glGetProgramBinary
glProgramBinary
glProgramParameteri
glBindSampler
glDeleteSamplers
glGenSamplers
glSamplerParameteri
glSamplerParameteriv
glGetQueryObjectiv
glGetQueryObjecti64v
glGetQueryObjectui64v
glQueryCounter
glInvalidateBufferData
glInvalidateBufferSubData
glInvalidateTexImage
glInvalidateTexSubImage
glInvalidateFramebuffer
glInvalidateSubFramebuffer
glGetShaderPrecisionFormat
glDeleteFencesNV
glFinishFenceNV
glGenFencesNV
glSetFenceNV
glTestFenceNV
</details>

**Comment by Beyley** [comment]
> I threw this print statement in:
> 
> ```fsharp
> printfn "Major: %A, Minor: %A, Profile: %A, API: %A"
>     window.API.Version.MajorVersion
>     window.API.Version.MinorVersion
>     window.API.Profile
>     window.API.API
> ```
> 
> and got:
> 
> > Major: 3, Minor: 3, Profile: Core, Other: OpenGL
> 
> So I assume that means GLFW 3.3 is being used, which makes sense since it's the latest. OpenGL 4.6 is installed on the machine, confirmed via OpenGL Extensions Viewer.

that means OpenGL 3.3 not GLFW 3.3

**Comment by bmitc** [comment]
Oh, I see. The `API` property is not very clear or documented.

Why is OpenGL 3.3 being used then when OpenGL 4.6 is present? What is the windowing abstraction doing differently than just using the GLFW bindings?

**Comment by Perksey** [comment]
That exception is a red herring, use TryGetProcAddress which doesn’t throw an exception. Skia checks whether EGL functions are present to enable EGL-specific functionality, but will not fail if we return 0 from that function.

**Comment by Beyley** [comment]
Has perksey's suggestion of using the fallible `TryGetProcAddress` version worked?

**Comment by Perksey** [comment]
No response from user, assuming suggestion has worked.

**Comment by HurricanKai** [comment]
Please elaborate why you think this is only a workaround.
Skia will attempt to resolve specific egl extensions, if the symbol can't be found it expects 0 to be returned, indicating that the function and therefore the extension isn't present.
This is exactly what you get from our TryGetProcAddress.
If you can't resolve a symbol that you think you should be able to, this is likely a configuration error. See comments above about the default standard version requested by our windowing implementation.
If you think there's still a bug somewhere that prevents symbols from being resolved by silk that should be available, please explain here or open a new issue.
