### ISSUE TITLE
GLFW3.dll missing in Net461 projects

### ISSUE THREAD

**Issue by paralaxsd** [dotnet/Silk.NET#1356]
# Summary
Hi,
I stumbled upon an issue where the native `glfw3.dll` would not be copied to a console app's output directory if targeting the .Net 4.6.1 framework. I stripped the issue down to the basics and [published a repository that demonstrates the issue](https://github.com/paralaxsd/ultz.native.glw-framework-test).

I also looked at the [Silk.NET.GLFW.Native](https://github.com/dotnet/Silk.NET/blob/main/src/Native/Silk.NET.GLFW.Native/Silk.NET.GLFW.Native.csproj) project and compared the approach to other .net libraries with native dependencies [[1](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/build/net40/ImGui.NET.targets)], [[2](https://github.com/mono/SkiaSharp/blob/main/binding/SkiaSharp/nuget/build/net462/SkiaSharp.targets)]. These projects are using a `.targets` rather than a `.props` file for copying their native dependencies on .Net 4.

I have locally tested with an adapted nuget package that's using a .targets file instead and it fixes this issue. [I am providing a hotfix branch](https://github.com/paralaxsd/Silk.NET/commit/d81fda7166e00fefb37ac048b870d48090ebd605) that could be converted into a pull request.

# Steps to reproduce
* Clone the repository from https://github.com/paralaxsd/ultz.native.glw-framework-test
* Open the Visual Studio solution and compile both projects
* Observe (as mentioned in the readme) that the `net461` project is missing `glfw3.dll` while the file should be copied into its output directory as per [Ultz.Native.GLFW.props](https://github.com/dotnet/Silk.NET/blob/main/src/Native/Silk.NET.GLFW.Native/build/net461/Ultz.Native.GLFW.props). The `.net7` project is using a different mechanism for pulling in the libraries and will not be affected.

It stands to reason that the same issue should also befall `Ultz.Native.SDL` but I have not tested this.

**Comment by Perksey** [comment]
Sounds like a good fix we’d be happy to take as a PR, but just update to a modern .NET version haha

**Comment by paralaxsd** [comment]
> Sounds like a good fix we’d be happy to take as a PR, but just update to a modern .NET version haha

It's a strategic thing really. My original project supports .net 4 - 7 but .net7 is def more fun :)

But in any case, thanks - let me prepare the PR then...

**Comment by Perksey** [comment]
Thanks for the fix! :)

**Comment by paralaxsd** [comment]
I'm glad I could help :)
