### ISSUE TITLE
Memory Leak in StringArrayToMemory

### ISSUE THREAD

**Issue by Khitiara** [dotnet/Silk.NET#1358]
# Summary
Unmanaged memory leak in `SilkMarshal.StringArrayToMemory`.
Specifically, the returned `GlobalMemory` has no means or mechanism to free the individual strings in the array, whereas `StringArrayToPtr` storesextra context which `SilkMarshal.Free` can use to free the strings.

# Steps to reproduce
https://github.com/Khitiara/SilkMemoryCheck 
When running the provided code, the benchmark for StringArrayToPtr completes but the benchmark for StringArrayToMemory consumes increasing memory with diverging execution time.

**Comment by Khitiara** [comment]
I was considering sending a pull request but im not sure what the best/simplest way to actually idiomatically fix this would be.

**Comment by Perksey** [comment]
You use the Dispose method instead.

**Comment by Perksey** [comment]
Oh I see what you mean. Yes I think you’re still expected to call SilkMarshal.Free on each of the individual pointers, but call Dispose on the containing GlobalMemory. We could in theory add some metadata in GlobalMemory to sweep up the child pointers as well if you felt like improving this.

**Comment by Khitiara** [comment]
The reason Id consider it a bug is calling SilkMarshal.Free on the intptr from StringArrayToPtr does free the individual pointers but dispose on the globalmemory doesnt, so the behavior is inconsistent there.  Ill look into ideas on adding the metadata somehow
