### ISSUE TITLE
Update SDL2.dll on Windows

### ISSUE THREAD

**Issue by skyebird189** [dotnet/Silk.NET#1424]
# Summary
The version of SDL that `Silk.NET.SDL` targets is newer than the DLL that `Ultz.Native.SDL` outputs, meaning that some newer methods (specifically `SDL_GetWindowSizeInPixels`) are not present in the existing DLL.

# Steps to reproduce
- Platform: Windows
Just use any SDL function that is present in >SDL 2.14.0, in my example SDL_GetWindowSizeInPixels which was added in SDL 2.26.

# Comments
I am going to look to open a PR simply replacing the SDL DLLs with the versions available on the SDL releases page, but I thought I'd open an issue in case there is some CI runner that does it automatically etc.

**Comment by Perksey** [comment]
As discussed in #1425, improvements here will be community-contributed only and will not be tracked by the core team. In addition, the native binary process isn't automated for SDL like the other libs and will need to be done beforehand before accepting any improvements here.
