### ISSUE TITLE
[WebGPU] : Native symbol not found

### ISSUE THREAD

**Issue by ykafia** [dotnet/Silk.NET#1426]
# Summary
A summary of the issue you're experiencing.

# Steps to reproduce
- Platform: Windows
- Framework Version: .NET 7
- API: WebGPU
- API Version: Latest in experimental feed

1. Create a texture
2. Call  api.TextureGetWidth() function 

Errors : 

```
'Native symbol not found (Symbol: wgpuTextureGetWidth)'
'Native symbol not found (Symbol: wgpuBufferGetConstMappedRange)'
```

# Comments
Same happens with some buffer functions

**__If you know how to fix this issue, please submit a pull request instead!__**

**Comment by ykafia** [comment]
That's a good question, i don't really know exactly but i assume vulkan.

That's how i created the device and adapters, didn't provide any info for the driver


```csharp

if (window is not null)
{
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        cs.SType = SType.SurfaceDescriptorFromWindowsHwnd;
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        cs.SType = SType.SurfaceDescriptorFromXlibWindow;
    }
    var desc = new InstanceDescriptor() { NextInChain = &cs };
    Instance = new(Api.CreateInstance(desc));

    Surface surface = new(window.CreateWebGPUSurface(Api, Instance));
    {
        var requestAdapterOptions = new RequestAdapterOptions
        {
            CompatibleSurface = surface.Handle
        };

        Api.InstanceRequestAdapter
        (
            Instance,
            requestAdapterOptions,
            new PfnRequestAdapterCallback((_, adapter1, _, _) => Adapter = new(adapter1)),
            null
        );
    }
}
```

**Comment by Perksey** [comment]
Nono are you using WGPU or Dawn? (or some other driver?)

**Comment by ykafia** [comment]
Ah, i'm using WGPU with the native nuget package you provide

**Comment by Perksey** [comment]
WGPU does not implement those functions at this time, please report this upstream: https://github.com/gfx-rs/wgpu-native/blob/master/src/unimplemented.rs#L282
