### ISSUE TITLE
`IGamepad.LeftStick` and `IGamepad.RightStick` return Buttons instead of Thumbsticks

### ISSUE THREAD

**Issue by jvyden** [dotnet/Silk.NET#1468]
https://github.com/dotnet/Silk.NET/blob/main/src/Input/Silk.NET.Input.Common/GamepadExtensions.cs#L71-L79

Currently, when trying to access a controller's thumbsticks via the `GamepadExtensions` class, it'll return a `Button`. When using this API I expected to see the X/Y values you'd typically see from a joystick, but it just ended up confusing me when all I saw was the "pressed" state.

I do see that `Thumbstick`s do not have pressed states (not all joysticks have buttons of course), but in my opinion it's more intuitive to have the X/Y values first as they are used more often.

I ended up having to do this:
```cs
Thumbstick leftStick = gamepad.Thumbsticks[0];
```
instead of the desirable method:
```cs
Thumbstick leftStick = gamepad.LeftStick();
```

It's not a big deal of course, but it does end up looking a bit messy.

I can open a PR to fix this, but I'd like to gauge interest before I do.

**Comment by Perksey** [comment]
Ah, that is unfortunate should’ve probably been called LeftStickButton or LeftStickPress or something. Yeah happy to accept another extension method for getting the Thumbstick value

**Comment by jvyden** [comment]
Judging by the wording, renaming the existing ones are a no-go? I guess that would be a breaking change...

But that said, what would I even call the new methods? `LeftStickThumbstick` maybe? Sounds a little strange.

**Comment by Perksey** [comment]
Yeah renaming is a no go. The least bad names I can think of are:
- LeftThumbstick
- LSButton

(and then deprecate the old ones).

Still feels naff but idk any better names.
