### ISSUE TITLE
libdl.so is not available on many Linux distros, causing crashes on native library load

### ISSUE THREAD

**Issue by CasualPokePlayer** [dotnet/Silk.NET#1492]
# Summary
Many Linux distros do not have libdl.so, rather they only have libdl.so.2. This causes a `DllNotFoundException` when using its native functions.

This would only occur when using .NET Framework / .NET Standard, as .NET Core / .NET 5+ just use `System.Runtime.InteropServices.NativeLibrary` instead of P/Invoking libdl directly.

According to the loader readme, the code was taken from NativeLibraryLoader, which seems to have [this issue fixed already](https://github.com/mellinoe/nativelibraryloader/pull/19), so it's probably as simple as porting over that fix.

# Steps to reproduce
- Platform: Linux (Ubuntu 22.04 was used for this case)
- Framework Version: .NET Framework / .NET Standard (.NET Core / .NET 5+ is not affected)

1. Do anything which loads in a native library (e.g. Sdl.GetApi).

**Comment by Perksey** [comment]
Thanks for letting us know. I have looked at the fix and concluded that this isn't an appropriate fix for Silk.NET, namely the try-and-catch method tends to create a poor user experience given that users are encouraged to have first chance exception handling on when debugging their applications. As you have identified that this is working on the newer .NET versions, I don't think we will take any action here. Please use the latest .NET.

**Comment by CasualPokePlayer** [comment]
To be clear, upgrading to the latest .NET version is not possible at this time for my use case. I've been looking into Silk.NET to provide bindings for use in the BizHawk project, which is stuck on .NET Framework due to several .NET Framework only dependencies (e.g. OpenTK for OpenAL/OpenGL bindings), so we've been moving away from dependencies one by one by switching them to .NET Standard 2.0, allowing us to easily upgrade when we no longer have .NET Framework dependencies.

Considering that most (if not all?) Linux distros seem to just have libdl.so.2, perhaps it'd be fair to just switch the p/invoke to that?

**Comment by Beyley** [comment]
I would be happy switching exclusively to just `libdl.so.2` this is what [osu-framework does](https://github.com/ppy/osu-framework/blob/b5e8a9bca9bda6b7a9b0127f6c8696685474b34b/osu.Framework/Platform/Linux/Native/Library.cs#L15), and i havent heard of/experienced any problems with that, feel free to open a PR changing that/come onto the discord to discuss more, if you are sure it wont cause any problems
