### ISSUE TITLE
Add SDL_image binding

### ISSUE THREAD

**Issue by kgs233** [dotnet/Silk.NET#1529]
# Summary of feature
Add SDL_image binding on Silk.NET.

# Comments
SDL_Image is often used in the SDL development process, it's also important for my development, I hope this binding can add this project

# Does this have a proposal?
No

**Comment by Perksey** [comment]
As it currently stands, we are only maintaining the GLFW and SDL bindings to the extent required by our Windowing APIs, and given the current 3.0 development plan it is our intention to discontinue our SDL bindings entirely once 2.X has run its course. For this reason, we are no longer adding new features to our SDL bindings. This can of course change, for instance I know there is a lot of interest around SDL 3 and SDL_gpu, but these will be a conversation to have later in the 3.0 development cycle. Thank you for your suggestion though, we do appreciate it and are always looking for ways to improve the experience for our users :)
