### ISSUE TITLE
feat request: sType$default

### ISSUE THREAD

**Issue by hYdos** [dotnet/Silk.NET#1531]
# Summary of feature
instead of manually defining every Struct Type for the Vulkan bindings, Provide the default Structure Type.

# Comments
An example of usage can be seen in the Java library LWJGL. Example from my previous Vulkan usage:
```JAVA
            var appInfo = VkApplicationInfo.calloc(stack)
                    .sType$Default()
                    .pApplicationName(stack.UTF8(provider.name))
                    .pEngineName(stack.UTF8("test"))
                    .engineVersion(0)
                    .apiVersion(VK12.VK_API_VERSION_1_2);
```

# Does this have a proposal?
No, it shouldn't be a massive change I believe

**Comment by Perksey** [comment]
Use the constructor which has the sType argument defaulted.
