### ISSUE TITLE
The SDL2.dll that comes with the NuGet package is so out of date that functions are missing.

### ISSUE THREAD

**Issue by I-Katie** [dotnet/Silk.NET#1539]
# Summary
When calling this: sdl.GetTicks64();
I get this exception: Silk.NET.Core.Loader.SymbolLoadingException: 'Native symbol not found (Symbol: SDL_GetTicks64)'
If I download the SDL2.dll from the SDL2 website and put it in the bin/Debug/net6.0 directory it works fine.
The dll that the NuGet package is providing seems severely out of date. So out of date in fact that it doesn't even have all the functions that are present in the C# code.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 6
- API: SDL
- API Version: SDL2
1. I created a new C# Console App in visual studio
2. Installed Silk.NET.SDL latest stable (2.17.1)
3. Entered the following code into Main()
```
            var sdl = Silk.NET.SDL.Sdl.GetApi();
            if (sdl.Init(Silk.NET.SDL.Sdl.InitVideo) != 0) throw sdl.GetErrorAsException();
            sdl.GetTicks64(); // <- exception gets thrown here with included SDL2.dll

```
4. Pressed the Run button.
5. Got the exception.
6. Took a copy of SDL2.dll from the SDL website and copied it to bin/Debug/net6.0
7. Returned to VS and pressed Run
8. No problems

# Comments
When I provide my own SDL2.dll the function seems to work properly.

I assume you should either keep the dll files up to date or not bundle them with the NuGet package in the first place.

**Comment by Beyley** [comment]
see https://github.com/dotnet/Silk.NET/pull/1425 for our stance on SDL

this specific issue is likely resolved on master anyway after https://github.com/dotnet/Silk.NET/pull/1438
reopen if it still happens on master, but closing for now
