### ISSUE TITLE
Net Wrapper for Google's Filament

### ISSUE THREAD

**Issue by vpenades** [dotnet/Silk.NET#1540]
# Summary of feature

Google's Filament is a C++, cross platform, straightforward graphics engine being developed by Google.

A while ago, they published a C compliant API so people could write wrappers over it.

Considering that Low level APIs like OpenGL/DirectX are not easy to use, this might be a good alternative for many developers.

# Comments

Someone already tried to write a wrapper, but I think it's outdated and no longer supported.

https://github.com/google/filament/discussions/5923

**Comment by Beyley** [comment]
That project looks really interesting! But I'm not sure how likely we'd be to add filament bindings ourselves. 

Given it isn't a standard (like OpenGL/Vulkan) and isn't a widely accepted "standard" library (such as SPIRV-Cross), it doesn't fit the "feel" of the main Silk.NET project. 

While that may be true, feel free to hop on our discord and discuss making community bindings based off of our code generator! We already have an example of this at [the JackCS repo](https://github.com/SilkCommunity/JackCS), which is a fully separate bindings project, still using the Silk.NET bindings generator.
