### ISSUE TITLE
ImGui on Andorid

### ISSUE THREAD

**Issue by CeSun** [dotnet/Silk.NET#1542]
Create an ImGuiController object in Android and throw an exception:
```
System.DllNotFoundException: 'cimgui'
```
nuget reference：
```xml

 <PackageReference Include="Silk.NET" Version="2.16.0" />
 <PackageReference Include="Silk.NET.OpenGL" Version="2.16.0" />
<PackageReference Include="Silk.NET.Input.Common" Version="2.16.0" />
<PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.16.0" />
```

**Comment by Beyley** [comment]
Tracked upstream
https://github.com/ImGuiNET/ImGui.NET/issues/319

**Comment by CeSun** [comment]
> Tracked upstream [ImGuiNET/ImGui.NET#319](https://github.com/ImGuiNET/ImGui.NET/issues/319)

We'll just have to wait for the upstream to fix it, right?

**Comment by Beyley** [comment]
> > Tracked upstream [ImGuiNET/ImGui.NET#319](https://github.com/ImGuiNET/ImGui.NET/issues/319)
> 
> We'll just have to wait for the upstream to fix it, right?

Given mellinoe's situation, i doubt that will happen, you should provide the libraries yourself

**Comment by CeSun** [comment]
> > > Tracked upstream [ImGuiNET/ImGui.NET#319](https://github.com/ImGuiNET/ImGui.NET/issues/319)
> > 
> > 
> > We'll just have to wait for the upstream to fix it, right?
> 
> Given mellinoe's situation, i doubt that will happen, you should provide the libraries yourself

It seems that you only need to put an arm abi's cimgui.so in your Android project. I just tried it and the initialization was successful, but calling the function will hit the assertion (about input)
