### ISSUE TITLE
GLFW multiwindow crash with cursor/mouse callbacks

### ISSUE THREAD

**Issue by desiwko** [dotnet/Silk.NET#1544]
# Summary
When realizing multiple windows using the GLFW backend the application will crash in Silk.NET.GLFW.Glfw.PollEvents() after exercising the windows (change focus, resize, mouse over, etc.) with a callstack similar to the following:

```
Process terminated. A callback was made on a garbage collected delegate of type 'Silk.NET.GLFW!Silk.NET.GLFW.GlfwCallbacks+CursorEnterCallback::Invoke'.
   at Silk.NET.GLFW.Glfw.PollEvents()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Silk.NET.Windowing.IView.DoEvents()
```

The crash timing is random but consistently happens.  I am not able to reproduce this with the SDL backend.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 6, .NET Core 7
- API: OpenGL, GLFW
- API Version: OpenGL 4.5

1. Instantiates two or more Silk windows
2. Instantiate an InputContext (window.CreateInput()) for each window
3. Run the render loop
4. Allow the mouse to traverse between windows to allow for the mouse enter message to event through
5. Observe crashing exception (note: likely will not happen immediately)

# Comments
I've been able to reproduce this on two separate workstations with different hardware profiles in different code bases.  I have seen other garbage collected delegate exceptions but most involve some sort of mouse input delegate attached to Glfw.PollEvent().

Minimal example:
```
using Silk.NET.Windowing;
using Silk.NET.Windowing.Extensions;
using Silk.NET.Input;
using Silk.NET.OpenGL;

namespace ogl;

public class OpenGL
{
    private WindowManager windowManager;
    private List<IInputContext> inputContexts = new List<IInputContext>();

    public OpenGL()
    {
        windowManager = new WindowManager();

        for (int i = 0; i < 4; i++)
            windowManager.CreateWindow(WindowOptions.Default);        
    }

    public void Start()
    {
        foreach(var window in windowManager.Windows)
        {
            window.Load += () =>
            {
                var inputContext = window.CreateInput();
                inputContexts.Add(inputContext);
            };

            window.Render += (time) =>
            {
                var context = GL.GetApi(window.GLContext);

                context.Enable(EnableCap.DepthTest);
                context.ClearColor(0f, .2f, .2f, 1f);
                context.Clear(ClearBufferMask.DepthBufferBit | ClearBufferMask.ColorBufferBit);
            };
        }

        windowManager.Run();
    }
}
```

**Comment by Perksey** [comment]
Wow, it's neat that they added a nice exception message.

Yep know exactly what's causing this, will investigate this on Friday.

**Comment by Perksey** [comment]
I've pushed up a PR that changes the codegen like so:
```diff

        public unsafe partial global::Silk.NET.GLFW.GlfwCallbacks.CharCallback SetCharCallback(global::Silk.NET.GLFW.WindowHandle* window, global::Silk.NET.GLFW.GlfwCallbacks.CharCallback callback)
        {
            global::System.IntPtr n4;
            ; // BEGIN RESOLVE 1 | READCOUNT: 1 | ALLOW_INLINE: True | FORCE_INLINE: False | CACHED: False
            // RESOLVED 1 INLINED
            // END RESOLVE 1
            this.PinUntilNextCall((/* VAR 1 */
-           callback), -712178223); // BEGIN RESOLVE 4 | READCOUNT: 1 | ALLOW_INLINE: False | FORCE_INLINE: False | CACHED: False
+           callback), global::System.HashCode.Combine(-712178223, (nint)window)); // BEGIN RESOLVE 4 | READCOUNT: 1 | ALLOW_INLINE: False | FORCE_INLINE: False | CACHED: False
            // BEGIN RESOLVE 0 | READCOUNT: 1 | ALLOW_INLINE: True | FORCE_INLINE: False | CACHED: False
            // RESOLVED 0 INLINED
            // END RESOLVE 0
            // BEGIN RESOLVE 2 | READCOUNT: 1 | ALLOW_INLINE: True | FORCE_INLINE: False | CACHED: False
            // ALREADY RESOLVED 1
            // RESOLVED 2 INLINED
            // END RESOLVE 2
            // RESOLVED 4 TO VARIABLE n4
            n4 = ((delegate* unmanaged[Cdecl]<global::Silk.NET.GLFW.WindowHandle*, global::System.IntPtr, global::System.IntPtr> )(CurrentVTable as GeneratedVTable).glfwSetCharCallback)((/* VAR 0 */
            window), (/* VAR 1 */
            /* VAR 2 */
            callback == null ? IntPtr.Zero : System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(/* VAR 1 */
            callback))); // END RESOLVE 4
            // BEGIN RESOLVE 3 | READCOUNT: 1 | ALLOW_INLINE: True | FORCE_INLINE: False | CACHED: False
            // ALREADY RESOLVED 4
            // RESOLVED 3 INLINED
            // END RESOLVE 3
            return (/* VAR 4 */
            /* VAR 3 */
            n4 == IntPtr.Zero ? null : System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer<global::Silk.NET.GLFW.GlfwCallbacks.CharCallback>(/* VAR 4 */
            n4));
        }

```

**Comment by Perksey** [comment]
By the way we're keen to get feedback on WindowManager - it's a quite obscure part of the library and we're definitely looking to make the multi-window experience better.

**Comment by desiwko** [comment]
> By the way we're keen to get feedback on WindowManager - it's a quite obscure part of the library and we're definitely looking to make the multi-window experience better.

I bet!  I'll honestly say I didn't even know it existed until I wanted to investigate this issue a little bit more myself and ended up using it for the minimal example above.  I will investigate using WindowManager a bit more as part of the reason multiple windows is of interest to me is in trying to get the ImGui multiple viewports working.  This issue has been a blocker on that front though, so I appreciate the PR!

**Comment by Arugin** [comment]
I got the same crash. Is there any pre release version with this fix that I could get?

**Comment by Perksey** [comment]
https://dotnet.github.io/Silk.NET/docs/silk.net/experimental-feed.html

**Comment by BoyWithRanch** [comment]
Will this fix be published with **2.17.2** ? Couse its nearly impossible to work with the bug in advanced multiwindow. And totally impossible to attach dotMemory 🙂

Everithing works like a charm in the experimental branch 👍

**Comment by Perksey** [comment]
2.18 should be out very soon

**Comment by tingspain** [comment]
Any plan to publish an example of how to use ImGui with multi viewports on silk.net? 

thanks in advance

**Comment by Perksey** [comment]
We welcome contributions to make this area easier, I have no doubt ImGuiController can probably do with changes to make this scenario easier, and if that happens we will likely make a demo for it. But such effort would need to be community-driven.

**Comment by Arugin** [comment]
I made such an implementation in my game engine. It is working, hovewer some functions are missing (like SetFocus() method), so it feels rough. But I may publish it at some point when I have time to clean up code.

**Comment by tingspain** [comment]
@Arugin Could you give me some hint how to achieve it? 

Thanks in advance

@Perksey thanks, if I manage to make it work, I will be more than happy to share it

**Comment by Arugin** [comment]
@tingspain I've basically followed an implementation of multiviewport / docking sample in Imgui.Net repo: https://github.com/ImGuiNET/ImGui.NET/blob/docking/src/ImGui.NET.SampleProgram/ImGuiController.cs

So you basically need to implemet a bunch of delegates that would create / destroy / manipulate windows for Imgui. And every such window would have its own render and event loops. There are also some nuances on how to handle input in different windows. Other than that it is pretty much the same code that Silk.NET repo has.

I'd be happy to publish my implementation, but I am using my custom render graph wrapper around Silk.NET, so the code is very different from Silk.NET implementation.

**Comment by tingspain** [comment]
@Arugin, thank you very much for pointing me to the right direction. I will look into it.
