### ISSUE TITLE
Bool32 Equality operators

### ISSUE THREAD

**Issue by Syncaidius** [dotnet/Silk.NET#1586]
I haven't looked too much into the source code for [Bool32](https://github.com/dotnet/Silk.NET/blob/aaac557a5ed608798e02f63eb1a4282dc13eaf0b/src/Core/Silk.NET.Core/Miscellaneous/Bool32.cs) so I can't tell if it is an auto-generated type, but could `==` and `!=` operators be added to it?

Currently, doing an equality check with Bool32 is `if(a.Value == b.Value)`, which is fine, but it could be simplified to just `if(a == b)` and so on, if the operators were present.

Such operators would make sense for a bool type? 😄

**Comment by Perksey** [comment]
Not autogenerated, would be happy to accept PRs here :)
