### ISSUE TITLE
WebGPU wrong size for bool

### ISSUE THREAD

**Issue by EmilSV** [dotnet/Silk.NET#1593]
# Summary
silk uses bool32 for booleans in WebGPU i have done some tests and using bool32 leads to wrong field offset for RenderBundleEncoderDescriptor and maybe other struct.

# Steps to reproduce
- API: WebGPU

Her are two program that you can compare to see the problem
C
```c
#include <stdio.h>
#include "webgpu.h"

int main()
{
	printf("sizeof  WGPURenderBundleEncoderDescriptor %i \n", (int)sizeof(WGPURenderBundleEncoderDescriptor));
	printf("nextInChain %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, nextInChain));
	printf("label %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, label));
	printf("colorFormatsCount %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, colorFormatsCount));
	printf("colorFormats %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, colorFormats));
	printf("depthStencilFormat %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, depthStencilFormat));
	printf("sampleCount %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, sampleCount));
	printf("depthReadOnly %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, depthReadOnly));
	printf("stencilReadOnly %i \n", (int)offsetof(WGPURenderBundleEncoderDescriptor, stencilReadOnly));
}
```
result:
sizeof  WGPURenderBundleEncoderDescriptor 48
nextInChain 0
label 8
colorFormatsCount 16
colorFormats 24
depthStencilFormat 32
sampleCount 36
depthReadOnly 40
stencilReadOnly 41

C#
```c#
using Silk.NET.WebGPU;

unsafe
{
    RenderBundleEncoderDescriptor value = default;
    Console.WriteLine($"RenderBundleEncoderDescriptor sizeOf: {sizeof(RenderBundleEncoderDescriptor)}");
    Console.WriteLine($"NextInChain :{(int)((byte*)&value.NextInChain - (byte*)&value)}");
    Console.WriteLine($"Label :{(int)((byte*)&value.Label - (byte*)&value)}");
    Console.WriteLine($"ColorFormatsCount :{(int)((byte*)&value.ColorFormatsCount - (byte*)&value)}");
    Console.WriteLine($"ColorFormats :{(int)((byte*)&value.ColorFormats - (byte*)&value)}");
    Console.WriteLine($"DepthStencilFormat :{(int)((byte*)&value.DepthStencilFormat - (byte*)&value)}");
    Console.WriteLine($"SampleCount :{(int)((byte*)&value.SampleCount - (byte*)&value)}");
    Console.WriteLine($"DepthReadOnly :{(int)((byte*)&value.DepthReadOnly - (byte*)&value)}");
    Console.WriteLine($"StencilReadOnly :{(int)((byte*)&value.StencilReadOnly - (byte*)&value)}");
}

Console.WriteLine();

unsafe
{
    RenderBundleEncoderDescriptorBool8 value = default;
    Console.WriteLine($"RenderBundleEncoderDescriptorBool8 sizeOf: {sizeof(RenderBundleEncoderDescriptorBool8)}");
    Console.WriteLine($"NextInChain :{(int)((byte*)&value.NextInChain - (byte*)&value)}");
    Console.WriteLine($"Label :{(int)((byte*)&value.Label - (byte*)&value)}");
    Console.WriteLine($"ColorFormatsCount :{(int)((byte*)&value.ColorFormatsCount - (byte*)&value)}");
    Console.WriteLine($"ColorFormats :{(int)((byte*)&value.ColorFormats - (byte*)&value)}");
    Console.WriteLine($"DepthStencilFormat :{(int)((byte*)&value.DepthStencilFormat - (byte*)&value)}");
    Console.WriteLine($"SampleCount :{(int)((byte*)&value.SampleCount - (byte*)&value)}");
    Console.WriteLine($"DepthReadOnly :{(int)((byte*)&value.DepthReadOnly - (byte*)&value)}");
    Console.WriteLine($"StencilReadOnly :{(int)((byte*)&value.StencilReadOnly - (byte*)&value)}");
}

public unsafe struct RenderBundleEncoderDescriptorBool8
{
    public ChainedStruct* NextInChain;
    public byte* Label;
    public uint ColorFormatsCount;
    public TextureFormat* ColorFormats;
    public TextureFormat DepthStencilFormat;
    public uint SampleCount;
    public bool DepthReadOnly;
    public bool StencilReadOnly;
}
````
result: 
RenderBundleEncoderDescriptor sizeOf: 48
NextInChain :0
Label :8
ColorFormatsCount :16
ColorFormats :24
DepthStencilFormat :32
SampleCount :36
DepthReadOnly :40
StencilReadOnly :44

RenderBundleEncoderDescriptorBool8 sizeOf: 48
NextInChain :0
Label :8
ColorFormatsCount :16
ColorFormats :24
DepthStencilFormat :32
SampleCount :36
DepthReadOnly :40
StencilReadOnly :41

**Comment by Beyley** [comment]
Is this still a problem on the latest master builds? Use the experimental nuget feed to get the latest release

This is likely coming about due to the use of stdbool in webgpu.h

**Comment by EmilSV** [comment]
I have tried the experimental nuget feed now it did not fix the problem. I don't know how silks binding generation tools works but the "generator.json" file has  "$include.dxTypeMap": "build/dx_typemap.json" inside the webgpu typeMaps.

**Comment by Beyley** [comment]
looks like movement is happening to remove the `stdbool.h` dependency, see https://github.com/webgpu-native/webgpu-headers/issues/84
asked for an ETA, pending response
if the upstream fix is going to be soon-ish, then we'll block 2.18 until its out

**Comment by Beyley** [comment]
merged upstream, we just need to wait for wgpu-native to update now

**Comment by Perksey** [comment]
@Beyley are we go for 2.18 here? upstream has been closed.

**Comment by Beyley** [comment]
> @Beyley are we go for 2.18 here? upstream has been closed.

wgpu-native has had no movement for updating, so our options for WebGPU right now are:
a) stay on the current 2.17.1 known-broken version of WebGPU (anything that uses bools is marshalled wrong)
b) update wgpu-native ourselves (i tried but im really bad at rust so couldnt get too far)
c) leave our wgpu-native binary packages as known-broken and add Dawn binary packages 
d) fix the bool marshalling problem, and stay on old WebGPU until wgpu-native updates
