### ISSUE TITLE
Build fails due to git invocation fail

### ISSUE THREAD

**Issue by derigel23** [dotnet/Silk.NET#1594]
# Summary
Build fails due to git invocation fail

# Steps to reproduce
- Platform: Desktop, WIndows 11
- Framework Version: .NET Core 7
- Download release Silk.NET-2.17.1
1. Run `build.cmd`
2. Get error 
`...\Silk.NET-2.17.1\build\props\common.props(36,9): error MSB3073: The command "git show -s "--format=%%cI"" exited with code 128.`

** I think it's related to the `format` parameter passed to git command **

**Comment by derigel23** [comment]
Or, it's rather just due to the absence of .git folder at all because sources were downloaded as a release archive.

**Comment by Perksey** [comment]
You probably need to `git submodule update --init --recursive`

**Comment by derigel23** [comment]
@Perksey As I've said, I've got sources from release archive. Is it buildable alone by itself without any dependencies?

**Comment by Perksey** [comment]
Not currently, I've just opened #1596 to rectify this.
