### ISSUE TITLE
Generate classes and structs with partial keyword

### ISSUE THREAD

**Issue by Klotzi111** [dotnet/Silk.NET#1619]
# Summary of feature
Make the classes and structs in the generated source code `partial`.
So that a user of this library can extend these classes and structs.

# Comments
Other source generators like `Grpc.Tools` (via `protoc`) also generates its message classes with `partial`.

## Example
Consider this struct:
```C#
namespace Silk.NET.Vulkan
{
	public struct ExtensionProperties
	{
		public unsafe fixed byte ExtensionName[256];
		public uint SpecVersion;
		//...
	}
}
```
Since the `ExtensionName` field is of `fixed byte` type (which by itself is good to match the native struct layout) it is sometimes hard to work with.
Often one needs a string. This can be done like so: `SilkMarshal.PtrToString((nint)extensionProperties.ExtensionName, NativeStringEncoding.UTF8)`.
It would be nice to just do: `extensionProperties.GetExtensionName()`.
This could be achived with an extension function.
But the story goes on.

Now also think of this struct:
```C#
namespace Silk.NET.Vulkan
{
	public struct LayerProperties
	{
		public unsafe fixed byte LayerName[256];
		public uint SpecVersion;
		public uint ImplementationVersion;
		public unsafe fixed byte Description[256];
		//..
	}
}
```
They have some things in common.
They both have:
- a name
- a `SpecVersion`

Now one might want to write a function that can take either a `ExtensionProperties` or a `LayerProperties` and print the `SpecVersion` (and name). But for this to work they both need to implement the same interface so that interface can be used as type contraint for the generic type parameter of the function.

If the structs would be `partial` the interface could be added even if the generator does not add it.
Then the following code would work:
```C#
public interface ISpecVersioned
{
	public uint SpecVersion { get; }
}

namespace Silk.NET.Vulkan
{
	public partial struct ExtensionProperties : ISpecVersioned
	{
		readonly uint ISpecVersioned.SpecVersion => SpecVersion;
	}
	public partial struct LayerProperties : ISpecVersioned
	{
		readonly uint ISpecVersioned.SpecVersion => SpecVersion;
	}
}

public static void PrintProperties<T>(in T properties)
	where T : ISpecVersioned
{
	Console.WriteLine($"{typeof(T).Name}'s SpecVersion = {properties.SpecVersion}");
}
```

# Does this have a proposal?
No (none required i think)

**Comment by skyebird189** [comment]
You could always use extension methods? This is how silk typically adds functionality to these types of structs at the moment. (which is used heavily in the directx bindings)
Personally I think this idea is relatively unnecessary since extension methods do pretty much exactly this.

**Comment by skyebird189** [comment]
A slightly bigger issue that I've just remembered though: partial structs/classes can only be partial within their own assembly.
This in turn makes extending them in user assemblies impossible.

**Comment by Beyley** [comment]
> A slightly bigger issue that I've just remembered though: partial structs/classes can only be partial within their own assembly.
> This in turn makes extending them in user assemblies impossible.

yes, partial types are a *language feature*, so im not sure what making types partial would do here, given we publish to nuget

**Comment by Klotzi111** [comment]
> A slightly bigger issue that I've just remembered though: partial structs/classes can only be partial within their own assembly. This in turn makes extending them in user assemblies impossible.

Oh. If that is the case then this issue is done.

> You could always use extension methods? This is how silk typically adds functionality to these types of structs at the moment. (which is used heavily in the directx bindings)
Personally I think this idea is relatively unnecessary since extension methods do pretty much exactly this.

Can you please tell my how I would do this generic function with extension functions?

**Comment by skyebird189** [comment]
Something like

```cs
public static class VulkanExtensions {
    public static string GetExtensionName(this LayerProperties props) {
        // stuff here
    }
}
```

**Comment by Klotzi111** [comment]
Yea I know. I already mentioned that.
I meant the `PrintProperties<T>(in T properties)` function

**Comment by Beyley** [comment]
closing due to being covered already by extension methods + partial structs not existing after compilation and publishing to nuget

**Comment by Klotzi111** [comment]
> being covered already by extension methods

This is not true. There is no way to implement the `PrintProperties<T>(in T properties)` function I mentioned. That is the reason for this issue.
But because it is impossible closing is our only choice.

**Comment by Beyley** [comment]
> > being covered already by extension methods
> 
> This is not true. There is no way to implement the `PrintProperties<T>(in T properties)` function I mentioned. That is the reason for this issue.
> But because it is impossible closing is our only choice.

you can implement that function for multiple types separately, or use reflection

**Comment by Klotzi111** [comment]
Yea. Implementing that function for multiple types separately can be a lot of repetetive work. But reflection is no better because it is very slow.
I guess a SourceGenerator could help implementing all the function overloads.

**Comment by Beyley** [comment]
> Yea. Implementing that function for multiple types separately can be a lot of repetetive work. But reflection is no better because it is very slow.
> I guess a SourceGenerator could help implementing all the function overloads.

console io will be 2x slower than reflection

**Comment by Klotzi111** [comment]
> console io will be 2x slower than reflection

true. This was just a example to demonstrate the problem. I am of course not using this exact function.
