### ISSUE TITLE
TryGetExtension fails for OpenAL EffectExtension

### ISSUE THREAD

**Issue by okaniku** [dotnet/Silk.NET#1691]
# Summary
Using TryGetExtension to obtain an instance of OpenAL EffectExtension returns false.

# Steps to reproduce
- Platform: Windows 11 Desktop
- Framework Version: .NET 6.0
- API: OpenAL
- API Version: 1.1 ALSOFT 1.23.1

When I try to obtain an instance of EffectExtension using TryGetExtension, the call returns false indicating that the extension is not present.

```
AL al = AL.GetApi(true);
EffectExtension efx;
if (!al.TryGetExtension(out efx))
    throw new Exception();
```

I played around with the OpenAL Soft library and it likewise returns false when I call: `alIsExtensionPresent("ALC_EXT_EFX")`

What is the intended way to get an instance of EffectExtension? I can simply go `efx = new EffectExtension(al.Context);` but that seems inconsistent. Obtaining the effect extension context API works as expected:
```
ALContext alc = ALContext.GetApi(true);
EffectExtensionContext efxContext;
if (!alc.TryGetExtension(null, out efxContext))
    throw new Exception();
```

**Comment by Perksey** [comment]
Yeah so OpenAL is extremely inconsistent here, using an ALC extension name for an AL extension... I'll add a hack in for this.

**Comment by Perksey** [comment]
Forgot I fixed this in 2.18, closing :)

**Comment by okaniku** [comment]
Thanks for looking into this. `TryGetExtension` is still returning false for me even after the fix. I had a look at the hack that was added - I believe the `alcIsExtensionPresent` function call is missing a `Device*` parameter? https://github.com/dotnet/Silk.NET/blob/521e18a36ca4d91393814a1b4ae6a9494a91fd9b/src/OpenAL/Silk.NET.OpenAL/AL/AL.cs#L39
I tried this and it started returning 'true' for me:

```
return ((delegate* unmanaged[Cdecl]<Device*, byte*, char>) Context.GetProcAddress("alcIsExtensionPresent"))
                        (null, namePtr) == 1;
```

**Comment by okaniku** [comment]
It seems to me that a proper fix would need to pass in the device for the current ALC context, like in ALContext, instead of `null` like I have above, which would just use the default context:
https://github.com/dotnet/Silk.NET/blob/521e18a36ca4d91393814a1b4ae6a9494a91fd9b/src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs#L31C10-L31C10

But that would make things a bit awkward..

**Comment by Perksey** [comment]
Sorry for the delay, seen this, thanks for letting us know. If you know how to fix this please open a PR, otherwise I'll maybe try and remember at some point.

**Comment by Perksey** [comment]
And I'm happy for this to be as hacky as possible to be correct (it's an ugly situation brought on by OpenAL themselves), so I'm happy for there to be another function pointer call to alcGetCurrentContext to make this work.

**Comment by okaniku** [comment]
Confirmed working.
