### ISSUE TITLE
Embed OpenAL Library Files for Mac/Linux

### ISSUE THREAD

**Issue by Kuumba123** [dotnet/Silk.NET#1697]
# Summary of feature
Simply embeds the library files into the EXE file  for Mac/Linux just like it does for Windows so that no one has to manually mess with projects settings and grab the  library files .

# Comments
Ill admit Im being a bit lazy but I bet Im not the only who thinks having a million dll's for a final  release is a mess.
# Does this have a proposal?
Include the library files for Linux/Mac single file publish just like it is for Windows.

**Comment by Perksey** [comment]
Set the IncludeNativeLibrariesForSelfExtract MSBuild property to true.

**Comment by Perksey** [comment]
*From @Kuumba123 on duplicate issue #1698*

This is re-issue of issue that was immedilatly closed (https://github.com/dotnet/Silk.NET/issues/1697 and yes I already had everything setup in project/publish settings otherwise my program wouldn't have worked regardless if I was using Silk.NET) next time please dont just immediatly close issues , I wouldn't have opened either of these issues unless I know there was a problem. I guess Ill try to explain a bit more depth what the issue is. So normally when I want write a .NET 6 cross platform app I go to publish and then select the platform I want to publish for (mac , linux etc). Depending on witch platform I select the libraries (that generally get via nugget) I include in my C# project the libraries simply include different library files (dll,so files etc) based on the platform I am publishing for. However for some reason with Silk.NET (more specficly openAL) it doesnt include the propery library files if I publish for anything other than windows so if I try to run the program Ill get an error as soon as it tries to run any code that uses Silk.NET. Now I could just go in the source code and grab the correct library files (libopenal.so and libopenal.dylib in my case) and just copy them to the same directory as the Linux and Mac EXE witch fixes the problems. I could also just force users to just install openAL but I dont like doing that (especally for linux cause of all the distros). But preferable this should all be taken care of by the libraries and not by me copying library files and messing with my the files included in my project. Anyways hopefully you folks understand what Im talking about.

**Comment by Perksey** [comment]
Can you send me your csproj please

**Comment by Kuumba123** [comment]
thanks for reopening :) , right here is C# project file: 
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release;Linux;Mac-x64;Mac-ARM64</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Linux|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Mac-x64|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Mac-ARM64|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="UI\ImGuiShadders\GLSL\imgui-frag.glsl" />
    <None Remove="UI\ImGuiShadders\GLSL\imgui-vertex.glsl" />
    <None Remove="UI\ImGuiShadders\HLSL\imgui-frag.hlsl.bytes" />
    <None Remove="UI\ImGuiShadders\HLSL\imgui-vertex.hlsl.bytes" />
    <None Remove="UI\ImGuiShadders\Metal\imgui-frag.metallib" />
    <None Remove="UI\ImGuiShadders\Metal\imgui-vertex.metallib" />
    <None Remove="UI\ImGuiShadders\SPIR-V\imgui-frag.spv" />
    <None Remove="UI\ImGuiShadders\SPIR-V\imgui-vertex.spv" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI\ImGuiShadders\GLSL\imgui-frag.glsl" />
    <EmbeddedResource Include="UI\ImGuiShadders\GLSL\imgui-vertex.glsl" />
    <EmbeddedResource Include="UI\ImGuiShadders\HLSL\imgui-frag.hlsl.bytes" />
    <EmbeddedResource Include="UI\ImGuiShadders\HLSL\imgui-vertex.hlsl.bytes" />
    <EmbeddedResource Include="UI\ImGuiShadders\Metal\imgui-frag.metallib" />
    <EmbeddedResource Include="UI\ImGuiShadders\Metal\imgui-vertex.metallib" />
    <EmbeddedResource Include="UI\ImGuiShadders\SPIR-V\imgui-frag.spv" />
    <EmbeddedResource Include="UI\ImGuiShadders\SPIR-V\imgui-vertex.spv" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.89.9.2" />
    <PackageReference Include="Silk.NET.OpenAL" Version="2.17.1" />
    <PackageReference Include="Veldrid" Version="4.9.0" />
    <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Misc\" />
  </ItemGroup>

</Project>
```
Ill also include the publish profile for linux (windows publish file xml is pretty much the exact same) since that might help solve this issue:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Linux</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\publish\PogTro-linux-x64</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net7.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```

**Comment by Perksey** [comment]
The IncludeNativeLibrariesForSelfExtract property is not present anywhere in those files, please include it in your csproj or publish profile.

**Comment by Kuumba123** [comment]
my appologizes that was my main project I plan on using Silk.NET.OpenAL with , I should have posted the test project I made. Heres the test project: 
```
<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Silk.NET.OpenAL" Version="2.17.1" />
	</ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>

```
heres the linux publish file: 
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net6.0\publish\linux</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
</Project>
```

**Comment by Perksey** [comment]
You haven’t installed the OpenAL Soft package. Silk.NET will not automatically include binaries unless you ask it to and change your code to use OpenAL soft.

**Comment by Perksey** [comment]
It’s worth noting that macOS should work OOTB as we use the system implementation if we can find it, but knowing Apple they’ve probably deprecated it…

**Comment by Kuumba123** [comment]
I havne't had a chance to test on Mac since I would neeed my uncle's Laptop for that (still dont have my own Mac) . However give that I am having these problems with Linux I would assume it would have similar problems on Mac as well.

**Comment by Perksey** [comment]
Apple ships an OpenAL implementation and while it is deprecated, it is still functional in modern versions of the OS. This is purely a Linux issue. Before you report that something is broken on a particular platform, please make sure it actually is.

Please install OpenAL using your Linux distribution's package manager, or if you don't want to require that use OpenAL Soft. This will involve installing the Silk.NET.OpenAL.Soft.Native package and setting your GetApi calls to `true` for the `soft` parameter.
