### ISSUE TITLE
Codegen for `IPropertyBag2` and its friends

### ISSUE THREAD

**Issue by hez2010** [dotnet/Silk.NET#1735]
This is a follow-up to #1674.

It seems that we still need to introduce the support for `IPropertyBag2`, `tagPROPVARIANT` and `tagPROPBAG2`, otherwise it can be hard to use. For example, https://learn.microsoft.com/en-us/windows/win32/wic/-wic-creating-encoder#tiff-encoding-example

Those types are located in oaidl.h and ocidl.h.

Is there any way to only include the types we actually need without introducing the whole bunch of unnecessary dependencies?

_Originally posted by @hez2010 in https://github.com/dotnet/Silk.NET/issues/1674#issuecomment-1741700823_

**Comment by Perksey** [comment]
You could add these headers and exclude everything but these types, but really we need support for that in the generator.

Happy for whatever is practicable here.
