### ISSUE TITLE
Unhandled exception. Silk.NET.Core.Loader.SymbolLoadingException: Native symbol not found (Symbol: vkCreateDebugUtilsMessengerEXT) 

### ISSUE THREAD

**Issue by CyberT3C** [dotnet/Silk.NET#1764]
# Summary
Hello,

I am trying to setup vulkan in F# with Silk.Net. So far everything works as expect but somehow I am not able to setup a debug messenger. Here is my code line which fails:

` debugUtils.CreateDebugUtilsMessenger(state.instance, &createInfo, NativeInterop.NativePtr.nullPtr, &state.debugMessenger)`

I think that somehow Sill.net isnt using the Vulkan Version which I expect. Maybe you have a idea on how to fix it and which vulkan sdk should work. 

# Steps to reproduce
- Platform: Windows/Desktop
- Framework Version: .NET 7,
- API: Vulkan
- API Version: Vulkan 1.3

<html><body>

Executable Info
--
Exe Directory | C:/VulkanSDK/1.3.250.1/Bin
Current Directory | C:/Users/...
App Version | Version 1.3
Vulkan API Version | 1.3.250
Byte Format | 64-bit

</body>
</html>

<html><body>

Vulkan Runtimes
--
Runtimes In Registry | SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall |  
  | [0] | 1.0.65.1  [Install Count = 1]
Runtimes in System Folder | C:/WINDOWS/system32/ |  
DLL 0 | vulkan-1-1-0-65-1.dll | Version 1.0.65.1.
DLL 1 | vulkan-1-999-0-0-0.dll | Version 1.3.241.0.
DLL 2 | vulkan-1.dll | Version 1.3.241.0.
Runtime Used by App | C:/Windows/System32/vulkan-1.dll | 1.3.241.0.

</body>
</html>

Full Error output:

`Starting demo application.
loading window... 
Yes, we have validation Layer support!!!
Unhandled exception. Silk.NET.Core.Loader.SymbolLoadingException: Native symbol not found (Symbol: vkCreateDebugUtilsMessengerEXT)
   at Silk.NET.Core.Contexts.LamdaNativeContext.<GetProcAddress>g__Throw|4_0(String proc)
   at Silk.NET.Core.Contexts.LamdaNativeContext.GetProcAddress(String proc, Nullable`1 slot)
   at Silk.NET.Vulkan.Extensions.EXT.ExtDebugUtils._B.get__KJM()
   at Silk.NET.Vulkan.Extensions.EXT.ExtDebugUtils.CreateDebugUtilsMessenger(Instance instance, DebugUtilsMessengerCreateInfoEXT& pCreateInfo, AllocationCallbacks* pAllocator, DebugUtilsMessengerEXT& pMessenger)
   at VulkanStuff.VulkanModule.setupDebugMessenger(VulkanState state) in C:\...\VulkanSetup-IntoFunctional\refactored.fs:line 265  

The vulkan instance created without a problem. I can also pick a phyiscal device and create the logical device without a problem.

Vulkan setup as:

EDIT:
Theseare my used packages. 
"Silk.NET.Core" Version="2.18.0"   
"Silk.NET.GLFW" Version="2.18.0"   
"Silk.NET.Input" Version="2.18.0"   
"Silk.NET.Input.Glfw" Version="2.18.0"   
"Silk.NET.Maths" Version="2.18.0" 
"Silk.NET.Vulkan" Version="2.18.0" 
"Silk.NET.Vulkan.Extensions.EXT" Version="2.18.0" 
"Silk.NET.Vulkan.Extensions.KHR" Version="2.18.0" 
"Silk.NET.Windowing" Version="2.18.0" 
"Silk.NET.Windowing.Glfw" Version="2.18.0" 

# vulkaninfoSDK Outut

Vulkan Instance Version: 1.3.241

Instance Extensions: count = 15
===============================
        VK_EXT_debug_report                    : extension revision 10
        VK_EXT_debug_utils                     : extension revision 2
        VK_EXT_swapchain_colorspace            : extension revision 4
        VK_KHR_device_group_creation           : extension revision 1
        VK_KHR_external_fence_capabilities     : extension revision 1
        VK_KHR_external_memory_capabilities    : extension revision 1
        VK_KHR_external_semaphore_capabilities : extension revision 1
        VK_KHR_get_physical_device_properties2 : extension revision 2
        VK_KHR_get_surface_capabilities2       : extension revision 1
        VK_KHR_portability_enumeration         : extension revision 1
        VK_KHR_surface                         : extension revision 25
        VK_KHR_surface_protected_capabilities  : extension revision 1
        VK_KHR_win32_surface                   : extension revision 6
        VK_LUNARG_direct_driver_loading        : extension revision 1
        VK_NV_external_memory_capabilities     : extension revision 1

Layers: count = 15

PS:
I just rebuild the c++ version from [vulkan-tutorial c++](https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers)
```

        let setupDebugMessenger (state: VulkanState): InitResult<VulkanState> = // (debugMessenger: DebugUtilsMessengerEXT byref) 
            match state.enableValidationLayers with
            | true ->

                let mutable createInfo = createPopulateDebugMessengerCreateInfo

                let mutable debugUtils: ExtDebugUtils = Unchecked.defaultof<ExtDebugUtils>
                let mutable debugMessenger: DebugUtilsMessengerEXT = Unchecked.defaultof<DebugUtilsMessengerEXT>

                match (optionValueVkFromVulkanState state).TryGetInstanceExtension(state.instance, &debugUtils) with
                    | true ->   match debugUtils.CreateDebugUtilsMessenger(state.instance, &createInfo, NativeInterop.NativePtr.nullPtr, &state.debugMessenger) with
                                | Result.Success ->  Success { state with debugMessenger = debugMessenger }
                                | _ ->  Failure "Failed to set up debug messenger - couldn't create CreateDebugUtilsMessenger!"
                    | false -> Failure "Failed to set up debug messenger - couldnt get debugUtils extension!"
                    
            | false -> Success state // nothing to do
```

**Comment by Perksey** [comment]
Have you enabled the extension when creating your instance?

Also, manually using validation layers is not recommended anymore, the new industry-preferred way of using validation layers is the vkconfig tool that comes with the Vulkan SDK - this allows you to inject layers without changing code.

**Comment by CyberT3C** [comment]
Working with the vkconfig works just like a charm and i will ditch my codebase for setting this up on my own. 
Thank you for your quick response!

For future ppl who will run into a similiar error: I think my codebase where i setup the debug utils ist just wrong at some point. I think a pointer was just not in the right spot or had the right type.
