### ISSUE TITLE
Prefer Wayland over X11 if Available

### ISSUE THREAD

**Issue by bbb651** [dotnet/Silk.NET#1773]
Currently, it seems like with linux on wayland, Silk.NET will still prefer using x11 with xwayland. I'm not too familiar with the library so I'm not sure which backend is being used, I think it's GLFW, and [this code seems to try x11 before wayland first?](https://github.com/dotnet/Silk.NET/blob/da7cae57614f91d0387fa51af8a52c99b7c43d98/src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs#L54) I think it'll really improve the experience for linux users, for example SDL already switched to wayland by default a while ago.

**Comment by Beyley** [comment]
> Currently, it seems like with linux on wayland, Silk.NET will still prefer using x11 with xwayland. I'm not too familiar with the library so I'm not sure which backend is being used, I think it's GLFW, and [this code seems to try x11 before wayland first?](https://github.com/dotnet/Silk.NET/blob/da7cae57614f91d0387fa51af8a52c99b7c43d98/src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs#L54) I think it'll really improve the experience for linux users, for example SDL already switched to wayland by default a while ago.

This should be discussed upstream at GLFW, we dont decide what backend gets used by default, the linked code is only called after the window is created

**Comment by bbb651** [comment]
I looked into it and GLFW has a wayland backend and support for choosing a backend at runtime but [it's currently not the default as it's less complete.] There is a way to hint to GLFW to prefer wayland, this shouldn't be enabled by default as it'll be unexpected for users, are you interested in exposing it somehow to the api/environment variable? If not I'll patch the library downstream, thanks for your help!

**Comment by Beyley** [comment]
id prefer this be handled upstream, given the still prevalent issues with GLFW on Wayland (ive had a enough of them where i use the x11 version through xwayland exclusively for my own projects), i would not really want to expose a simple way on our end to force the GLFW backend, since that should be handled upstream, GLFW is also an implementation detail of our windowing, as it may choose use to use SDL in some scenarios

**Comment by Perksey** [comment]
We have discussed exposing backend specific hints in the past, even making it as far as a proposal [here](https://github.com/dotnet/Silk.NET/blob/main/documentation/proposals/(Rejected)%20Proposal%20-%20Platform%20Hints.md), but it was rejected by the working group on the following counts:
- We should properly expose functionality that should be common by designing a proper API around it. Given that the abstraction itself does not know about the backend itself having multiple backends, we haven’t pursued this in this case.
- We should empower the user to obtain the native handle so they can do this themselves. This led to a chain of further work like the [native contexts proposal](https://github.com/dotnet/Silk.NET/blob/main/documentation/proposals/Proposal%20-%20Contexts.md) to make it easier to evade our APIs to handle it yourself, and native handles being exposed in #411.

A workaround could be using `GlfwProvider.GLFW.Value.WindowHint` but this limits your code’s portability - you’d need to somehow make sure that the backend is GLFW ahead of time which I believe can be done using the APIs we expose on `Window`, but it’s far easier not to care and our position is that we delegate decisions here to our upstream libraries like GLFW.
