### ISSUE TITLE
AL.TryGetExtension fails for most extensions

### ISSUE THREAD

**Issue by okaniku** [dotnet/Silk.NET#1805]
# Summary
AL.TryGetExtension doesn't seem to be working for me for anything other than the EFX extension that we hacked around recently: https://github.com/dotnet/Silk.NET/pull/1770 I don't think it's ever worked for me, and the EFX extension is actually the only AL extension that I've tried before this, which led to me reporting the issue with it.

# Comments
Every AL extension I've tried results in TryGetExtension returning false, for example:

```
al = AL.GetApi(true);
SoftGainClamp sgc;
if (!al.TryGetExtension(out sgc))
    throw new Exception("!!!");
```

I've also tried calling IsExtensionPresent, which also returns false for everything I throw at it, e.g. 
```
al.IsExtensionPresent("AL_SOFT_deferred_updates");
```

And I've also tried calling the function in a hacky way, but it also returns false, e.g.
```
string name = "AL_SOFT_deferred_updates";
var maxName = SilkMarshal.GetMaxSizeOf(name, NativeStringEncoding.UTF8);
var nameNative = name.Length > 256 ? new byte[maxName] : stackalloc byte[maxName];
SilkMarshal.StringIntoSpan(name, nameNative, NativeStringEncoding.UTF8);
fixed (byte* namePtr = nameNative)
{
    return ((delegate* unmanaged[Cdecl]<byte*, char>)al.Context.GetProcAddress("alIsExtensionPresent"))(namePtr) == 1;
}
```

ALContext.TryGetExtension works fine for every ALC extension I've passed in.

I don't think it's an issue with my `soft_oal.dll`, because I confirmed that `alIsExtensionPresent` returns true for all the above extensions as expected.

Any ideas why this might be happening?

**Comment by Perksey** [comment]
Are you sure your context is current? Looking at the C++ implementation, alIsExtensionPresent is just a wrapper over alcIsExtensionPresent for the current context...

**Comment by okaniku** [comment]
You're totally right, I misunderstood the API.. I changed my code to make sure a context was set as current before checking for the AL extensions and it worked. Sorry for the false alarm, and thanks so much!
