### ISSUE TITLE
UTF-8 path not supported on Windows

### ISSUE THREAD

**Issue by WinstonMao** [dotnet/Silk.NET#1809]
# Summary
Hello,
When I dragged a file with the UTF-8 characters into the SDL window, it returned a wrong path.
It seems to only return the wrong path under Windows, and it works fine under Mac OS.
# Steps to reproduce
- Platform: Windows 10 Enterprise LTSC 1809
- Framework Version: .NET6
- API: Silk.NET.Windowing
- API Version: 2.18
1. Drop the File named with UTF-8 characters to the SDL window. It returns a wrong path.
2. Inspired by SDL2-CS, I modified the source code of "SdlWindow.cs" and got the following result:
![utf-8-path-error](https://github.com/dotnet/Silk.NET/assets/8135506/730ad2aa-f77b-49e3-bbeb-14e6991013fd)

3. And here is the file named with UTF-8 characters：
[测试.txt](https://github.com/dotnet/Silk.NET/files/13423712/default.txt)

**Comment by Perksey** [comment]
Good spot, we’d welcome PRs here.

**Comment by Perksey** [comment]
Closed by #1810 :tada:
