### ISSUE TITLE
OpenAL ReopenDevices extension doesn't work

### ISSUE THREAD

**Issue by okaniku** [dotnet/Silk.NET#1823]
# Summary
The OpenAL ReopenDevices extension doesn't seem to work.

# Steps to reproduce
After setting a current context, and calling
`reopenDevices.ReopenDevice(device, deviceName, attrList);`
I get 'Native symbol not found (Symbol: alcReopenDeviceSOFT)'

# Comments
I'm wondering whether it's because this is an ALC prefixed extension, and the extension class derives from `NativeExtension<AL>` rather than `ContextExtensionBase`.

Ref: https://github.com/dotnet/Silk.NET/blob/main/src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/ReopenDevices.cs

Interestingly, getting the extension in the first place works fine from the AL API:
```
al = AL.GetApi(true);
al.TryGetExtension(out ReopenDevices reopenDevices);
```

Is this a bug or something I'm doing wrong?

**Comment by okaniku** [comment]
Unfortunately this is still happening, even after changing it to a context extension.

Strangely, I'm able to successfully call the underlying function by doing this:

```
using var alc = ALContext.GetApi(true);
var deviceName = string.Empty;
var dev = alc.OpenDevice(deviceName);
var ctx = alc.CreateContext(dev, null);
alc.MakeContextCurrent(ctx);

if (dev != null && alc.TryGetExtension(dev, out ReopenDevices ext))
{
    var maxName = SilkMarshal.GetMaxSizeOf(deviceName, NativeStringEncoding.UTF8);
    var nameNative = deviceName.Length > 256 ? new byte[maxName] : stackalloc byte[maxName];
    fixed (byte* namePtr = nameNative)
    {
        ((delegate* unmanaged[Cdecl]<Device*, byte*, int*, bool>) alc.GetProcAddress(dev, "alcReopenDeviceSOFT"))(dev, namePtr, null);
    }
}
```

**Comment by Perksey** [comment]
@okaniku Can you compare the results of `alc.Context.GetProcAddress("alcReopenDeviceSOFT")` vs `alc.GetProcAddress("alcReopenDeviceSOFT")`

Relevant code:

https://github.com/dotnet/Silk.NET/blob/main/src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs#L98

**Comment by okaniku** [comment]
Calling `alc.Context.GetProcAddress()` throws the same error. `NativeLibrary3.TryGetExport()` returns false, stack trace:

```
Silk.NET.Core.Loader.LibraryLoader.NetNextNativeLibraryLoader.CoreLoadFunctionPointer(nint handle, string functionName)
Silk.NET.Core.Loader.LibraryLoader.LoadFunctionPointer(nint handle, string functionName)
Silk.NET.Core.Loader.UnmanagedLibrary.LoadFunction(string name)
Silk.NET.Core.Contexts.DefaultNativeContext.GetProcAddress(string proc, int? slot)
Silk.NET.Core.Contexts.MultiNativeContext.GetProcAddress(string proc, int? slot)
```
