### ISSUE TITLE
TryGetDeviceExtension succeeds when Device is invalid

### ISSUE THREAD

**Issue by ripwin** [dotnet/Silk.NET#1825]
# Summary
Hi,

I'm using TryGetDeviceExtension to load VK_KHR_swapchain extension. But it returns true when the device is not valid.

```c#
        if (!vk.TryGetDeviceExtension<KhrSwapchain>(instance, new Device(), out var khrSwapchain))
        {
            throw new Exception("Unable to load KHR swapchain  extension");
        }
``` 

In this example, the function returns true even though the Device is invalid. It creates a KhrSwapchain object that is not valid.

And I have an exception after when I use it :

![image](https://github.com/dotnet/Silk.NET/assets/10164365/65cbf680-2186-464d-a597-69fc2049ebeb)

![image](https://github.com/dotnet/Silk.NET/assets/10164365/fed33c2b-8443-4e17-9767-9c68f439c667)

# Steps to reproduce
- Platform: Desktop (Window 10)
- Framework Version: .NET 8
- API: Vulkan
- API Version: Vulkan 1.1

# Comments
I'm uncertain whether it can be mitigated. Upon reviewing the underlying code, I find it strange why Activator.CreateInstance doesn't throw an exception. Additionally, I'm unsure if we could simply check for the default handle and return null and false instead.

I also tried with a default Instance. The program just stops 🤣

**Comment by Perksey** [comment]
Can’t be mitigated, we have no way of knowing what extensions you’ve actually enabled for a given device vs what extensions we know are present on any physical device (which is what we actually check).

**Comment by ripwin** [comment]
I understand the remarks on the method. Thank you. Sorry for the inconvenience.
