### ISSUE TITLE
Incorrect locals assignment in Matrix2X2<T>.GetDeterminant() implementation

### ISSUE THREAD

**Issue by BladeWise** [dotnet/Silk.NET#1826]
# Summary
The `Matrix2X2<T>.GetDeterminant()` [implementation](https://github.com/dotnet/Silk.NET/blob/bc7d8a0741f716f7a1e6c0c046df54db61986598/src/Maths/Silk.NET.Maths/Matrix2X2.cs#L265) computes `(M11*M21)-(M12*M22)` instead of `(M11*M22)-(M12*M21)`, due to an inverted assignment of locals `c` and `d`.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 8
- API: not relevant
- API Version: not relevant
1. Create a new .NET 8 console project and add Silk.NET.Maths package reference
2. Paste the following code
```cs
using System;
using Silk.NET.Maths;

//     | m11 m12 |
// m = |         |
//     | m21 m22 |
// det(m) = m11*m22 - m21*m22
var m = new Matrix2X2<float>(2, 3, 4, 5);
Console.WriteLine($"Determinant (expected): {m.M11 * m.M22 - m.M21 * m.M12}");
Console.WriteLine($"Determinant (actual)  : {m.GetDeterminant()}");
```
3. Check the result
```shell
Determinant (expected): -2
Determinant (actual)  : -7
```

# Comments
I can provide a PR if needed.

**Comment by Perksey** [comment]
Good spot, PRs welcome!

**Comment by Perksey** [comment]
Also @HurricanKai for second opinion on the maths (this means nothing to me)
