### ISSUE TITLE
High CPU Usage when checking Joysticks and Gamepads

### ISSUE THREAD

**Issue by Vercidium** [dotnet/Silk.NET#1861]
# Summary
I've set up a bare-bones project using Silk.NET that uses OpenGL to render a texture to the screen.

I then ran a profiler and found it's checking for `JoystickPresent` and `GetGamepadState` every single frame.

I don't use a Joystick or Gamepad, can I disable these checks?

![image](https://github.com/dotnet/Silk.NET/assets/12014138/5ddf93fe-0fca-4125-80e8-a3ac66ea8ad0)

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 7
- API: OpenGL
- API Version: OpenGL 3.3

- Create a window
- Call `window.Run()`

**Comment by Perksey** [comment]
I don't think we're going to do anything here. 2% time being spent updating the input context is negligible, and is lesser half of the work done in `ProcessEvents` (i.e. polling the event pump in the system's window manager takes longer than us to respond to those changes). If there are instances of this taking a significant portion of a capped frame window (e.g. a large % of a 16ms/60FPS frame window) then we should investigate that, but until then I'm going to write this off as a negligible detail exposed by unrepresentative microbenchmarking.
