### ISSUE TITLE
Move Shader class et. al from the Silk.NET.OpenGL namespace

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1864]
# Summary of feature
Move the Shader class to another namespace. Perhaps Texture and other classes as well.

# Comments
In practice, users will have conflicts when `using Silk.NET.OpenGL;` in which if they have a local class named Shader they will have to fully qualify the local class Shader's namespace to use their local class. So this demands users to use a name such as GLShader. I think Texture is also a problem here.

# Does this have a proposal?
No

**Comment by Perksey** [comment]
We can’t do this as it will be a breaking change. However, this is not without precedent given that all of our other bindings do this, OpenGL is just unique in that the strong types aren’t an inherent part of the specification. Other than that, we don’t see reason to single out OpenGL here and if we do want to make changes here I’d want to see justification and execution across the whole library.

It’s worth noting that namespaces were invented to alleviate these sorts of problems, and this is the reason that you can use a namespace when referring to one of these types.
