### ISSUE TITLE
IMouse.MouseMove Vector2 vector parameter is useless

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1871]
# Summary
Equals(mouse.Position, vector) == true

Let's say you want to handle input i.e. click detection (release doesn't fire when not moused over component), mouse down, mouse up between multiple components. If you want to have a function which handles all components uniformly then you will fall back to the IMouse parameter as shown in the code below.
```cs
	private static Component? lastComponentMouseDown = null;
	
	private static (int, int, Component?) HitTestForComponent(IMouse mouse)
	{
		int mouseX = (int) mouse.Position.X;
		int mouseY = window.Size.Y - (int) mouse.Position.Y;
		return (mouseX, mouseY, Container.GetTopMostComponentFor(EditorWindow.Instance.Root.DoHitTest(mouseX, mouseY)));
	}
	
	private static void OnMouseDown(IMouse mouse, MouseButton button)
	{
		(int mouseX, int mouseY, Component? topMostComponent) = HitTestForComponent(mouse);
		topMostComponent?.Rendered.OnMouseDown(mouseX, mouseY, (int) button, topMostComponent);
		lastComponentMouseDown = topMostComponent;
	}
	
	private static void OnMouseUp(IMouse mouse, MouseButton button)
	{
		(int mouseX, int mouseY, Component? topMostComponent) = HitTestForComponent(mouse);
		topMostComponent?.Rendered.OnMouseUp(mouseX, mouseY, (int) button, topMostComponent);
		if (ReferenceEquals(topMostComponent, lastComponentMouseDown))
			topMostComponent?.Rendered.OnClick(mouseX, mouseY, (int) button, topMostComponent);
		lastComponentMouseDown = null;
	}
	
	private static void OnMouseMove(IMouse mouse, Vector2 vector)
	{
		(int mouseX, int mouseY, Component? topMostComponent) = HitTestForComponent(mouse);
		topMostComponent?.Rendered.OnHover(mouseX, mouseY, topMostComponent);
	}
	
	private static void OnMouseScroll(IMouse mouse, ScrollWheel wheel)
	{
		(int mouseX, int mouseY, Component? topMostComponent) = HitTestForComponent(mouse);
		topMostComponent?.Rendered.OnScroll(mouseX, mouseY, (int) wheel.Y, topMostComponent);
	}
```

Having a vector readily available doesn't make much sense. A new vector will be created which at worst case could be 60-240hertz (or even worse at uncapped framerates) struct instances copied as a value type via the stack per bound callback (nCallbacks * 480 to nCallbacks * 1920 bytes). However, I find this vector to be very useful if its normalized to the current window dimensions. i.e. `new Vector2(mouse.Position.X / window.Width, mouse.Position.Y / window.Height);` I don't think any reason can really justify having this vector parameter around, and as a 'shortcut' is just lazy. Unless it differs in OSes other than Windows.

Breaking change? Yes. Most compatible would be to just delete the param. "Well we will have all the other events require accessing the IMouse.Position except this one MouseMove event".

**Comment by Beyley** [comment]
Breaking changes are no bueno for 2.x, sorry!

**Comment by tilkinsc** [comment]
Thats fine. I just wanted this for my own documentation later! Lol
