### ISSUE TITLE
Shaderc native libraries are broken on Linux

### ISSUE THREAD

**Issue by Helco** [dotnet/Silk.NET#1888]
# Summary
Trying to load the Shaderc native library is broken on Linux

# Steps to reproduce
- Platform: Linux x64/arm64
- Framework Version: .NET 8
- API: Shaderc
1. First I cloned https://github.com/Helco/temp-test-silk-shaderc-linux
2. Then I run `LD_DEBUG=libs dotnet run`

# Comments
In the test repository I have added an Action to confirm on foreign hardware, [the error message](https://github.com/Helco/temp-test-silk-shaderc-linux/actions/runs/7448656724/job/20263511850#step:4:627) when run with `LD_DEBUG=libs` is: 
```
      1873:	find library=libshaderc_shared.so [0]; searching
      1873:	 search cache=/etc/ld.so.cache
      1873:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      1873:	  trying file=/lib/x86_64-linux-gnu/libshaderc_shared.so
      1873:	  trying file=/usr/lib/x86_64-linux-gnu/libshaderc_shared.so
      1873:	  trying file=/lib/libshaderc_shared.so
      1873:	  trying file=/usr/lib/libshaderc_shared.so
      1873:	
      1873:	/home/runner/work/temp-test-silk-shaderc-linux/temp-test-silk-shaderc-linux/bin/Debug/net8.0/runtimes/linux-x64/native/libshaderc_shared.so: error: symbol lookup error: undefined symbol: __isoc23_strtol (fatal)
Unhandled exception. System.IO.FileNotFoundException: Could not load from any of the possible library names! Please make sure that the library is installed and in the right place!
   at Silk.NET.Shaderc.Shaderc.CreateDefaultContext(String[] n)
   at Silk.NET.Shaderc.Shaderc.GetApi()
   at Program.<Main>$(String[] args) in /home/runner/work/temp-test-silk-shaderc-linux/temp-test-silk-shaderc-linux/Program.cs:line 1
```

**Comment by Beyley** [comment]
runs fine on my machine, what distro are you on?

**Comment by Perksey** [comment]
`__isoc23_strtol` does shaderc really need C23? Is there any way we can avoid this? Perhaps it's a glibc issue?

**Comment by Beyley** [comment]
> `__isoc23_strtol` does shaderc really need C23? Is there any way we can avoid this? Perhaps it's a glibc issue?

I dont believe we need C23, i wonder if the compiler is defaulting to that. I do also link explicitly against glibc 2.16, so im guessing that whats happening here is that the old glibc doesnt support whatever c23 weirdness is being used (even though i'd assume that would be caught at link time [grr c moment])

**Comment by Beyley** [comment]
Attached is a version compiled with glibc 2.17, could you manually replace the shared object in the runtimes folder with this and try it on your machine?
[Archive.tar.gz](https://github.com/dotnet/Silk.NET/files/13867310/Archive.tar.gz)

**Comment by Helco** [comment]
[The same error message](https://github.com/Helco/temp-test-silk-shaderc-linux/actions/runs/7457863470/job/20290781557#step:6:627) occurs with the other so file.
The problems occurs both on the default Github Actions Image ([Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)) as well as this Microsoft DevContainer image (seems to be [Debian 8](https://github.com/devcontainers/images/blob/main/src/dotnet/README.md))

**Comment by Beyley** [comment]
This is a very odd error, i cant recreate it locally on my Arch Linux machine, so i think i'll have to spin up an ubuntu 22.04 VM and see if i can recreate it there. shaderc doesnt even use any C code (its all C++ 17), so its a weird error to happen.

**Comment by Helco** [comment]
Good catch from the discussions on the Veldrid discord, as the alternative so library was replaced by the build. The alternative so library works on the GHA runners.

**Comment by Beyley** [comment]
> Good catch from the discussions on the Veldrid discord, as the alternative so library was replaced by the build. The alternative so library works on the GHA runners.

Oh it does work? In that case i'll push out a fix and open a PR. Seems to be some weirdness with the Zig compiler's glibc support when targetting versions <2.17

I'll also go ahead and fix all the other build.zig based native library builds to target glibc 2.17
