### ISSUE TITLE
IDirect3D9Ex CreateDeviceEx Crash 

### ISSUE THREAD

**Issue by fallingrust** [dotnet/Silk.NET#1925]
# Summary
Created a console application (Release|x86),it works well if set optimize false.But if the optimize parameter set to true, the program will crash in CreatDeviceEx, and the console log:
Fatal error. 0xC0000005
Fatal error while logging another fatal error.
Fatal error while logging another fatal error.

# Steps to reproduce
- Platform: Windows
- Framework Version: net6.0-windows
- API: Direct3D9
- API Version: Silk.NET.Direct3D9 2.20.0

# Comments
[SourceCode.zip](https://github.com/dotnet/Silk.NET/files/14119322/SourceCode.zip)

**__If you know how to fix this issue, please submit a pull request instead!__**

**Comment by Perksey** [comment]
For the most part, our stance is that we do not support 32-bit. In principal, this should mean that any API that isn’t supported on Android 32-bit (currently our only supported 32-bit target) is unsupported completely for 32-bit. In practice, the two notable APIs where we’ve found issues (and the reason why this policy was put in place) were SDL and D3D9.

All this to say that issues like these are to be expected if you use an x86 configuration.

It is possible that we could do more to document this.

Here is where we originally discussed this policy: https://discord.com/channels/521092042781229087/587346162802229298/825768049558028288
