### ISSUE TITLE
is `VK_KHR_dedicated_allocation` extension missing?

### ISSUE THREAD

**Issue by jcyuan** [dotnet/Silk.NET#1950]
sorry i didn't find it even tried to find in the source code...
or i just missed it?
thanks so much.

**Comment by Perksey** [comment]
This is a struct/enum extension only. Because it doesn’t add any new functions, a class isn’t generated. The structs in question are in the main package. Please note we prefer the discussions feature to be used for questions.

**Comment by jcyuan** [comment]
> This is a struct/enum extension only. Because it doesn’t add any new functions, a class isn’t generated. The structs in question are in the main package. Please note we prefer the discussions feature to be used for questions.

okay, thank you.
