### ISSUE TITLE
Directx9 CheckDeviceFormat and CheckDeviceFormatConversion missing

### ISSUE THREAD

**Issue by Revan1985** [dotnet/Silk.NET#1954]
# Summary
The methods CheckDeviceFormat and CheckDeviceFormatConversion for IDirect3DDevice9Ex are missing

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Standard 2.0
- API: DirectX
- API Version: 9

Hi all,
I am using Silk.Net to port an internal library from c++/cli to c#.
As in the summary, I cannot find the CheckDeviceFormat and CheckDeviceFormatConversion methods.
This is a missing, or have been "deprecated" in some way?

Thanks for your help, have a nice day

**Comment by Perksey** [comment]
This is on the IDirect3D9 interface and its descendants.
