### ISSUE TITLE
wrong type for `DebugReportCallbackFunctionEXT` generated

### ISSUE THREAD

**Issue by jcyuan** [dotnet/Silk.NET#1956]
[        uint flags,](https://github.com/dotnet/Silk.NET/blob/e853c232ddcb081943f3c8d1ded2f2a2f4570691/src/Vulkan/Silk.NET.Vulkan/DebugReportCallbackFunctionEXT.cs#L6)

`flags` should be `DebugReportFlagsEXT`

**Comment by Perksey** [comment]
We can't fix this without a breaking change unfortunately.
