### ISSUE TITLE
Build shaderc, SPIRV-Cross, and SPIRV-Reflect native packages for `linux-arm`

### ISSUE THREAD

**Issue by alexrp** [dotnet/Silk.NET#2015]
On the Silk side, this just requires some trivial build script modifications.

Need to check if Zig support is good enough: https://github.com/ziglang/zig/issues/3174

**Comment by Perksey** [comment]
FWIW zig cc is likely to have full support even if Zig itself doesn't, zig cc is basically repackages clang but it Just Works™ out of the box

**Comment by alexrp** [comment]
For some reason I thought there were outstanding issues for `linux-arm` in Zig, but looks like those were fixed in 0.11.0, judging by past me's decision in https://github.com/vezel-dev/zig-sdk/issues/1. :thinking: So it's probably just a matter of updating the build script on Silk's side and that's that.

**Comment by alexrp** [comment]
Note to self: Blocked on #1993 which fixes some Zig build script issues.
