### ISSUE TITLE
Create a build script for OpenAL Soft native binaries

### ISSUE THREAD

**Issue by alexrp** [dotnet/Silk.NET#2016]
It looks like there's no build script for this right now. The project uses CMake, so should be fairly straightforward to integrate like all the other native projects.

**Comment by Perksey** [comment]
Please note that we generally don't use the issue tracker for non-user-facing things, these generally go on the Development Tracker here: https://github.com/orgs/dotnet/projects/64/views/13 (I appreciate this is read-only to the public).

I've added this as an entry there.
