### ISSUE TITLE
Input related callbacks in GLFW cause an AccessViolationException

### ISSUE THREAD

**Issue by vlOd2** [dotnet/Silk.NET#2026]
# Summary
When setting any input related callbacks in GLFW, PollEvents causes an AccessViolationException

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 4.7.2
- API: OpenGL
- API Version: Legacy/OpenGL 1.1 (I mostly use Silk.NET to port legacy games)
1. Properly initialize a GLFW context and a window
2. Use either SetKeyCallback, SetMouseButtonCallback or SetCursorPosCallback (probably others too)
3. Call PollEvents

# Comments
Oddly enough, SetWindowSizeCallback and other non-input related callbacks do not cause an access violation

```
// Leaving on this callback is fine
glfw.SetWindowSizeCallback(window, (WindowHandle* window, int width, int height) => 
{
	// Code is executed
	// ...
});
// But uncommenting this line, causes an AccessViolationException when polling the events
glfw.SetKeyCallback(window, (WindowHandle * window, Keys key, 
    int scanCode, InputAction action, KeyModifiers mods) =>
{
	// Code is not executed, game crashes
	// ...
});
```

**Comment by Perksey** [comment]
Does the problem reproduce on .NET 6 or later?

**Comment by vlOd2** [comment]
> Does the problem reproduce on .NET 6 or later?
This issue only happens on .NET Framework, not .NET 6+
