### ISSUE TITLE
Build SwiftShader native package for `win-arm64`

### ISSUE THREAD

**Issue by alexrp** [dotnet/Silk.NET#2066]
This can't be done currently because of errors like this:

```
D:\a\Silk.NET\Silk.NET\build\submodules\SwiftShader\third_party\llvm-10.0\configs\windows\include\llvm\Config\llvm-config.h(44,1): error C1189: #error:  "unknown architecture" [D:\a\Silk.NET\Silk.NET\build\submodules\SwiftShader\build\third_party\llvm-10.0\llvm.vcxproj]
```

This is happening because of this code in SwiftShader's `llvm-config.h` which isn't handling Arm64:

https://github.com/google/swiftshader/blob/62c59c41e194c288c06739788bb0aad3c86b19bf/third_party/llvm-10.0/configs/windows/include/llvm/Config/llvm-config.h#L17-L23

Which then causes this error to happen:

https://github.com/google/swiftshader/blob/62c59c41e194c288c06739788bb0aad3c86b19bf/third_party/llvm-10.0/configs/windows/include/llvm/Config/llvm-config.h#L44

This should be fairly easy to patch on our end.

While doing this, we should also consider building SwiftShader with LLVM 16 instead of 10 (the default).

**Comment by Perksey** [comment]
In our experience upgrading LLVM versions without dedicated engineering effort to do so always has unforeseen consequences. Recommend waiting for upstream to update here.

**Comment by alexrp** [comment]
Turns out this requires more build hackery than expected. I'll see how annoying the contribution process is and send some patches upstream if it's not too much.

**Comment by alexrp** [comment]
https://swiftshader-review.googlesource.com/c/SwiftShader/+/73268
