### ISSUE TITLE
Hi, is NV_DX_interop2 missing for WGL.Extensions?

### ISSUE THREAD

**Issue by jcyuan** [dotnet/Silk.NET#2149]
I found Silk.NET.WGL.Extensions.NV.NVDXInterop only, but there is no extension for NV_DX_interop2.
or maybe there is, but i missed it?
by the way, what does those `Overloads` mean? for example `NVDXInteropOverloads`, is this actually the `NV_DX_interop2`?
thank you so much.

**Comment by Perksey** [comment]
NV_DX_interop2 does not add any new functions therefore it does not have a class generated. For more info see the specification: https://registry.khronos.org/OpenGL/extensions/NV/WGL_NV_DX_interop2.txt

**Comment by jcyuan** [comment]
> NV_DX_interop2 does not add any new functions therefore it does not have a class generated. For more info see the specification: https://registry.khronos.org/OpenGL/extensions/NV/WGL_NV_DX_interop2.txt

thanks for reply, yeah i know that, actually it was the usage confused me, so how can i use NV_DX_interop2 with Silk.WGL? i assume that the Overloads will be auto used for those changes in NV_DX_interop2?

**Comment by Perksey** [comment]
Yes that's correct.

**Comment by jcyuan** [comment]
> Yes that's correct.

Hi sir, sorry for bothering again,

i just found 2 problems:

1, this method is not implemented in WGL.cs:
![image](https://github.com/dotnet/Silk.NET/assets/850854/78a66185-2a5d-45e7-8e92-34f728bcef9e)
so, `if (wgl.TryGetExtension<NVDXInterop>(out var ext))` will fail.

2, `NV_DX_interop` does not exist in the extension string list. but i can still use `wglGetProcAddress("wglDXOpenDeviceNV")` to use those methods, not sure why, it's strange to me...

if i try to use the ext with a 'normal' way just like other extensions:
![image](https://github.com/dotnet/Silk.NET/assets/850854/44cabacb-db2f-45c3-8c03-28c68c22a46e)
by this test code:
```
var wgl = WGL.GetApi();
var ext = new NVDXInterop(wgl.Context);
ext.DxopenDevice(out IntPtr device);
 ext.DxcloseDevice(device);
```
it will fail....

and if i just use it by using DllImport even it does not exist in the extension string list:
![image](https://github.com/dotnet/Silk.NET/assets/850854/1460324d-93f4-4217-8cc3-e2143c94c260)
it just works....

**Comment by Perksey** [comment]
oops

**Comment by Perksey** [comment]
This will now be fixed as part of #2115 (the next update), and the fix is contained in commit [dfb4225](https://github.com/dotnet/Silk.NET/commit/dfb422577c26aaec9346569acdfcdecdeea98ebb). If you would like to work around this in your own code, feel free to use this commit as inspiration.

**Comment by jcyuan** [comment]
> This will now be fixed as part of #2115 (the next update), and the fix is contained in commit [dfb4225](https://github.com/dotnet/Silk.NET/commit/dfb422577c26aaec9346569acdfcdecdeea98ebb). If you would like to work around this in your own code, feel free to use this commit as inspiration.

👏thanks so much.

**Comment by jcyuan** [comment]
hi @Perksey 

i had applied your changes into my logic (as the official release is not ready yet),
i found that i can create NVDXInterop extension in my 'primary' context, once i try to create with any context created later (and shared with the primary context), the creating will fail.

ex info: i manage all DCs in a thread.

maybe i should wait for new official release?

**Comment by Perksey** [comment]
2.21 should have fixed this.

**Comment by jcyuan** [comment]
so fast! thanks so much @Perksey 
but just had a try and it didn't work, here is the code:

```C#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
    [SupportedOSPlatform("windows")]
    private INativeContext CreateNativeContext()
    {
        return WGL.CreateDefaultContext(["Opengl32"]);
    }

// ------

 var nativeContext = CreateNativeContext();
        
        using (MakeCurrent())
        {
            _gl = GL.GetApi(nativeContext);
            _wgl= WGL.GetApi();   // new WGL(nativeContext) not work too.
        }

// test
var test = _wgl.TryGetExtension(out NVDXInterop ext);
```

it throws exception:
![image](https://github.com/dotnet/Silk.NET/assets/850854/8008c198-f931-4c5e-9b2e-6d402589a959)

**Comment by Perksey** [comment]
Please ensure that you're using WGL.GetApi. Please note that the snippet you gave is using GL.GetApi incorrectly - this will only work for OpenGL 1.1 - you need to use a native context that uses wgl.GetProcAddress for the others.

I'm not sure why this isn't working, I'll reopen this issue until a community member can investigate further.

**Comment by jcyuan** [comment]
thanks for your suggestion,
i have changed my code like this:
```c#
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static IntPtr GetProcAddress(string proc)
    {
        var p = NativeMethods.wglGetProcAddress(proc);
        return p != IntPtr.Zero ? p : NativeMethods.GetProcAddress(OpenGl32Handle, proc);
    }

        using (MakeCurrent())
        {
            _gl = GL.GetApi(GetProcAddress);
            _wgl = WGL.GetApi();  // way auto create `MultiNativeContext`
        }
```

i think for `_gl` it's fine now, but for `_wgl`, still the same exception.

**Comment by jcyuan** [comment]
update:

i tried to create WGL with `new WGL(new LamdaNativeContext(GetProcAddress));` (the GetProcAddress is the same one the `_gl` uses.

now it has exception, the `_extensions` is null:
![image](https://github.com/dotnet/Silk.NET/assets/850854/aa2c0d35-56ad-4304-b049-837f789d4770)

**Comment by qian-o** [comment]
This is a way I tried, I hope it can help you.

Use TryGetProcAddress instead of GetProcAddress in the GetProcAddress function of MultiNativeContext.
```csharp
public nint GetProcAddress(string proc, int? slot = null)
{
    INativeContext[] contexts = Contexts;
    for (int i = 0; i < contexts.Length; i++)
    {
        if (contexts[i]?.TryGetProcAddress(proc, out IntPtr intPtr, slot) ?? false)
        {
            return intPtr;
        }
    }

    return 0;
}
```

Initialize and assign _extensions in WGL.

This can effectively solve the extension problem of WGL.

![image](https://github.com/dotnet/Silk.NET/assets/84434846/5a11ec34-b9c2-4302-b911-cc6ff6f20a2c)
