### ISSUE TITLE
SDL2 gone on publish

### ISSUE THREAD

**Issue by Coloryr** [dotnet/Silk.NET#2157]
# Summary
SDL2.dll gone on publish

```
System.IO.FileNotFoundException: Could not load from any of the possible library names! Please make sure that the library is installed and in the right place!
   at Silk.NET.SDL.Sdl.CreateDefaultContext(String[] n)
   at Silk.NET.SDL.Sdl.GetApi()
   at ColorMC.Gui.Utils.InputControl.Init() in E:\code\ColorMC\src\ColorMC.Gui\Utils\InputControl.cs:line 21
   at ColorMC.Gui.UIBinding.BaseBinding.Init() in E:\code\ColorMC\src\ColorMC.Gui\UIBinding\BaseBinding.cs:line 85
```

```
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>..\build_out\win-x64-dotnet\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
</Project>
```

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 8
- API: SDL2
- API Version: SDL2

![image](https://github.com/dotnet/Silk.NET/assets/26276037/fd0a91d6-0eb7-4021-b4ee-e7698445e8be)
but in AOT is back.
![image](https://github.com/dotnet/Silk.NET/assets/26276037/58d7c347-d86a-4be7-b371-613469ce4cb6)

**Comment by Perksey** [comment]
First try removing the Platform property - this is implicit now. If that doesn’t work, try setting IncludeNativeLibrariesForSelfExtract to false. If that doesn’t work, try removing your custom publish directory. If that doesn’t work, I’m out of things to suggest.

**Comment by Coloryr** [comment]
> First try removing the Platform property - this is implicit now. If that doesn’t work, try setting IncludeNativeLibrariesForSelfExtract to false. If that doesn’t work, try removing your custom publish directory. If that doesn’t work, I’m out of things to suggest.

`IncludeNativeLibrariesForSelfExtract` after set false, the file appears, but there are also many files appearing together. How to run it without errors while keeping it is true.

**Comment by Coloryr** [comment]
Could considered enabling `IncludeNativeLibrariesForSelfExtract` to work properly?

**Comment by Coloryr** [comment]
> [The docs say](https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting/#ensure-the-underlying-api-is-present-on-the-system/) that Silk.NET will search the `PATH` for native libraries, if they are not found in the output dir.
> 
> When `IncludeNativeLibrariesForSelfExtract` is enabled, the native libraries are embedded into the `exe` and extracted to a temp path upon starting the program.
> 
> Maybe Silk.NET in addition to searching the `PATH` could also search in those temp dirs, which can be retreived via `AppContext.GetData("NATIVE_DLL_SEARCH_DIRECTORIES")`?
> 
> EDIT: Just tried it out and it does seem to work!
> 
> All I had to do was add an additional path resolver before calling `Window.Create`:
> 
> ((DefaultPathResolver)PathResolver.Default).Resolvers.Add(file =>
>     AppContext.GetData("NATIVE_DLL_SEARCH_DIRECTORIES") is string nativeDllSearchDirectories
>         ? nativeDllSearchDirectories.Split(";").Select(directory => Path.Combine(directory, file))
>         : []
> );

Thanks!!!!!
