### ISSUE TITLE
Error when trying to use TextureStorage3D on Android

### ISSUE THREAD

**Issue by davidtme** [dotnet/Silk.NET#2163]
# Summary
when trying to call TextureStorage3D on Android I get the following exception:

`Silk.NET.SDL.SdlException: 'Failed loading _glTextureStorage3D: undefined symbol: __glTextureStorage3D'`

![image](https://github.com/dotnet/Silk.NET/assets/1804141/2937fcaa-88b0-40de-93e7-8101885e4aef)

# Steps to reproduce
- Platform: Mobile
- Framework Version: .NET Core 8
- API: OpenGL
- API OpenGLES 3.2

## Minimal code example

```C#
using System.Diagnostics;
using Android.App;
using Silk.NET.OpenGL;
using Silk.NET.Windowing;
using Silk.NET.Windowing.Sdl.Android;

namespace AndroidDemo
{
    [Activity(Label = "@string/app_name", MainLauncher = true)]
    public class MainActivity : SilkActivity
    {
        protected override void OnRun()
        {
            var options = ViewOptions.Default;
            options.API = new GraphicsAPI(ContextAPI.OpenGLES, ContextProfile.Compatability, ContextFlags.Default, new APIVersion(3, 2));
          
            var view = Silk.NET.Windowing.Window.GetView(options);

            view.Load += () => { 
                var gl = GL.GetApi(view);
                var texture = gl.GenTexture();
                gl.ActiveTexture(TextureUnit.Texture0);
                gl.BindTexture(TextureTarget.Texture2DArray, texture);
                gl.TextureStorage3D(texture, 1u, SizedInternalFormat.Rgba8, 1024, 1024, 1);
            };

            view.Run();
            view.Dispose();
        }
    }
}
```

**Comment by Perksey** [comment]
Yes, direct state access functions such as this one is only available in OpenGL 4.5+ and is not present in any OpenGLES version. Not a bug, user error.

**Comment by davidtme** [comment]
@Perksey I'm a bit confused, on https://registry.khronos.org/OpenGL-Refpages/es3/html/glTexStorage3D.xhtml it is OpenGL ES 3+ has glTexStorage3D

![image](https://github.com/dotnet/Silk.NET/assets/1804141/a21bb2b5-0a00-43e5-924e-4a956e373c8d)

Microsoft also seems to think it should be in es3

https://learn.microsoft.com/en-us/dotnet/api/android.opengl.gles30.gltexstorage3d?view=net-android-34.0#android-opengl-gles30-gltexstorage3d(system-int32-system-int32-system-int32-system-int32-system-int32-system-int32)

(sorry if I've misunderstood what you mean by direct state access function).

**Comment by Perksey** [comment]
glTexStorage3D is different to glTextureStorage3D

**Comment by davidtme** [comment]
@Perksey sorry for wasting your time 🤦🏻‍♂️

**Comment by Perksey** [comment]
No worries! Easy mistake to make :)
