### ISSUE TITLE
MAUI project on Android using OpenXR

### ISSUE THREAD

**Issue by MSU-PV** [dotnet/Silk.NET#2170]
# Summary
Hi,

I am trying to solve unexpected problems when using OpenXR in the MAUI application with Silk.NET NuGet packages on Android.

I prepared a minimalist demo to check the possibility of using Silk.NET for our business, but I couldn't find a working constellation for it.

# Steps to reproduce
1. Create a default MAUI application in the Visual Studio 2022:
![01 Create default MAUI](https://github.com/dotnet/Silk.NET/assets/119041038/38757b8a-61f3-44df-9503-198f3708bea0)
![02 Create default MAUI](https://github.com/dotnet/Silk.NET/assets/119041038/6d1ee54f-ea08-4d2c-b563-97a3d6b3f964)
![03 Create default MAUI](https://github.com/dotnet/Silk.NET/assets/119041038/06586f23-c84a-43aa-98da-628c9b6a4026)
![04 Create default MAUI](https://github.com/dotnet/Silk.NET/assets/119041038/35babcdc-ca67-44ff-a2c7-abf33071bbd7)

2. To avoid the possibility that we are missing a NuGet package, we will install all of them from Silk.NET:
![05 Install All NuGets from Silk NET](https://github.com/dotnet/Silk.NET/assets/119041038/a4967071-6041-4c70-84fa-b07dbd992bd8)

3. Set the project to the Unsafe code:
![06 Set Unsafe code](https://github.com/dotnet/Silk.NET/assets/119041038/ad943d69-edc1-4027-8e89-ecfac0e408e3)

4. Edit the code to get the OpenXR Extensions:
![07 Edit code to get  OpenXR extensions](https://github.com/dotnet/Silk.NET/assets/119041038/735e4e2f-5a7c-4070-8de1-2e8ca60c2af3)

5. Run the application:
![08 Run the MAUI app on Windows](https://github.com/dotnet/Silk.NET/assets/119041038/8809d28a-74fc-41de-b960-306943852c35)

6. Click on the button Click me:
![09 Click on Click me button in the app](https://github.com/dotnet/Silk.NET/assets/119041038/03564fe2-b564-4a74-8a92-c81039cf92ac)
**This is the first one I would like to ask how to solve this?**

7. I found the solution in installing a NuGet package **Evergine.OpenXR**:
![10 Try install NuGet Evergine OpenXr](https://github.com/dotnet/Silk.NET/assets/119041038/193e4557-01d5-45c2-841a-c7594ba9fe3f)

8. Run the app with **Evergine.OpenXR**:
![11 Run with NuGet Evergine OpenXr](https://github.com/dotnet/Silk.NET/assets/119041038/aa1682ba-d493-4e1f-82c9-1dd9d13cf698)
**It works.**
![12 Run with NuGet Evergine OpenXr](https://github.com/dotnet/Silk.NET/assets/119041038/385ddcab-6d65-4d93-abce-36f277495b3c)

9. Run another sample app with all known work-arounds:
![13 Run with all known work-arounds](https://github.com/dotnet/Silk.NET/assets/119041038/d1e3f91a-8c9c-413e-b81f-abce940efce4)
It works without exception, but it doesn't load any OpenXR extensions.

- Platform: 
    Mobile - Android, API 34, in emulator, Pixel5+6, (Magic Leap 2 )
    AR - Magic Leap 2, Andorid (AOSP) 10.0 - API 29
    Desktop - Windows 11
- Framework Version: .NET 8, MAUI, Visual Studio 2022
- API: OpenXR

# Comments
Want some information?

**As a solution, it would be enough for me if you create a minimalistic MAUI application in which OpenXR support would work.**

**Comment by Perksey** [comment]
Sorry, we’re not going to write your app for you. We also don’t support MAUI at this time, only .NET 8 Android. Also we do not control the Evergine package. Finally, if you want something like this to be developed, please consider taking out a paid sponsorship.
