### ISSUE TITLE
SDL API not loading on M-series Mac

### ISSUE THREAD

**Issue by joskuijpers** [dotnet/Silk.NET#2173]
# Summary
I am unable to load the SDL API on my Mac, even though the same code works on Windows.

# Steps to reproduce
- Platform: Desktop, MacBook Pro M-series
- Framework Version: .NET Core 8
- API: SDL
Added Silk.NET.SDL to my project
Then with this code, this works fine on a Windows 64bit (Win10) machine:

```c#
    SdlProvider.InitFlags = Sdl.InitVideo | Sdl.InitEvents;
    var sdl = SdlProvider.SDL.Value;

    WindowFlags flags = WindowFlags.AllowHighdpi;    
    var windowHandle = sdl.CreateWindow("Hello World", Sdl.WindowposUndefined, Sdl.WindowposUndefined, 640, 480,      (uint)flags);

while(true) {}
```

On my MBP, it fails in creating the API (also when using GetApi). It exits before it reaches the line after acquiring the API.
I've looked at the resource folder: libSDL2-2.0.dylib is available in `runtimes/osx/native`, the rest of the Silk libraries are in `runtimes/osx-arm64`.

# Comments
Maybe the library is not being found in the right place? I tried to find how the build system works for ARM but not successfully yet.

**Comment by joskuijpers** [comment]
The way https://github.com/dotnet/Silk.NET/blob/main/src/Native/Silk.NET.SDL.Native/build/net461/Ultz.Native.SDL.targets is set up, it should set 'osx-x64' even on ARM (due to the 64bit check). This means it will look in runtimes/osx-x64/native. It is not there.

**Comment by Perksey** [comment]
Are you using .NET Framework/Mono? That targets file does not apply otherwise.

**Comment by alexrp** [comment]
If you are *not* using Framework/Mono, I would be curious if you could try moving the dylib into `runtimes/osx-arm64` and see if it works then. If so, then this is indeed a bug in our packaging.

**Comment by joskuijpers** [comment]
I am not no. :D I barely know what I am doing on the native part.

https://github.com/dotnet/Silk.NET/pull/1645/files#diff-39bb3db1dc156c384f572851e6b01ecb0c6202605e127a734446753414bde82a

I see here that the libs got added here, but no config for OSX

**Comment by Perksey** [comment]
Does it work if you use dotnet publish or dotnet run with a runtime identifier specified?

**Comment by joskuijpers** [comment]
Moved the file, but it gets put back on Run. Any tip on how I can try this properly?

**Comment by joskuijpers** [comment]
> Does it work if you use dotnet publish or dotnet run with a runtime identifier specified?

dotnet run -r osx-arm64 -> same issue
dotnet run -r osx-x64 -> wrong CPU error (to make sure...)
dotnet run -r osx -> unknown runtime

**Comment by alexrp** [comment]
Do something like this:

```console
$ dotnet build
$ cp bin/Debug/net8.0/runtimes/osx/native/libSDL2-2.0.dylib bin/Debug/net8.0/runtimes/osx-arm64/native # replace net8.0 as appropriate
$ dotnet run --no-build
```

Does this work? (Basically trying to determine if the runtime is even attempting to pick up anything from `runtimes/osx`.)

**Comment by joskuijpers** [comment]
> % dotnet run --no-build                                                                               
A
B

No :( With code:

```cs
unsafe
{
    Console.WriteLine("A");
    SdlProvider.InitFlags = Sdl.InitVideo | Sdl.InitEvents;
    Console.WriteLine("B");
    var sdl = SdlProvider.SDL.Value;
    Console.WriteLine("C");
 }
```

**Comment by joskuijpers** [comment]
Oh... I remembered now to look at the system Console:

> Exception Type:        EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

**Comment by alexrp** [comment]
What's the output of `file runtimes/osx/native/libSDL2-2.0.dylib`?

**Comment by joskuijpers** [comment]
That one is both x64 and arm, but:

> codesign --verify bin/Debug/net8.0/runtimes/osx/native/libSDL2-2.0.dylib
bin/Debug/net8.0/runtimes/osx/native/libSDL2-2.0.dylib: invalid signature (code or signature have been modified)
In architecture: arm64

(fine for Skia and libwgpu (from your WebGPU))

**Comment by alexrp** [comment]
I don't really know how code signing works on macOS. Is there a way to turn off the enforcement just to see if that's the cause of the issue?

**Comment by joskuijpers** [comment]
I've signed it myself (overwriting the existing signature), and then it runs. So it is definitely the wrong signature.

**Comment by alexrp** [comment]
Did you do ad-hoc signing or an actual certificate?

**Comment by joskuijpers** [comment]
Actual certificate in this case. Let me find how to sign ad-hoc...
I do seem to understand clang auto-signs when it builds on macOS, so that might explain why the wgpu binary is signed correctly.

**Comment by joskuijpers** [comment]
'broken' signature:
> Identifier=libSDL2-55554944bb706839cb39394db041064fbfb14ef3
Format=Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=11881 flags=0x2(adhoc) hashes=362+5 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12

After I signed it adhoc:
> Executable=/Users/joskuijpers/Developer/RealismusModding/rts/eagle/src/Eagle.Playground/bin/Debug/net8.0/runtimes/osx/native/libSDL2-2.0.dylib
Identifier=libSDL2-2-55554944bb706839cb39394db041064fbfb14ef3
Format=Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=11787 flags=0x2(adhoc) hashes=362+2 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12

**Comment by alexrp** [comment]
Well, we also build SDL on macOS (using `xcodebuild` even), so the resulting binaries *should* be ad-hoc signed. My current suspicion is that the signature for the Arm64 portion somehow gets corrupted when we `lipo` the x64 and Arm64 binaries together. :thinking:

I don't have a macOS system, though, so hard for me to investigate this.

**Comment by joskuijpers** [comment]
I'm glad to help you figure it out :)

To be sure, I've renamed the file to something else, and an existing signature survives that. (I am not sure myself what the signature signs). So the identifier being libSDL2 instead of 2-2 should not be an issue.
A difference I see is the 'size'.

I'd think you need to sign after lipo?

Can I try building this whole thing locally?

**Comment by alexrp** [comment]
> I'd think you need to sign after lipo?

That may be it. My understanding is that each arch portion of a fat binary has its own signature, but maybe you also need to sign the combined fat binary at the end... :thinking:

> Can I try building this whole thing locally?

Clone the repo and do `git submodule update --init --recursive build/submodules/SDL`, followed by `./build.sh sdl2` to perform the build.

* This just builds the SDL native binaries, so you shouldn't need anything except .NET SDK 7 and Xcode.
* Do *not* clone the entire repository recursively since we have a lot of huge submodules (and some of them don't even clone cleanly).

You can find the build logic here: https://github.com/dotnet/Silk.NET/blob/main/build/nuke/Native/SDL2.cs

**Comment by joskuijpers** [comment]
Last line of the build: :)

> [ERR] SDL2: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: warning: changes being made to the file will invalidate the code signature in: /Users/joskuijpers/Developer/Silk.NET/src/Native/Silk.NET.SDL.Native/runtimes/osx/native/libSDL2-2.0.dylib (for architecture x86_64)
[ERR] SDL2: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: warning: changes being made to the file will invalidate the code signature in: /Users/joskuijpers/Developer/Silk.NET/src/Native/Silk.NET.SDL.Native/runtimes/osx/native/libSDL2-2.0.dylib (for architecture arm64)

**Comment by alexrp** [comment]
You can have multiple .NET SDKs installed side-by-side. One way is to use the [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script), e.g. `dotnet-install -v <sdk version>`.

**Comment by Perksey** [comment]
That'd do it 🤦

**Comment by joskuijpers** [comment]
Interestingly:

> codesign --verify src/Native/Silk.NET.SDL.Native/runtimes/osx/native/libSDL2-2.0.dylib
succeeds

**Comment by alexrp** [comment]
Hm. I mean, it does make sense that `strip` would invalidate the signature if it doesn't re-ad-hoc-sign it.

But `codesign --verify` then succeeding? That's strange. Does macOS have some special-casing going on for binaries built on the current system?

**Comment by joskuijpers** [comment]
I have no idea. I can make a PR with extra code-signing at the end. Then I can download the binary and verify again.

**Comment by alexrp** [comment]
That's a bit involved due to the way our native builds are triggered (it's not as simple as a PR). But, I think @Perksey daily-drives macOS, so maybe you can upload the binary you just built for him to `codesign --verify`? If we can confirm that it verifies on your system only because you built it, then I think we have sufficient information to know that we indeed just need to ad-hoc sign after stripping.

**Comment by joskuijpers** [comment]
Alright, I can do that. I made a PR anyways: #2174

**Comment by joskuijpers** [comment]
@Perksey I have uploaded the files to https://github.com/joskuijpers/Silk.NET/tree/testsign/src/Native/Silk.NET.SDL.Native/runtimes/osx/native

**Comment by joskuijpers** [comment]
For now I have a workaround:
```xml
<Target Name="Codesign" AfterTargets="Build">
    <Exec Command="codesign --force --sign - $(TargetDir)/runtimes/osx/native/libSDL2-2.0.dylib" />
</Target>
```

**Comment by joskuijpers** [comment]
Thank you for the super quick responses!

**Comment by alexrp** [comment]
Thanks for helping diagnose and fix it!
