### ISSUE TITLE
Android 14/API 34 RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED error

### ISSUE THREAD

**Issue by Basewq** [dotnet/Silk.NET#2232]
# Summary
Running on an Android device with Android 14+ will throw an error on the Activity.OnCreate method
`Java.Lang.SecurityException: ' One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts'`

As per Google, IntentFilters must explicitly declare RECEIVER_EXPORTED/RECEIVER_NOT_EXPORTED flag or the OS will just crash the app:
https://developer.android.com/develop/background-work/background-tasks/broadcasts#context-registered-receivers

# Comments
Requires updated SDL code, eg.
Current code has
https://github.com/dotnet/Silk.NET/blob/9b12fbeb69f2b29c9b48b36033f0953d6db17c8c/src/Windowing/SilkDroid/app/src/main/java/org/libsdl/app/HIDDeviceManager.java#L196
But new SDL properly declares
https://github.com/libsdl-org/SDL/blob/3d42412650119a8e13a016e289e5860c034dde19/android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java#L196-L200

No workaround for Android 14+ due to it baked in the OS.

**Comment by Perksey** [comment]
Duplicate of #2210, we will be updating our binaries shortly.

**Comment by Basewq** [comment]
> Duplicate of #2210, we will be updating our binaries shortly.

Just double checking as I don't know your build system, you'll also be updating the SDL code as well?
As far as I can tell, you don't have these latest changes (in fact, the last update for this fix on SDL side of things was just last week)

**Comment by Perksey** [comment]
Yes.

**Comment by Pyrdacor** [comment]
I really need this fix. Users are waiting for the Android release.

**Comment by Perksey** [comment]
The Silk.NET 2.X team at this time is just Beyley, and they've mostly moved out of the Silk.NET development space meaning they have less time to dedicate to Silk.NET. We just don't have the maintainer team we need to be able to swiftly develop 2.X right now.

**Comment by Pyrdacor** [comment]
What happened to the other team members and what does "moved out" mean? What are they doing currently?

**Comment by Beyley** [comment]
> What happened to the other team members 

They either only really work on Silk 3.0 (currently unreleased), or are in the same boat as me, unable to dedicate much time to the project atm.

> what does "moved out" mean? What are they doing currently?

I primarily have been working with non-C# languages lately, and when I do write C#, it's generally not for gamedev.

My work on Silk.NET was driven by my passion to work on gamedev tools for C#, but my personal projects have shifted away from needing that, and personal issues have lead to me only really having the time to dedicate to one or two projects at a time right now, which has lead to Silk.NET being left on the backburner for me for the past little while.

**Comment by Pyrdacor** [comment]
It is totally fine if other things have higher priorities. I was just curious if you have to work on other related projects.

I would be glad to help you out but I fear my knowledge about the SDL stuff is too limited and without anyone checking PRs it would be impossible to bring this forward I guess. What can I (or others do) to help?

**Comment by Perksey** [comment]
A 2.X maintainer really would be responsible for reviewing PRs coming in, regenerating the bindings (in most cases this “just works,” but there are some oddities in the process that could make this painful sometimes), and rebuilding native libraries. We’re not *intending* to have additive work done to 2.X these days, most new stuff is being saved for 3.0.

Pretty sure the team would welcome anyone reputable/trustworthy that is happy to do that in a heartbeat.

**Comment by Pyrdacor** [comment]
If you can give me a shirt briefing about the process of regenerating the bindings and rebuilding the native libraries (including the mentioned oddities) I can give it a shot. You can also contact me on discord.

But I am honest right now. I am also very involved with other projects. Of course two maintainers which have little time are better than one of them, but don't expect too much from me either. Still I can at least help from time to time to review stuff or bring everything up to date.
