### ISSUE TITLE
Silk.Net.Core Project does not build because of RequiresLocationAttribute

### ISSUE THREAD

**Issue by Bkara1981** [dotnet/Silk.NET#2251]
# Summary
Project does not build because of RequiresLocationAttribute in Silk.Net.Core/Native/Structs/ID3DInclude.gen.cs

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3, .NET 4.8, Xamarin Android 8.1
- API: Vulkan/OpenGL
- API Version: Vulkan 1.2/OpenGL 4.3 Legacy/OpenGL 4.5 Core/OpenGLES 3.2
1. Try to build Silk.Net.Core latest and get error. 

# Comments
. 

**__If you know how to fix this issue, please submit a pull request instead!__**

**Comment by Perksey** [comment]
Silk.NET requires a specific .NET SDK to build, and does not build with the latest SDKs. For more information see the global.json and our GitHub workflows.
