### ISSUE TITLE
Imgui Docking feature "undocks" previously docked windows

### ISSUE THREAD

**Issue by OneAbowAll** [dotnet/Silk.NET#2263]
# Summary
For some reason when closing and reopening the app Imgui undocks all the windows that were docked.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3, .NET 8
- API: OpenGL
- API Version: OpenGL 4.6 Core

1. Dock windows anyway you like
2. Close app
3. Reopen app

# Comments
Right now this is the flags that I'm setting OnLoad:
```
    io.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
```

And this is the code im using to create the Dockspace / OnRender code:
```
Gl.Clear((uint) ClearBufferMask.ColorBufferBit);
controller.Update((float)delta);
ImGui.DockSpaceOverViewport(ImGui.GetMainViewport(), ImGuiDockNodeFlags.PassthruCentralNode);

ImGui.BeginDemoWindow();
//etc... etc...
controller.Render();
```

# Example Image
Before closing the app:
![docked](https://github.com/user-attachments/assets/79e55c68-91d2-4b48-b32d-0bf60391f134)

After closing and then reopening the app:
![undocked](https://github.com/user-attachments/assets/93a5c959-43bf-443d-af5b-bd2c448007fe)
As you can see the window's positions are correct, but the expected behaviour is not.

**Comment by OneAbowAll** [comment]
Ok after looking into it i think i found a solution.
You have to set the DockingEnable config flag as soon as possible inside the constructor of ImGuiController.

```
public ImGuiController(GL gl, IView view, IInputContext input, ImGuiFontConfig? imGuiFontConfig = null, Action onConfigureIO = null)
{
    Init(gl, view, input);
    ImGuiIOPtr iO = ImGuiNET.ImGui.GetIO();
    if (imGuiFontConfig.HasValue)
    {
        IntPtr glyph_ranges = imGuiFontConfig.Value.GetGlyphRange?.Invoke(iO) ?? ((IntPtr)0);
        iO.Fonts.AddFontFromFileTTF(imGuiFontConfig.Value.FontPath, imGuiFontConfig.Value.FontSize, null, glyph_ranges);
    }

    onConfigureIO?.Invoke();
    iO.BackendFlags |= ImGuiBackendFlags.RendererHasVtxOffset;
    iO.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
    CreateDeviceResources();
    SetKeyMappings();
    SetPerFrameImGuiData(1f / 60f);
    BeginFrame();
}
```

**Comment by Perksey** [comment]
I’m glad you found a solution! Note that these sorts of things is why we expose the onConfigureIO callback, so hopefully this helps and you don’t need to manually edit the controller source :)
