### ISSUE TITLE
sdl2 crash in macos arm64

### ISSUE THREAD

**Issue by Coloryr** [dotnet/Silk.NET#2282]
# Summary
sdl2 crash in macos arm64
```
var sdl = Sdl.GetApi();
```

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET8
- API: SDL2
- API Version: SDL2

# Comments

https://github.com/user-attachments/assets/bbf60937-e644-4ffe-8b4f-5bbe6438d02e

**Comment by Perksey** [comment]
Hi. We don’t support MAUI at this time, only .NET Android without MAUI. In addition, there’s not enough information on this issue to suggest anything other than following the Android example we have in the repo if you do want to pursue this.

**Comment by Coloryr** [comment]
this is avalonia not maui. and this desktop application

**Comment by Perksey** [comment]
Ah ok. We don’t support Avalonia at all at this time, at least for SDL.

**Comment by Coloryr** [comment]
So it never work in macos arm64?

**Comment by Perksey** [comment]
By all means give it a go but Avalonia is not a scenario we support for SDL. I also have no idea what your error was, given that you did not include any details such as an exception or stack trace, so I did my best to identify the issue with the information provided.

**Comment by Coloryr** [comment]
Just crash went
```
var sdl = Sdl.GetApi();
```
not log, not any info, with arm64 build, but use x64 build it's work.

**Comment by Perksey** [comment]
Yes this library can be used on macOS arm64, that’s my daily driver. I advise making a brand new project and copying the code from an example in the repo to see whether known-good code works. If it does, then it’s likely a problem with your specific scenario.

**Comment by Coloryr** [comment]
Ok, I will try it out on the weekend

**Comment by Coloryr** [comment]
Nope it just crash on consoleapp

**Comment by Coloryr** [comment]
yes, it's SDL arch issues, I replaced the sdl library built with arm64 and it will work properly now.
