### ISSUE TITLE
[Math][Matrix] Support both LookAtRh and LookAtLH or, at least, add the coordinate system in comments or in readme

### ISSUE THREAD

**Issue by guiguibubu** [dotnet/Silk.NET#2286]
# Summary of feature
Add support for both coordinate system for LookAt matrix. Like it is in Stride 3D Engine
https://github.com/stride3d/stride/blob/master/sources/core/Stride.Core.Mathematics/Matrix.cs

Or add some comments on the LookAt function to explicitely write the coordinate system. Or/And add it in the readme of the project

# Comments

# Does this have a proposal?
Check the documentation/proposals folder. If it doesn't have one, you may need to create one if you're making **massive breaking changes**.

**Comment by Perksey** [comment]
Looks like [this proposal](https://github.com/dotnet/Silk.NET/blob/main/documentation/proposals/Proposal%20-%20Generic%20Math.md) has defined this, should be implemented with 3.0 generic maths.

**Comment by guiguibubu** [comment]
Thanks for the answer !
Is there a branch to help the dev of this proposal ?
I close the issue.

**Comment by Perksey** [comment]
I’ll keep this open until implemented
