### ISSUE TITLE
[Vulkan] Setting a ClearValue that includes ClearColorValue and ClearDepthStencilValue has weird effects

### ISSUE THREAD

**Issue by leafspr1ng** [dotnet/Silk.NET#2360]
I'm not sure if this is an actual issue or I am using the structs wrong. 

What I am doing is the following, which should lead to a black clear:

```
var clearValue = new ClearValue()
 {
     Color = new ClearColorValue()
     {
         Float32_0 = 0,
         Float32_1 = 0,
         Float32_2 = 0,
         Float32_3 = 1,
     },

     DepthStencil = new ClearDepthStencilValue()
     {
         Depth = 1.0f,
         Stencil = 0
     }
 };
```

However, the clear is red and the only way to get it to actually be whatever color is specified in the ClearColorValue is to remove the depth/stencil part. Looking into the Silk structs, I noticed the field offsets do seem odd, as in: They are both 0, so it might end up in arbitrary order when copied?

```
/// <summary></summary>
        [FieldOffset(0)]
        [NativeName("Type", "VkClearColorValue")]
        [NativeName("Type.Name", "VkClearColorValue")]
        [NativeName("Name", "color")]
        public ClearColorValue Color;
/// <summary></summary>
        [FieldOffset(0)]
        [NativeName("Type", "VkClearDepthStencilValue")]
        [NativeName("Type.Name", "VkClearDepthStencilValue")]
        [NativeName("Name", "depthStencil")]
        public ClearDepthStencilValue DepthStencil;
```

Again, not sure if this is actually an issue or the ClearValue is supposed to only be used with an either/or approach.

**Comment by Perksey** [comment]
This is correct. `ClearValue` should be used to clear _one_ attachment i.e. a color attachment _or_ a depth/stencil attachment. When you begin your render pass you can pass in multiple of these values, intended to correspond with the respective attachments.

More info: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRenderPassBeginInfo.html

**Comment by leafspr1ng** [comment]
That makes a lot of sense and I probably should have read the spec more carefully. :)

The fact that Silk technically does not behave according to spec (values are ignored vs. their presence breaks the intended behavior) is probably acceptable in this case and more of a known idiosyncrasy than something to waste effort on...

**Comment by Perksey** [comment]
It's a union so writes to Color will overwrite values in DepthStencil - equivalent C code behaves the same way. The spec wording is interesting here.

**Comment by Perksey** [comment]
Ok, I’m closing this though as Silk.NET seems to be doing everything right here. Feel free to reopen if there is a C vs C# discrepancy though.
