### ISSUE TITLE
API Tracking

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#265]
We should enable the PublicAPI analyzer on *all* projects. This will help tracking (breaking) changes and track nullability behaviour. Would suggest we get this before the final 2.0. Not very high priority, but an easy job but, imo, a big improvement.

**Comment by HurricanKai** [comment]
Assigning this to myself, but if someone else wants to pick this up, feel free to.
Adding to 2.0, but that's not in stone

**Comment by Perksey** [comment]
Not sure if this should be done for the bindings as we're not in control of upstream breaking changes, but perhaps that's something we can discuss on Friday. Defo Windowing and Input at least.
