### ISSUE TITLE
Silk Touch blocks referencing variables declared inside of them. 

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#288]
For example,
```cs
int n1;
fixed (int* SPECIAL_VAR2 = &n1)
{
    n1 = 5;
}
```

**Comment by Perksey** [comment]
Is this still an issue?

**Comment by HurricanKai** [comment]
I believe so yes. Probably will be resolved when I work on further generalizing the SilkTouch model, it just can't represent this scenario right now.

**Comment by Perksey** [comment]
Hmmm ok, put it on the list for 2.x

**Comment by Perksey** [comment]
"It really isn't a bug, it's just really bad" - Kai 2021

```cs
int n1;
fixed (int* SPECIAL_VAR2 = &n1) // <-- variable is initialized when we take a pointer to it
{
    n1 = 5;
}
```
