### ISSUE TITLE
Remove local functions in maths - not needed in .NET 6, replace with just ifs

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#304]
In 2.X, we used one local function per type (or type combination for methods with multiple Ts) per method to trick older .NET JITs to not go over the inlining budget. In .NET 6, the JIT prevents type specialization `if` branches (like the ones we use in the local functions today) from going over the inlining budget out-of-the-box, so this workaround isn't needed in 3.0 which is .NET 6 only.

**Comment by HurricanKai** [comment]
cc @Perksey anything you know already from your areas

**Comment by Perksey** [comment]
A lot of work will have to go into getting windowing to run on MAUI, as I'm sure that's going to be a popular request and probably how we'll do our mobile support in .NET 6 onwards.

**Comment by HurricanKai** [comment]
I'm guessing that MAUI will compile to native somehow, or at least that's the most performant way.
So yeah, that goes hand in hand with banning reflection.

**Comment by Perksey** [comment]
No issues with reflection as .NET 6's mobile support will be salvaged from Xamarin (and MonoAOT ships everything so no issues with reflection there)

**Comment by HurricanKai** [comment]
Just going to pretend I didn't see thag

**Comment by HurricanKai** [comment]
Not sure where else to write this down, but for 3.0 we should mark all core shared projects with `<SupportedPlatform Include="browser" />`

**Comment by Perksey** [comment]
> Remove method splitting from maths.

Do you know what this refers to? I think we should close this issue in favour of cards on the 3.0 tracker if these are small things.

**Comment by HurricanKai** [comment]
I believe it refers to having many (local) methods per single math method.

**Comment by Perksey** [comment]
Will edit the issue text to just be that then seeing as everything SilkTouch is changing anyways.

**Comment by Perksey** [comment]
#988 is evidence that these are still needed due to code size, closing.
