### ISSUE TITLE
Trimming

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#305]
In addition to the work done in #303 we should consider trimming. Our assemblies are already very large, so trimming would be of great use.
See https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/

**Comment by Perksey** [comment]
Trimming is more suited for the end consumer (application) instead of libraries, as you don't want to prematurely trim away IL for it to blow up on the downstream consumer.

**Comment by HurricanKai** [comment]
In the article they mention that libraries can (and should if possible) annotate APIs.
This won't be needed anymore once reflection has been eliminated, but if that doesn't work out, annotating the api is a good idea.

**Comment by Perksey** [comment]
I am not open to any trimming operations being done to Silk.NET itself. However, if we needed to annotate some APIs for the new (experimental) trimmer then this should be done no earlier than 3.0.

**Comment by HurricanKai** [comment]
Could you explain why you don't want this to be (optionally) done in 2.0?

**Comment by Perksey** [comment]
Primarily because as of 2.0 Silk.NET is still a .NET Standard library, and the new trimmer is .NET 5 only.

**Comment by HurricanKai** [comment]
I see, so you're not happy to multi-target to net5 just for this?

**Comment by Perksey** [comment]
Not for something like this, as it'll be large-scale and files will get messy with lots of preprocessor directives.

**Comment by Perksey** [comment]
Apparently auto trimming is cool, see this tweet from Tanner https://twitter.com/tannergooding/status/1412124486539702272?s=20

**Comment by cyraid** [comment]
@Perksey Trimming is becoming more of a thing now, not sure your comments aged well. One of those decisions that were perhaps made hastily or without considering trimming to be more mainstream. It's definitely up to the libraries to provide hints, as AOT is more and more a thing. Silk.NET is quite bloaty and trimming would help a lot.

**Comment by Perksey** [comment]
I still stand by all of my comments, it would be a maintenance nightmare for 2.X to annotate everything given the multitargeting. You missed the part where I said we’ll do this in 3.0 and the fact that the issue is still open, so we will do this eventually. But thank you for your opinion.

**Comment by HurricanKai** [comment]
One minor change for 2.x that we can do here for sure is annotating Silk.NET.Maths to be trimmable. I just keep forgetting to do this. PRs welcome as always. Would also impact binary size quite a bit already I think.

**Comment by cyraid** [comment]
> I still stand by all of my comments, it would be a maintenance nightmare for 2.X to annotate everything given the multitargeting. You missed the part where I said we’ll do this in 3.0 and the fact that the issue is still open, so we will do this eventually. But thank you for your opinion.

You're right, I don't see it mentioned previously for 3.0, but now you have affirmed it, that's cool.

Issues on many other projects stay open for years sometimes, and sometimes for no reason (sometimes forgetting), one cannot deduce something will be implemented by an issue remaining open :)

But either way that's good, you guys got this. I'll use this library for my project knowing this feature will come, thank you ahead of time.

**Comment by Perksey** [comment]
So incidentally we had to turn on trimming for another optimization being made elsewhere in the library (we need to tell the trimmer to get rid of some full-AOT paths in non-full-AOT scenarios) and, at least for TriangleNET6, I didn't see any trimmer warnings? I'd assume that most of our warnings would come from Windowing and Input, which is covered by that project, so I guess we're good to go.

#1645 implements this
