### ISSUE TITLE
Support for Xamarin Forms OpenGLView

### ISSUE THREAD

**Issue by btschumy** [dotnet/Silk.NET#345]
# Summary of feature
I would like to be able to use Silk.NET in the Xamarin Forms OpenGLView class

# Comments
Right now I don't see the necessary hooks in OpenGLView to be able to use Silk.  ULTZ Perksey indicated that "Yeah you’ll have to implement IGLContext yourself seeing as Silk.NET doesn’t have a dedicated extension package for it yet".  I don't think this is currently possible and he ask me to log a request.

# Does this have a proposal?
No

**Comment by btschumy** [comment]
I will also comment that there is currently no way of doing 3D graphics for iOS, Android, and UWP in a Xamarin Forms app.  UrhoSharp (C# bindings to Urho3D) used to be recommended but the project has been abandoned by Microsoft and It has numerous problems on UWP.

If Silk.NET could be made to work in Xamarin Forms, I'm sure it would be greatly appreciated by many developers.

**Comment by Perksey** [comment]
This is certainly something we want to investigate. Today Silk.NET may only be used on mobile via Xamarin Native instead of Forms.

**Comment by btschumy** [comment]
Is there some example code using Silk.NET on Xamarin Native?  I'm thinking it could be adapted to Xamarin Forms by using a native renderer.

**Comment by Perksey** [comment]
There is only an Android test application today. Silk.NET has its own dedicated Android Activity: https://github.com/Ultz/Silk.NET/tree/2.0/src/Lab/TriangleDroid

**Comment by freever** [comment]
Hello there... is there any change to this following the 2.0 release?

**Comment by Perksey** [comment]
Currently not, personally I want to just hold out for Silk.NET 3.0, .NET 6, and MAUI.

**Comment by freever** [comment]
Yeah, MAUI is really lacking a 3D story. UrhoSharp used to be the go-to but now it's just crickets.

**Comment by Perksey** [comment]
Closing in favour of #849
