### ISSUE TITLE
build.sh needs unix line endings; it can't be run as it is

### ISSUE THREAD

**Issue by vincenzoml** [dotnet/Silk.NET#429]
# Summary
A summary of the issue you're experiencing.

In order to run build.sh on my system, I first of all needed to change its permissions to executable and then to run "todos -d build.sh" to convert it to unix line endings. Please fix both issues on the repository!

**Comment by HurricanKai** [comment]
I don't think it's possible to specify file permissions in git, but we can definitely change line endings.

**Comment by vincenzoml** [comment]
I think git has permissions, see e.g. the - - chmod option here :

https://git-scm.com/docs/git-update-index

**Comment by Perksey** [comment]
I've tried using `git add --renormalize .` which usually fixes the line endings (and has done for some files - but not this one - in #425), but I notice it hasn't done that in this case. Could you possibly do these changes in a PR if you have a spare moment? If not I'll try whip up my Linux environment at some point.

**Comment by vincenzoml** [comment]
Thanks for fixing this!
