### ISSUE TITLE
Sample not rendering correctly

### ISSUE THREAD

**Issue by UltzLtd** [dotnet/Silk.NET#434]
<a href="https://github.com/sneusse"><img src="https://avatars.githubusercontent.com/u/1814523?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sneusse](https://github.com/sneusse)**
_Wednesday Aug 05, 2020 at 21:10 GMT_
_Originally opened as https://github.com/Ultz/SilkExtensions/issues/1_

----

I don't have a lot of experience to debug this, so here's a screenshot how the sample looks for me.

![grafik](https://user-images.githubusercontent.com/1814523/89463814-b66a8f80-d76f-11ea-86cf-d6c6d633b0d2.png)

After some time the blurry stuff vanishes and there's only background. Also, the application crashes on exit.
The ImGui.Net sample works as expected. 

Here's some information, If you need more to debug this I'll update the issue.

Win 10.0.17763
I7-8650U (UHD 620) - Driver 27.20.100.8476
Additionally: Geforce MX150 (deactivated in the device manager, enabling did not change anything)
Build with VS 2019

**Comment by UltzLtd** [comment]
<a href="https://github.com/joffarex"><img src="https://avatars.githubusercontent.com/u/41587092?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joffarex](https://github.com/joffarex)**
_Sunday Mar 21, 2021 at 15:57 GMT_

----

I know its really late comments, but happened to have the same issue with the same GPU. 

So the problem is that you do not have your GPU be defaulted to MX150 (or any other dedicated GPU for that matter), and applications are using the integrated intel GPUs, and as it happens, they dont like imgui.

**Comment by UltzLtd** [comment]
<a href="https://github.com/Perksey"><img src="https://avatars.githubusercontent.com/u/11160611?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Perksey](https://github.com/Perksey)**
_Sunday Mar 21, 2021 at 15:58 GMT_

----

Incredibly strange. I wonder if there's a workaround, as I'm yet to find one...

**Comment by sneusse** [comment]
Oh, I forgot I opened this one :) I switched to MonoGame for the rendering recently, but I had similar issues when the blending modes were off, maybe that's the whole problem?. When I get back to it, I'll try the example again and report it here.
