### ISSUE TITLE
GLFW v3.3.2 on OSX has problems with EGL/OES window creation, use v3.3.3 when it's released

### ISSUE THREAD

**Issue by UltzLtd** [dotnet/Silk.NET#435]
<a href="https://github.com/Tyler-IN"><img src="https://avatars.githubusercontent.com/u/33945568?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tyler-IN](https://github.com/Tyler-IN)**
_Tuesday Aug 18, 2020 at 23:52 GMT_
_Originally opened as https://github.com/Ultz/NativePackages/issues/2_

----

# Summary
UltralightSharp development revealed creating an EGL / OpenGL ES context under OSX in GLFW v3.3.2 would not succeed, and the null returned by glfw.CreateWindow would propagate into a call to RestoreWindow or other native methods and cause an access violation / segmentation fault.
Upgrading to a GLFW pre-v3.3.3 (3.3-stable branch) build solves it. There are multiple issues resolved in the branch with associated issues on the GH GLFW repo.

# Steps to reproduce
- Platform: Desktop OSX / Catalina
- Framework Version: .NET Core 3.1
- API: OpenGL ES (ANGLE & SwiftShader)
- API Version: 3.0
1. Create a Silk.NET project targeting OSX, w/ ANGLE libEGL and libGLESv2
2. Try to create a window and initialize it.

# Comments
glfw.CreateWindow returns null, goes unchecked, and propagates into the next usage of the window handle field to a native method like glfw.RestoreWindow.

SilkNetSandbox in the UltralightSharp project solves by shipping a build of GLFW pre-3.3.3.

GLFW v3.3.3 is not yet released.

**Comment by Perksey** [comment]
@Tyler-IN This has been fixed in #433 and will ship in 2.3.
