### ISSUE TITLE
Better naming for generated Vulkan enum and flag values

### ISSUE THREAD

**Issue by hjred** [dotnet/Silk.NET#458]
# Summary of feature
The generated enum values (regardless if bitflag or not) are often unnecessary long. For example in https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/Enums/DebugUtilsMessageSeverityFlagsEXT.gen.cs
where the full name of the enum is a prefix of every value for example "DebugUtilsMessageSeverityVerboseBitExt".

This leads to extremly long code.

Some of the enums are handled in a more C# way, like https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/Enums/StructureType.gen.cs where the prefix was removed.

Could all enums (and therefor flags) be handled like StructureType as well or are there reasons why not?

My suggestion would be:
* for all enum values to remove the common prefix (without the extension) and the extension at the end.
* for all flag values to remove the common prefix (without Flags and extension) and Bit + extension at the end.

# Comments
* I would like to help if needed, but got lost in the BuildTools project.
* A general naming scheme might need to be discussed upfront:
  1. Keep extension name (KHR, EXT, etc.) on value names or remove them?
  2. Always remove prefix or are there exceptions?

# Does this have a proposal?
Not as of now.

**Comment by Perksey** [comment]
Been thinking about doing this for the 3.0 BuildTools overhaul, good thing you opened this issue to hold me to account!

**Comment by Perksey** [comment]
We have found a way to tackle this in 2.X, changing milestone to 2.X.
