### ISSUE TITLE
Vulkan additional basetype for flags causes generation errors

### ISSUE THREAD

**Issue by hjred** [dotnet/Silk.NET#469]
# Summary
The vulkann spec did change. A VkFlags64 basetype was added to allow 64 bit bitflags. This new basetype is already in
use in:
* https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/Enums/AccessFlags2KHR.gen.cs
* https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/Enums/PipelineStageFlags2KHR.gen.cs

The current generator produces wrong values for anything above 32 bits. This can be seen as duplicated values for different keys.

# Steps to reproduce
- API: Vulkan
- API Version: current vk.xml generated in repo
1. Check source generated in repo

**Comment by hjred** [comment]
Hey there, it seems you make good progress on this issue 👍 

It currently seems, that the fix is sadly not enough. If you look at the generated code from the commit the output is still incorrect, for example here:

https://github.com/dotnet/Silk.NET/blob/25bc56b1ed8056156a7a2fdd668ad4d13a586199/src/Vulkan/Silk.NET.Vulkan/Enums/PipelineStageFlags2KHR.gen.cs#L55

The EnumValue type for parsing still uses an int for the value which overflows when parsing:

https://github.com/dotnet/Silk.NET/blob/25bc56b1ed8056156a7a2fdd668ad4d13a586199/src/Core/Silk.NET.BuildTools/Converters/Khronos/EnumDefinition.cs#L127

**Comment by Perksey** [comment]
Huh, thanks for letting me know! Will fix...

**Comment by hjred** [comment]
Hey there,
I hate to say it, but there are still broken values AccessFlags2KHR
from https://github.com/dotnet/Silk.NET/blob/5c8862a9f0b488ec4a7bdc4cd9734a1f5f34f2c3/src/Vulkan/Silk.NET.Vulkan/Enums/AccessFlags2KHR.gen.cs#L59
to https://github.com/dotnet/Silk.NET/blob/5c8862a9f0b488ec4a7bdc4cd9734a1f5f34f2c3/src/Vulkan/Silk.NET.Vulkan/Enums/AccessFlags2KHR.gen.cs#L65

the other values are looking fine now :)

The difference there is, that these 4 values come from two different extensions and parsing them still seems to rely on int.

**Comment by HurricanKai** [comment]
This should *really* fix this. Thank you for the Help spotting these repeated issues.

**Comment by hjred** [comment]
Now it seems to be a alright 👍 

My pleasure 😄  Maybe I can find other areas to help, I would like to use this library extensively and want to contribute as well. Currently I am still trying to figure out how the details are working

**Comment by HurricanKai** [comment]
Awesome :+1: don't hesitate to ask if you need anything!
