### ISSUE TITLE
Add Shaderc and  SPIRV-Cross bindings?

### ISSUE THREAD

**Issue by FaberSanZ** [dotnet/Silk.NET#482]
Hello,  I would like to know if there are any plans to add [Shaderc ](https://github.com/google/shaderc) and [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross).

**Comment by HurricanKai** [comment]
I'd like to keep this open for tracking

**Comment by Beyley** [comment]
#1201 adds a SPIRV-Cross submodule and the native CI workflow to build it, all someone needs to do is plumb it up to publish the shared libraries, and point the generator to it
