### ISSUE TITLE
Issue running Sdl window with Vulkan

### ISSUE THREAD

**Issue by theprotonfactor** [dotnet/Silk.NET#490]
# Summary
Hi, I've just started to use this library today, so I'm probably doing something stupid, but when I try to force Silk.Net to use an Sdl window with the Vulkan Graphics backend I get an SdlException complaining that the window isn't an OpenGL Window. The exception occurs on line 160 of SdlView.cs when initializing the window view.

# Steps to reproduce
- Platform: Desktop Windows 10
- Framework Version: .NET 5
- API: Vulkan
- API Version: Vulkan Default

The code below is enough to raise the exception for me:

`           Silk.NET.Windowing.Sdl.SdlWindowing.Use();
            SdlProvider.SetMainReady = true;
            var opts = ViewOptions.DefaultVulkan;
            opts.API = GraphicsAPI.DefaultVulkan;

            _window = Silk.NET.Windowing.Window.GetView(opts);

            _window.Initialize();`

If I guard the Create call on line 160 of SdlView.cs like so:

` if (opts.API.API != ContextAPI.Vulkan)
            {
            sharedContext?.MakeCurrent();
            (CoreGLContext as SdlContext)?.Create`

then the exception goes away and everything builds and runs as expected.

# Comments
I'm using a x64 debug SDL2.dll made using the following cmake flags:  -DBUILD_SHARED_LIBS=ON -DVIDEO_VULKAN=ON if that makes any difference.
I could open a pull request for my proposed change, but like I said I'm fairly unfamiliar with the codebase and I could just be doing something dumb. An example that explicitly uses an Sdl window with Vulkan would be much appreciated.

**Comment by Perksey** [comment]
Totally missed that! When I added CoreGLContext my thinking was I didn't need to do an API check because GLContext does it for us, but then I went and added code which naively uses CoreGLContext.

The easiest fix would be do change

```cs
        protected override IGLContext? CoreGLContext => _ctx ??= new SdlContext(Sdl, SdlWindow, this);
        protected override IVkSurface? CoreVkSurface => _vk ??= new SdlVkSurface(this);
```

to

```cs
        protected override IGLContext? CoreGLContext => API.API == ContextAPI.OpenGL || API.API == ContextAPI.OpenGLES
            ? _ctx ??= new SdlContext(Sdl, SdlWindow, this)
            : null;

        protected override IVkSurface? CoreVkSurface => API.API == ContextAPI.Vulkan
            ? _vk ??= new SdlVkSurface(this)
            : null;
```

in SdlView.cs

If you'd like to make a PR for this would be more than happy to accept! Otherwise, I'll sweep this up at the start of June.

**Comment by theprotonfactor** [comment]
Confirmed locally that the change fixes the issue. PR has been made

**Comment by Perksey** [comment]
Awesome! Reopening this until it's merged into main...
