### ISSUE TITLE
Minimizing window causes Vulkan validation layer error spam

### ISSUE THREAD

**Issue by theprotonfactor** [dotnet/Silk.NET#492]
# Summary
I've only tested this with an SDL window, but when running the VulkanTriangle sample under Lab/Experiments, minimizing the window results in the following validation layer error: vkCreateFramebuffer(): Requested VkFramebufferCreateInfo height must be greater than zero. The Vulkan spec states: height must be greater than 0.

Basically, this happens because the extent of the swapchain gets set to zero when the window is in a minimized state, but the frameBufferSize and Size of the IView remain whatever the unminimized resolution was. This causes the CreateSwapChain function to produce an invalid swapchain and as a result triggers the validation error (no crash on my device though). 

I think this can either be fixed by setting the frameBufferSize of the IView to zero when in a minimized state (not sure if that should be the expected behaviour?), or (the more simple fix I implemented locally) by making the CreateSwapChain function more robust to deal with a possible zero extent. Let me know which fix sounds better or if there's a better solution.

# Steps to reproduce
- Platform: Desktop Windows 10
- Framework Version: .NET 5
- API: Vulkan
- API Version: Vulkan 1.2

1. Run the VulkanTriangle sample under src/Lab/Experiments
2. Minimize the SDL window
3. Go to the console output
4. Observe the error spam

**Comment by Perksey** [comment]
This is a problem with our application. Applications in the src/Lab folder are not guaranteed to demonstrate best practice and may be broken in some ways (like you have found) and we should look to fix this when we have a spare minute, which is rare, or if a community member wanted to investigate and fix we’d welcome a PR.

**Comment by theprotonfactor** [comment]
> Applications in the src/Lab folder are not guaranteed to demonstrate best practice

In that case I'll open a PR with my current fix. Although I suspect the more "correct" one is to zero the framebufferSize. I can leave a TODO comment in the code if you guys don't mind stuff like that? I don't see many comments in the code in general, so figured I'd ask first

**Comment by Perksey** [comment]
By all means! The reason for no comments is anything in src/Lab has been created for the purposes of having a quick & dirty demo to test Silk.NET functionality, so it hasn’t seen much love!
