### ISSUE TITLE
Problem with Vulkan Callback issue

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/Silk.NET#499]
@HurricanKai 
# Summary
Unhandled exception. System.InvalidOperationException: Vulkan functions can only be used after initialization (just before the Load callback is executed)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.<get_VkSurface>g__Throw|106_0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.get_VkSurface()
   at VulkanSample.Launch.HelloTriangleApplication.InitWindow() in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 81
   at VulkanSample.Launch.HelloTriangleApplication.Run() in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 28
   at VulkanSample.Launch.Program.Main(String[] args) in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 1178

# Steps to reproduce
- Platform: Desktop Ubuntu 20.04.2
- Framework Version: .NET 5.0
- API: Vulkan
- API Version: Vulkan 1.0
1. I use VulkanTriangle from Lab directory and I tried but it throws same problem.
I have already installed and latest updated lib files under Ubuntu 20.04

2. Same trying no success. 

Because my display card is AMD Radeon RX 480 8 GB VRAM has Vulkan 1.0 and OpenGL 4.6 - I really don't understand why I have tried. I already tested AmdGpu's rocm and vulkan are already installed.

How do I get successful VulkanTriangle on Ubuntu 20.04.2

**Comment by Perksey** [comment]
This is a problem with the lab application regarding dependency on undefined and undocumented behaviour in our windowing system.

Applications in the Lab folder shouldn’t be relied upon as proper examples, and really shouldn’t be used unless as part of development of the library itself.

Will leave this open as an action item to eventually fix our Lab application.

**Comment by HurricanKai** [comment]
In the lab application the window.Initialize() just has to be moved to above the null check, should be an easy fix.

**Comment by theprotonfactor** [comment]
> In the lab application the window.Initialize() just has to be moved to above the null check, should be an easy fix.

The PR I have open incorporates this fix

**Comment by DeafMan1983** [comment]
Thanks @Perksey and @HurricanKai 
I have moved `_window.Initialize();`
over if statement then I retry but it looks like my display card has Vulkan 1.0.0 and it doesn't support :(

```
Unhandled exception. System.NotSupportedException: Validation layers requested, but not available!
   at VulkanSample.Launch.HelloTriangleApplication.CreateInstance() in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 258
   at VulkanSample.Launch.HelloTriangleApplication.InitVulkan() in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 98
   at VulkanSample.Launch.HelloTriangleApplication.Run() in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 29
   at VulkanSample.Launch.Program.Main(String[] args) in /home/jens/Projects/dotnet/VulkanSample/VulkanSample.Launch/Program.cs:line 1177
```

```
vulkaninfo | grep "AMD"
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
		GPU id 	: 0 (AMD RADV POLARIS10 (ACO))
		GPU id 	: 0 (AMD RADV POLARIS10 (ACO))
		GPU id 	: 0 (AMD RADV POLARIS10 (ACO))
GPU id : 0 (AMD RADV POLARIS10 (ACO)):
			AMD RADV POLARIS10 (ACO) (ID: 0)
		AMD RADV POLARIS10 (ACO) (ID: 0)
			AMD RADV POLARIS10 (ACO) (ID: 0)
	deviceName     = AMD RADV POLARIS10 (ACO)
	VK_AMD_buffer_marker                      : extension revision 1
	VK_AMD_device_coherent_memory             : extension revision 1
	VK_AMD_draw_indirect_count                : extension revision 1
	VK_AMD_gcn_shader                         : extension revision 1
	VK_AMD_memory_overallocation_behavior     : extension revision 1
	VK_AMD_mixed_attachment_samples           : extension revision 1
	VK_AMD_rasterization_order                : extension revision 1
	VK_AMD_shader_ballot                      : extension revision 1
	VK_AMD_shader_core_properties             : extension revision 1
	VK_AMD_shader_core_properties2            : extension revision 1
	VK_AMD_shader_explicit_vertex_parameter   : extension revision 1
	VK_AMD_shader_fragment_mask               : extension revision 1
	VK_AMD_shader_image_load_store_lod        : extension revision 1
	VK_AMD_shader_info                        : extension revision 1
	VK_AMD_shader_trinary_minmax              : extension revision 1
	VK_AMD_texture_gather_bias_lod            : extension revision 1
```

**Comment by HurricanKai** [comment]
That suggests you don't have the Vulkan SDK installed. Change the "EnableValidationLayers" at the top of the file to be equal to false, that should disable that.
But I'd highly suggest installing the Vulkan SDK if you are going to do any vulkan development at all.

**Comment by DeafMan1983** [comment]
I have already tried...
same problem like my last post.

> But I'd highly suggest installing the Vulkan SDK if you are going to do any vulkan development at all.

I installed `libvulkan-dev`
```
sudo apt install -fy libvulkan-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvulkan-dev is already the newest version (1.2.131.2-1).
libvulkan-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by HurricanKai** [comment]
Looking at [The LunarG page](https://vulkan.lunarg.com/sdk/home#linux) you would have to run
```
wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
sudo apt update
sudo apt install vulkan-sdk
```
for Ubuntu 20.04 & Latest SDK

**Comment by DeafMan1983** [comment]
Hey @HurricanKai  Thanks for problem. Now It works fine.

![image](https://user-images.githubusercontent.com/57066679/120362985-f2c53880-c30b-11eb-9351-d23124cac569.png)

Updated SDK works fine! Close now!


Or I need buy new display card?
