### ISSUE TITLE
PhysicalDeviceProperties.DeviceName returns empty. It looks weirdly.

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/Silk.NET#502]
# Summary
PhysicalDeviceProperties.DeviceName can't show in console's line.
Like German C++ developer made DeviceName as his current display card name but in C# nothing.
Link to [Youtube](https://www.youtube.com/watch?v=ZQ7TrcwLgRQ&list=PL58qjcU5nk8uH9mmlASm4SFy1yuPzDAH0&index=9) 

# Steps to reproduce
- Platform: Desktop - Ubuntu 20.04.2
- Framework Version: .NET 5
- API: Vulkan
- API Version: Vulkan 1.0
1. First I did this
I have tried with Fixed with PhysicalDevice* 
but Console doesn't display Propreties's DeviceName
2. Then I did this
And I try with ref attribute
# Comments
Problem with DeviceName doesn't display in console line.
![image](https://user-images.githubusercontent.com/57066679/120614306-6031b000-c457-11eb-87da-ce29210da3c9.png)
Or I try Encoding.UT8.GetString() with propreties.DeviceName
![image](https://user-images.githubusercontent.com/57066679/120618590-83f6f500-c45b-11eb-88ad-d06ee9721def.png)

But nothing shows DeviceName. Has DeviceName issue of latest Vulkan like @HurricanKai or who said. ( I can't remember that. Sorry I am busy to learn Vulkan. ) ?

**Comment by HurricanKai** [comment]
This is a problem with your code. At a glance I've noticed that you're passing `(uint*)amount` but you're probably looking for `&amount`.
The Console.WriteLine is outside the loop, so very likely what's happening is that amount stays zero, and you're basically just printing a null string, as no call to GePhysicalDeviceProperties happens.
This would've been caught by simply stepping through that function with a debugger, and by asking on our discord or via GitHub discussions.

**Comment by DeafMan1983** [comment]
@HurricanKai thanks for explanation! My god it is hard for PhysicalDevice[] is not working that is why I use single and it works fine.
![image](https://user-images.githubusercontent.com/57066679/120627714-3b900500-c464-11eb-83f8-ea9216a8cabb.png)
It resolved. Why does GetString() doesn't like int.MaxValue => Out of memory. That is why I need use byte.MaxValue = It is working. Thank you for helping! I will support for that. If I am successful with Vulkan Development and stay safe, my friends!

**Comment by HurricanKai** [comment]
You don't need `Encoding.ASCII.GetString`, use `SilkMarshal.PtrToString(properties.DeviceName)`
Thank you, stay safe as well
