### ISSUE TITLE
Cannot Construct a Matrix4X4 with swapped near and far plane

### ISSUE THREAD

**Issue by theprotonfactor** [dotnet/Silk.NET#503]
So this isn't necessarily a bug, but it prevents a particular feature from being implemented. Namely Reversed-Z Depth Buffering. In order to implement a reversed depth buffer, one must swap the values of the near and far plane when constructing a projection matrix. When attempting to do so with Matrix4X4.CreatePerspectiveFieldOfView an ArgumentOutOfRangeException is raised. Now, when using a standard depth buffer and/or when doing other operations this is a perfectly legitimate exception.  So, on the one hand I understand why it's there, but some alternative is needed in order to not block the above use case.

Just removing that specific exception clause works and seems to be the simplest option. In that case we simply hope that if a user mistakenly uses a smaller far plane than near plane, rather than intentionally flipping it, that the issue will be self-apparent. The other option is to make some type of method that takes a projection matrix and "reversifies" it. Not sure which is more preferable or if there's another option I'm missing.

**Comment by HurricanKai** [comment]
Thank you for the report. I'll look into this.

**Comment by theprotonfactor** [comment]
@HurricanKai Okay, so after getting some sleep I think I've found a simple way to do this that keeps everyone happy. It implements the feature in an opt-in manner, maintains the existing exception checks and should not break existing code that relies on the API. PR has been opened.

**Comment by theprotonfactor** [comment]
Closed by #504
