### ISSUE TITLE
Problem with BenchmarksDotNet

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/Silk.NET#518]
# Summary
I have problem because Rider said error popup message about BenchmarksDotNet under Linux.

# Steps to reproduce
- Platform: Desktop - Ubuntu 20.04
- Framework Version: .NET Core 3.1.400, .NET 5.0.201,5.0.301
- API: Vulkan 1.2 /OpenGL 4.6
- API Version: Vulkan 1.2/OpenGL 4.5 Core/OpenGLES 3.2
1. It happens It cannot upgrade if I use Rider and It throws error. But I don't know why does it happen with after ./build.sh and hangs longer
2. Use Rider to build and it throws error because BenchmarksDotNet has support _4.8 - But I don't have DotNet 4.8 - But I already installed Mono runtime ( latest version )

# Comments
Can't build with Silk.Net

**Comment by HurricanKai** [comment]
For your purposes, just remove the target framework in there.
But you generally don't need to build the benchmarks if you don't want to run them. So unloading the project in Rider should also work.

**Comment by DeafMan1983** [comment]
Thanks and what is `CreateDefaultContext`?

Ok I will unload it. Thanks!

**Comment by HurricanKai** [comment]
CreateDefaultContext is generated by our source generator. It will be marked as an error in editor, but at compile time it works.

**Comment by DeafMan1983** [comment]
Thank you for explanation! Now I close it.

**Comment by DeafMan1983** [comment]
Now I have problem with CreateDefaultContext
![image](https://user-images.githubusercontent.com/57066679/121657759-f9d50f00-caa0-11eb-9df6-cb395d7b7d2d.png)

I have tried to generate with X11 gen but it looks not working - How do I get success but why does Rider not compile successfully? But for me always errors... I don't understand .... How did you make like magic? I have tried `public partial (type) implementname(....)`
![image](https://user-images.githubusercontent.com/57066679/121658358-87186380-caa1-11eb-891a-18b3d0c4fa0f.png)
But nothing works for me. :(

**Comment by HurricanKai** [comment]
A relatively new .NET SDK is required for the projects to compile. What SDK are you using

**Comment by DeafMan1983** [comment]
I am using Net 5.0 SDK 5.0.301 and Mono 6.12.0.122

**Comment by HurricanKai** [comment]
I'm not sure how mono influences this. Do make sure you have the net5 sdk selected in the rider settings

**Comment by DeafMan1983** [comment]
Still using Net 5.0 Sdk.
![image](https://user-images.githubusercontent.com/57066679/121664780-250f2c80-caa8-11eb-9951-21ff898ef0dd.png)

**Comment by DeafMan1983** [comment]
@HurricanKai 
Please clean up and use current version "net5.0" for all projects of Silk.NET! Remove all unused frameworks! Thanks!
I really hate problem with errors. I have tried no success. I am very disappointed because it can't make my own X11 for Silk.NET

**Comment by HurricanKai** [comment]
If you can check in any changes you made and link to them here, I'll have a look

**Comment by Perksey** [comment]
> Please clean up and use current version "net5.0" for all projects of Silk.NET! Remove all unused frameworks!

.NET 5 can't be used on mobile. We intend to move to .NET 6 only for Silk.NET 3.0.

> I have tried no success. I am very disappointed because it can't make my own X11 for Silk.NET

You've installed the SilkTouch NuGet package right?

---

Also, please stop opening issues. Issues are not the place for questions or discussions like these, discussions are. Going forward please only open an issue once we've confirmed it's a bug via GitHub Discussions.
