### ISSUE TITLE
Formalize when we're allowed to make breaking changes in bindings in a proposal

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#530]

**Comment by HurricanKai** [comment]
I think we just don't? We break when the underlying API breaks.
We can formalize this of course.

**Comment by Perksey** [comment]
I really want the ability to disable overloads if we reasonably think they are just plain wrong and/or are causing issues en masse in our userbase.

So yeah we need to discuss with the working group when a breaking change is allowed in a minor release, and also discuss whether a ABI break (but not API break) is acceptable as well maybe?

**Comment by HurricanKai** [comment]
@Perksey wasn't this part of one of the proposals? Or do you want to further discuss specifically disabling extensions

**Comment by Perksey** [comment]
Yes this can be closed once the proposals PR is merged

**Comment by Perksey** [comment]
...or now I guess
