### ISSUE TITLE
GLTF support

### ISSUE THREAD

**Issue by FaberSanZ** [dotnet/Silk.NET#544]
Hi,  any plans for add GLTF?
My [loader](https://github.com/FaberSanZ/Vultaik/blob/master/Src/Samples/Common/GLTF/Interface.cs) that uses System.Text.Json and an internal generator that I can donate.

**Comment by HurricanKai** [comment]
At the moment we only provide bindings for native libraries, but I actually think it might not be too bad of an idea to have a GLTF parser. @Perksey thoughts?

**Comment by Perksey** [comment]
Stuff like this is something I’d like in the library, I do want to make Silk.NET more of a toolbox and actually be “the one library you’ll need” for graphics applications.

A fully managed model loading library is something I can see being part of the Silk.NET suite, but we’d need to put work into the design to verify that it makes us all happy if we wanted to bring it under our umbrella.

We’ll be having a discussion on utilities like this in the next working group meeting (among other things), where if you’d like we can discuss this with our stakeholders on what role Silk.NET should play (and if utilities like this fits it) if you’d like.

Working group meetings happen at ~7pm BST and we announce the date in Discord (also where the meeting takes place) ahead of time.

**Comment by FaberSanZ** [comment]
Assimp supports importing some data from glTF, I think it is better to keep GLTF as separate library from other formats, [Godot](https://godotengine.org/article/we-should-all-use-gltf-20-export-3d-assets-game-engines)

**Comment by Perksey** [comment]
We will be discussing this in the Working Group meeting on Thursday 5th August at 7pm BST in our Discord server. Feel free to come along and discuss with us.

**Comment by HurricanKai** [comment]
I'm very happy to advocate for this and eventually implement GLFW if no external contributor will :)

**Comment by Perksey** [comment]
Discussed in Working Group meeting Thursday 5th August 7:45pm-7:55pm BST:
- Would gain updates as part of our support schedule
- Not a binding, just another "useful library" (see #496 on our discussions on this) 
- There are concerns for staying up-to-date
    - doesn't change often
- We will always have new standards and libraries to add support, again see #496 for the "where is the line"
    - We just end up exploding the library into lots of maintainable things. 
- There seems to be an official loader
    - potentially not performant (`Newtonsoft.Json` etc)

Consensus:
- **We won't have one in the main library right now, keep it a community project**
- Seriously consider `silk-community` org in a future meeting.

**Comment by Perksey** [comment]
Going to close this off now, thanks for the offer for donating your library! In future meetings we'll be discussing an organisation for community projects which have our seal of approval but neither the Silk.NET team or the .NET Foundation supervise or directly run i.e. we'll recommend them to users and they'll see that we approve of the library, but they won't be bound by our support schedule and won't have the strong backing the Foundation provides.
