### ISSUE TITLE
Investigate Performance Implications of #561

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#562]

**Comment by Perksey** [comment]
Note:
- the tenet labels don't mean anything for any non-3.0 issues, as they are not defined until 3.0.
- all issues should have area labels. we're slippy on this, but if ever we do look at the dotnet issue labeller it needs all the data it can get.

**Comment by HurricanKai** [comment]
I expect no one cares about this, we didn't  have any complaints, so closing this.
