### ISSUE TITLE
Box2D.Center returns bogus values

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#567]
This is due to a BODMAS/BIDMAS/PEMDAS error. Reported by @MatijaBrown:

![image](https://user-images.githubusercontent.com/11160611/128904117-a8193dbe-0f75-47fd-a538-3370477524c0.png)

The same may apply for other boxes. The work is to check over the Box2D and Box3D code and ensure that for `Center` we are using the correct order of operations (i.e. we have brackets). Right now we are doing `Min + (Max / 2)` whereas we need to be doing `(Min + Max) / 2`.

Easy fix, community contribution welcome

**Comment by MatijaBrown** [comment]
if no one's taken this yet, I might as not to cause anyone to waste some time, considering I brought it up.
(Not sure if it's already taken, I'm to stupid for github issues...)
