### ISSUE TITLE
MissingMethodException on OpenAL GetExtension

### ISSUE THREAD

**Issue by LaXiS96** [dotnet/Silk.NET#590]
# Summary
Trying to instantiate any OpenAL extension with `GetExtension<TContextExtension>(Device* device)` results in exceptions like these:
```
Constructor on type 'Silk.NET.OpenAL.Extensions.EXT.Capture' not found.
```
```
Constructor on type 'Silk.NET.OpenAL.Extensions.Enumeration.Enumeration' not found.
```

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 5.0
- API: OpenAL Soft
- API Version: OpenAL v2.7.0, OpenAL.Soft.Native v1.21.1.1

1. Test code:
```
using Silk.NET.OpenAL;
using Silk.NET.OpenAL.Extensions.EXT;

namespace ConsoleApp1
{
    class Program
    {
        static unsafe void Main(string[] args)
        {
            using var alc = ALContext.GetApi(true);

            if (alc.IsExtensionPresent(null, "ALC_EXT_CAPTURE"))
            {
                using var captureApi = alc.GetExtension<Capture>(null);
            }
        }
    }
}

```
2. Exception on `alc.GetExtension<Capture>(null)`

# Comments
In discussion https://github.com/dotnet/Silk.NET/discussions/573 @Perksey included a piece of code where `GetExtension` had an overload with no arguments, but the current version does not include that overload.

**Comment by Perksey** [comment]
Thanks, will look into this in time for Friday's update. By the way, this is an outstanding model bug report - always great when we have all the information and a little minimal reproduction :D
