### ISSUE TITLE
Create a .NET 6 code path for GlobalMemory

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#597]
In .NET 6, new `NativeMemory` APIs were introduced to enable direct access to the underlying C standard library's implementation of `malloc` and `free`. Given we just need pinned memory, we should use this instead of `GC.AllocateUninitializedArray` - using that method can cause heap fragmentation given the pinned object heap is intended for long-lived objects, and our users quite often use SilkMarshal.Alloc and our GlobalMemory APIs for short to medium lived blocks of memory. In C `malloc` is used for just about everything, so we should follow suit.

The work is:
- [ ] Add a `net6.0` target in the [csproj](https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.Core/Silk.NET.Core.csproj#L4)
- [ ] Add a `NativeMemoryPtr` type in [GlobalMemory](https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.Core/Native/GlobalMemory.cs#L181) which mirrors `HGlobal`, except it uses [`NativeMemory`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativememory) to allocate instead
- [ ] In [`GlobalMemory.Free`](https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.Core/Native/GlobalMemory.cs#L121), add a new switch `case` for the new type to free the handle using `NativeMemory.Free`
- [ ] In [`GlobalMemory.Allocate`](https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.Core/Native/GlobalMemory.cs#L162), add a preprocessor branch for `NET6_0` to use `NativeMemoryPtr` as the memory object.

Community contributions welcome.

**Comment by Perksey** [comment]
@HurricanKai before I mark as up-for-grabs, comments?

**Comment by HurricanKai** [comment]
sounds good to me

**Comment by Perksey** [comment]
Will leave this is a community issue, no rush to get this in for 2.8.

**Comment by Perksey** [comment]
Closed by #609
