### ISSUE TITLE
VertexAttribPointer

### ISSUE THREAD

**Issue by courgeon** [dotnet/Silk.NET#606]
# Summary
I think there is an issue with one of the variant of GL.VertexAttribPointer
took me a while to figure out how to bypass the issue

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 5.0
- API: OpenGL
- API Version: OpenGL 4.6 Core

Basically, when I do the following, the attribute is not binded in the shader, all values remains to Zero.

` GL.VertexAttribPointer(location, att_Size, VertexAttribPointerType.Float, false, 0, someOffsetValue );`

but casting the offsetValue to void * makes it work.

` GL.VertexAttribPointer(location, att_Size, VertexAttribPointerType.Float, false, 0, (void*) someOffsetValue );`

Or... Maybe it's something I'm missing. Let me kwow !

Matt

**Comment by Perksey** [comment]
This is a known issue and an issue we can't fix as it's a breaking change, and we're quick to warn users in our Discord server about it as well. We're aware of how ugly it is and how many people it catches out but our hands are tied unfortunately! Hope this helps.

**Comment by courgeon** [comment]
oh ok. I've search the git hub discussion before posting, didn't find any mention of it. Thanks for the reply.
