### ISSUE TITLE
Support dotnet interactive in addition to jupyter

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/Silk.NET#611]
# Summary of feature
Since there is a branch supporting [Jupyter](https://github.com/dotnet/Silk.NET/tree/experiments/jupyter). Perhaps support https://github.com/dotnet/interactive too!

**Comment by HurricanKai** [comment]
That is essentially what that branch does.  Unfortunately, it's very difficult to get this right, the jupyter one works locally, but other stuff doesn't really work.
I'm not sure how to make it work well, the browser environment is very limited and to my knowledge there is no official API to load native symbols

**Comment by Perksey** [comment]
To echo recent discussions in the Discord server, we don't really feel (right now) we can create the interactive experience we want using .NET interactive. The implementation is too restrictive, and we can't create the seamless experience we're after.

Going to close this off for now, perhaps we will experiment with this in the future but there are no plans to productize Jupyter or .NET Interactive support today.
