### ISSUE TITLE
Make Vulkan Pfn* structs disposable to avoid memory leaks

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#614]
BuildTools-generated Pfn\* structures implement IDisposable so that `SilkMarshal.Free` can be called to unpin the delegate and allow the GC to have at it. The Vulkan Pfn\* structures, which are manually written, do not implement this at the moment and cause (very minor) memory leaks.

The work is:
- look at how the Pfn\* structures in one of the other libraries (for example SDL) does it
- make the Pfn\* structures in Vulkan inherit from IDisposable
- implement it
- optionally check OpenXR (and maybe OpenGL) as well

Community contributions welcome.

**Comment by p3t3rix** [comment]
https://github.com/dotnet/Silk.NET/pull/615

**Comment by Perksey** [comment]
Fixed by #615
