### ISSUE TITLE
Remove/Fix Vulkan "out"-binding overloads where pNext structures need to be created

### ISSUE THREAD

**Issue by p3t3rix** [dotnet/Silk.NET#626]
For example:
        public partial void GetPhysicalDeviceMemoryProperties2(PhysicalDevice physicalDevice, out PhysicalDeviceMemoryProperties2 pMemoryProperties);

This overload just does not work because Vulkan expects the struct to have the proper SType property set. Also without specifying a pNext chain, this overload would (even if it worked as expected) do little more than the normal GetPhysicalDeviceMemoryProperties function.

Possible fixes:

1. Removal of these methods
2. Create the structs with the right SType set
3. Find a way to specify a pNext chain (probably in combination with 1)

**Comment by HurricanKai** [comment]
3 is going to be it. I've talked with @Perksey about having something like what Vulkan.hpp does, but it uses templates and idk how we could do that. Probably an interface for pNext supporting structures and then do it that way, well need to figure that out.
For now I think we should mark these as Deprecated + Error as they are invalid.

**Comment by Perksey** [comment]
We haven’t done anything for OpenGL’s overloads, and I don’t think we can here in terms of removals or making these functions induce a compiler error.

We can set the sType to default and possibly introduce a structure chain mechanism in the future. But you have a more than good enough solution for now: pointers.

low priority, will not make 2.9

**Comment by Perksey** [comment]
Ok maybe a fix for this will make 2.9, but the structure chain part of the issue will not. Use pointers for this until we have a better solution.
