### ISSUE TITLE
Android-OpenGLES Demo

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#627]
We should make a demo application (or two) showcasing Silk.NET on Android (and maybe Silk.NET working on an Android touch display).

What these demos actually produce is up to you, but they should be:
- [ ] `examples/OpenGL Demos/AndroidDemo`
- [ ] `examples/OpenGL Demos/AndroidTouchDisplay`

They should use .NET 6 Android as we are soon dropping support for legacy Xamarin.

Community contributions welcome.

**Comment by Perksey** [comment]
@roeyskoe Can you put a comment here so I can assign this to you (so it's clear you've taken this one)?

**Comment by roeyskoe** [comment]
> @roeyskoe Can you put a comment here so I can assign this to you (so it's clear you've taken this one)?

Yes

**Comment by Perksey** [comment]
Thanks.
