### ISSUE TITLE
Create the stencil buffer automatically on SDL

### ISSUE THREAD

**Issue by FloatingBanana** [dotnet/Silk.NET#662]
# Summary
After a lot of research, I found that SDL doesn't create the stencil buffer by default. It took me a while to find that I need to call `Silk.NET.Windowing.Sdl.SdlWindowing.GetExistingApi(window).GLSetAttribute(Silk.NET.SDL.GLattr.GLStencilSize, 8)` before `window.Run()` to make the stencil work.

I think it would save a lot of people time if Silk made that automatically when creating the window. It shouldn't be a problem since GLFW already creates the stencil buffer by default.

# Comments
If you don't like the idea of creating it by default, it could also be when the user sets the `PreferredStencilBufferBits` on the `WindowOptions` object.

**Comment by Perksey** [comment]
#660 should fix the bug wherein PreferredStencilBufferBits doesn't work. We don't have any plans to add any automatic creation of this buffer (platform defaults remain undefined so if you want your window to have something, specify it using a property such as this one)

This fix will be part of 2.10 (releasing Friday). Hope this helps!
