### ISSUE TITLE
Improved Vulkan pNext experience

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#669]
# Summary of feature
We should improve the pNext experience somehow.

Idea that came up in discord: `T SetNext<T>(in T next, out T capture) where T : IPNext, unmanaged` this has the added benefit of allowing us to generate interface groups (ie device feature structs) and make the SetNext method use : IMyGroup instead.

**Comment by thargy** [comment]
See following PR #676 for the current proposals.

**Comment by thargy** [comment]
This is covered by #706

**Comment by Perksey** [comment]
agree
