### ISSUE TITLE
net6.0-android: Java.Interop conflict

### ISSUE THREAD

**Issue by xen2** [dotnet/Silk.NET#681]
# Summary
Referencing `Silk.NET.Windowing` 2.10.0.
Compiling result in following error:
```
1>CSC : error CS1705: Assembly 'Silk.NET.Windowing.Sdl' with identity 'Silk.NET.Windowing.Sdl, Version=2.10.0.0, Culture=neutral, PublicKeyToken=null' uses 'Java.Interop, Version=0.1.2.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
```

# Steps to reproduce
- Platform: Android
- Framework Version: `net6.0-android`
- API: OpenGL

Add following references:
```
    <PackageReference Include="Silk.NET.OpenGL" Version="2.10.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.10.0" />
```

# Comments
If I use 2.9.0, it works fine.
I suspect 2.10.0 was compiled with RC3 which had a bug: https://github.com/xamarin/xamarin-android/issues/6438
Probably, recompiling 2.11.0 with VS2022 RTM might fix the issue.

**Comment by Perksey** [comment]
Yeah, @roeyskoe caught this earlier. It's a shame!

We've merged in our PR to build against RTM now so as an interim solution you could use the experimental feed:
```xml
<Project>
    <PropertyGroup>
        <RestoreSources>https://pkgs.dev.azure.com/UltzOS/061abec9-b10b-4a9b-9c06-aa635c5e74a2/_packaging/7ae6c815-0dc0-4193-bf95-042c360df875/nuget/v3/index.json;$(RestoreSources)</RestoreSources>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Silk.NET.Windowing" Version="2.10.0-build1519.0" />
    </ItemGroup>
</Project>
```

I'll leave this open until we've shipped a version fixing this, not sure yet whether this will have its own out-of-cycle release.
