### ISSUE TITLE
Add a "deep clone" mechanism in Vk/XR

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#697]
In some graphics abstractions or larger engines, it's not uncommon to have the ability to create multiple logical devices. The spin-up time for a `Vk` or `XR` object is pretty crude, and even after that you still need to get back all the function pointers over time.

We should offer the ability to clone an API object such that all of the currently-cached function pointers are cloned into the new object, in addition to other state like the current instance and (for Vulkan) the current device.

Given we recommend one Vk object for each instance-device combo (so we don't need to worry about switching out the function tables), this will help scenarios where for example you have a class which creates the instance, and perhaps has a method to create a class wrapping a logical device. In this scenario:
- the first class would own one Vk object for the instance-no device combo
- the second class would own one Vk object for the instance-device combo
- the method on the first class would create an instance of the second class, and by extension the API object therein: it makes sense to reuse/clone the function pointers we've already gathered when creating the second Vk object.

This is inspired by Stride's usage of Vulkan.

@HurricanKai thoughts?

**Comment by Earthman100** [comment]
Perskey!

**Comment by Perksey** [comment]
Fixed in 2.11.
