### ISSUE TITLE
Add missing DXGI_CREATE_FACTORY_DEBUG

### ISSUE THREAD

**Issue by BMarques** [dotnet/Silk.NET#722]
# Summary of feature
Silk.NET.DXGI is doesn't have the constant/flag DXGI_CREATE_FACTORY_DEBUG. 

# Comments
I have to type by hand the 0x1 which is the value of DXGI_CREATE_FACTORY_DEBUG, it would be nice to be able to just grab it from the DXGI class, like DXGI.CpuAccessNone. 

This is useful to make it easier to pass the correct value to DXGI.GetApi().CreateDXGIFactory2
https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_3/nf-dxgi1_3-createdxgifactory2

**Comment by Perksey** [comment]
Looks like the generator is beyond repair here, so I'd happily accept a contribution which adds this in a manual part (i.e. `DXGI.cs` instead of `DXGI.gen.cs` as a `public const`)
