### ISSUE TITLE
Add a mechanism for getting/setting the clipboard text

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#732]
# Summary of feature
Currently, there is no clean way to get/set the clipboard text from the input API - you end up having to use GLFW and SDL directly which isn't ideal or user friendly.

This issue is to add a gettable and settable property onto `IKeyboard` (probably called `ClipboardText`).

# Comments

The work is:
- [ ] Add a `get`/`set` property onto `IKeyboard` (probably called `ClipboardText`)
- [ ] Implement this in `GlfwKeyboard` using the appropriate [GLFW functions](https://www.glfw.org/docs/3.0/group__clipboard.html) exposed in the [`Glfw`](https://github.com/dotnet/Silk.NET/blob/main/src/Windowing/Silk.NET.GLFW/Glfw.cs) class
- [ ] Implement this in `SdlKeyboard` using the appropriate [SDL functions](https://wiki.libsdl.org/CategoryClipboard) exposed in the [`Sdl`](https://github.com/dotnet/Silk.NET/blob/main/src/Windowing/Silk.NET.SDL/Sdl.gen.cs) class.

If your IDE is running slow, you can make a stripped down solution containing only input projects using `nuke sln --projects input`

Please see [CONTRIBUTING.md](https://github.com/dotnet/Silk.NET/blob/main/CONTRIBUTING.md) for more info on contributing.

Area owner is @ThomasMiz 

# Does this have a proposal?
This is exempt from a proposal as described in the proposals readme.

**Comment by Perksey** [comment]
If you would like to take this issue please leave a comment!

**Comment by Beyley** [comment]
Ill attempt to implement this

**Comment by Perksey** [comment]
Assigned, thanks :)

**Comment by ThomasMiz** [comment]
While checking PR #733 I want to ask, why is this implemented on `IKeyboard`? Why not `IInputContext`, or in the windowing packages on `IWindow`?

**Comment by Perksey** [comment]
This was primarily my call, clipboard is more of a human input thing so it belongs in Input and not Windowing.

But on the `IInputContext` vs `IKeyboard`, either is technically acceptable but I mainly leaned towards the latter as `IInputContext` is mainly just an "owner of input devices". I did briefly consider making an `IClipboard` but that seemed overkill.

**Comment by ThomasMiz** [comment]
Sounds good.

Something to keep in mind with this API though is that if the clipboard contains an image, file or anything that isn't text, the `ClipboardText` property will:
- GLFW: Throw an exception
- SDL: Return an empty string

**Comment by Perksey** [comment]
Ouch. I'm guessing there's nothing we can do about that.

**Comment by ThomasMiz** [comment]
Fixed by #733
