### ISSUE TITLE
The currently bound window platform(s) only support views, instead of windows. Use the view APIs instead.

### ISSUE THREAD

**Issue by NoahGav** [dotnet/Silk.NET#793]
**# Summary**
I want to use Silk.NET for a project, but when I try this simple program:

`using Silk.NET.Windowing;

var options = WindowOptions.Default;
options.Size = new(1280, 720);

var window = Window.Create(options);

window.Load += () => {};
window.Render += deltaTime => {};
window.Closing += () => {};

window.Run();`

I get this error:

> An unhandled exception of type 'System.NotSupportedException' occurred in Silk.NET.Windowing.Common.dll: 'The currently bound window platform(s) only support views, instead of windows. Use the view APIs instead.'
>    at Silk.NET.Windowing.Window.Create(WindowOptions options)
>    at Program.<Main>$(String[] args) in ...

**# Steps to reproduce**
- Platform: Pop OS, 20.04 LTS
- Framework Version: .NET 6
- API: Windowing

1. In vscode I ran 'dotnet new console'.
2. Then I ran 'dotnet add package Silk.NET --version 2.12.0'
3. Then I added the code above and ran it with F5.

**Comment by Perksey** [comment]
https://github.com/dotnet/Silk.NET/blob/main/website/docs/hlu/troubleshooting.md

(the table on the actual website is borked, so just read directly from GitHub)

**Comment by Perksey** [comment]
> Pop OS, 20.04 LTS

Just seen this, try installing GLFW. I have no idea how to do this on Pop OS, but the package name is probably something like `libglfw` or `libglfw3`

**Comment by NoahGav** [comment]
@Perksey Thank you. I don't know why this is, but libglfw.so.3 was already in runtimes/linux-x64/native, but when I copied it from /usr/lib/x86_64-linux-gnu it fixed the issue.

**Comment by Perksey** [comment]
Glad to hear this is resolved.
