### ISSUE TITLE
Silk.NET.Direct3D11.ID3D10Blob Missing Methods

### ISSUE THREAD

**Issue by Syncaidius** [dotnet/Silk.NET#811]
Hi,

The Silk.NET.Direct3D11.ID3D10Blob structure appears to be missing these two methods:

- [ID3D10Blob::GetBufferPointer](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nf-d3dcommon-id3d10blob-getbufferpointer)
- [ID3D10Blob::GetBufferSize](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nf-d3dcommon-id3d10blob-getbuffersize)

The struct itself contains nothing:
![image](https://user-images.githubusercontent.com/2464215/154206034-c62f598f-3ac2-4dd0-804b-0dd9e7ad1544.png)

EDIT: The workaround for this seems to be to use IDxcBlob for now, [as it is an alias of ID3D10Blob](https://github.com/microsoft/DirectXShaderCompiler/blob/9f60094d90bb2cc8b5997ad8a9b8ff777f8d7a0b/include/dxc/dxcapi.h#L148). However, I don't think this is a safe workaround given that Microsoft may change IDxcBlob structure/functionality later down the line and diverge from ID3D10Blob.

**Comment by Perksey** [comment]
Hi there. `ID3D10Blob` is in `Silk.NET.Core.Native` - unfortunate that it seems to have lit up in D3D11 as well. Will look at removing that as that's a bit of a binding bug.

https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.Core/Native/Structs/ID3D10Blob.gen.cs

**Comment by Syncaidius** [comment]
Hi Perksey, That's brilliant. Thanks for the really quick response and solution.
