### ISSUE TITLE
Direct2D/DirectWrite/WIC support?

### ISSUE THREAD

**Issue by sdcb** [dotnet/Silk.NET#813]
# Summary of feature
Silk.NET should have Direct2D/DirectWrite/WIC support.

 - [x] Direct2D (#1000)
 - [x] DirectWrite (introduced in #1349 and reworked in #1341)
 - [ ] WIC

# Does this have a proposal?
Hope it will be in 3.0

These can be related:
https://github.com/dotnet/Silk.NET/issues/808
https://github.com/dotnet/Silk.NET/discussions/809

**Comment by Perksey** [comment]
cc @Beyley

**Comment by Beyley** [comment]
D2D is [already in master](https://github.com/dotnet/Silk.NET/tree/main/src/Microsoft/Silk.NET.Direct2D), so all that needs to happen is [DirectWrite](https://learn.microsoft.com/en-us/windows/win32/api/dwrite/) and [WIC](https://learn.microsoft.com/en-us/windows/win32/wic/-wic-api) although ive never used either of these APIs so im not sure whether theres anything specific to take into account relating to what headers should go where

**Comment by hez2010** [comment]
Any updates to the WIC part?

**Comment by Beyley** [comment]
> Any updates to the WIC part?

Nothing right now, we'd love to accept any contributions in this area though!
