### ISSUE TITLE
Error when listing DXGI outputs with .NET 5.0

### ISSUE THREAD

**Issue by gofr3** [dotnet/Silk.NET#817]
Hi,

I'm trying to use DXGI in a .NET 5.0 project but it fails when listing adapters' outputs (while the same code is working fine with .NET 4.8).

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 5.0
- API: DXGI

I tried the following code:
```cs
Guid factory1Guid = IDXGIFactory1.Guid;

DXGI dXGIApi = DXGI.GetApi();

IDXGIFactory1* dXGIFactory1 = null;
IDXGIAdapter1* dXGIAdapter1 = null;
IDXGIOutput* dXGIOutput = null;

SilkMarshal.ThrowHResult(dXGIApi.CreateDXGIFactory1(ref factory1Guid, (void**)&dXGIFactory1));

// Adapter with index 0 should be the one with the output on which the primary desktop is displayed.
SilkMarshal.ThrowHResult(dXGIFactory1->EnumAdapters1(0, &dXGIAdapter1));

AdapterDesc1 adapterDesc = default(AdapterDesc1);
SilkMarshal.ThrowHResult(dXGIAdapter1->GetDesc1(&adapterDesc));

// Get the first output (with index 0) of the adapter, it should be the one on which the primary desktop is displayed.
SilkMarshal.ThrowHResult(dXGIAdapter1->EnumOutputs(0, &dXGIOutput));
```
The last line throws an error DXGI_ERROR_NOT_FOUND (0x887A0002).
The same code works fine with .NET 4.8.

## Additional comments
I went through the code and saw the main difference between .NET 4.8 / and .NET 5.0 is that the calling convention is omitted in the case of .NET 5+:
```cs
        public readonly unsafe int EnumOutputs(uint Output, IDXGIOutput** ppOutput)
        {
            var @this = (IDXGIAdapter1*) Unsafe.AsPointer(ref Unsafe.AsRef(in this));
            int ret = default;
            #if NET5_0_OR_GREATER
            ret = ((delegate* unmanaged<IDXGIAdapter1*, uint, IDXGIOutput**, int>)LpVtbl[7])(@this, Output, ppOutput);
            #else
            if (SilkMarshal.IsWinapiStdcall)
            {
                ret = ((delegate* unmanaged[Stdcall]<IDXGIAdapter1*, uint, IDXGIOutput**, int>)LpVtbl[7])(@this, Output, ppOutput);
            }
            else
            {
                ret = ((delegate* unmanaged[Cdecl]<IDXGIAdapter1*, uint, IDXGIOutput**, int>)LpVtbl[7])(@this, Output, ppOutput);
            }
            #endif
            return ret;
        }
```
As per my understanding, this will cause the calling convention to be defined at runtime depending on the platform the code is running on. But is there additional configuration / settings required for that?

The adapter returned for index 0 is different in .NET 5.0 / 4.8 while I would have have expected to receive the same adapter in both cases as the doc specifies that adapter 0 is the one with the output on which the primary desktop is displayed. But I'm not sure it is significant.  As a side note, I tried listing the outputs of other adapters and it fails as well.

Thanks in advance!

**Comment by Perksey** [comment]
Oh and by the way this is the most interesting bug report we've had in a while, so thanks(?) for that! :D

**Comment by Perksey** [comment]
One other idea: try .NET Core 3.1 as well to see if the bug reproduces there. If it doesn't, then I'll ping in a runtime god.

**Comment by gofr3** [comment]
Hi,

Thank you for your help and sorry for the late reply. I tried to enable the info queue output but it does return any message. I also tried with .NET core 3.1 and I confirm I can also reproduce the bug with it.

Thanks.

**Comment by Perksey** [comment]
Ok last resort time… @tannergooding (sorry) any ideas why we’d be getting differences between an unmanaged func pointer and our fudged fallback mechanism (see issue description)? Thanks for any help.

**Comment by tannergooding** [comment]
Not sure. Just for comparison, could you try to run the following code? I'd like to just get a quick sample on if this is something potentially wrong with TerraFX vs something with Silk.NET vs something with ClangSharp.

### Example.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.22000-rc1" />
  </ItemGroup>

</Project>
```

### Program.cs

```csharp
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using TerraFX.Interop.DirectX;
using TerraFX.Interop.Windows;
using static TerraFX.Interop.DirectX.DirectX;
using static TerraFX.Interop.Windows.Windows;

unsafe
{
    IDXGIFactory1* dxgiFactory1;
    ThrowIfFailed(CreateDXGIFactory1(__uuidof<IDXGIFactory1>(), (void**)&dxgiFactory1));

    IDXGIAdapter1* dxgiAdapter1;
    ThrowIfFailed(dxgiFactory1->EnumAdapters1(0, &dxgiAdapter1));

    DXGI_ADAPTER_DESC1 dxgiAdapterDesc;
    ThrowIfFailed(dxgiAdapter1->GetDesc1(&dxgiAdapterDesc));

    Console.WriteLine($"AdapterLuid: {dxgiAdapterDesc.AdapterLuid.HighPart:X8}{dxgiAdapterDesc.AdapterLuid.LowPart:X8}");
    Console.WriteLine($"Description: {MemoryMarshal.CreateReadOnlySpanFromNullTerminated((char*)dxgiAdapterDesc.Description)}");
    Console.WriteLine($"DeviceId: {dxgiAdapterDesc.DeviceId}");
    Console.WriteLine($"Revision: {dxgiAdapterDesc.Revision}");
    Console.WriteLine($"SubSysId: {dxgiAdapterDesc.SubSysId}");
    Console.WriteLine($"VendorId: {dxgiAdapterDesc.VendorId}");
    Console.WriteLine();

    IDXGIOutput* dxgiOutput;
    ThrowIfFailed(dxgiAdapter1->EnumOutputs(0, &dxgiOutput));

    DXGI_OUTPUT_DESC dxgiOutputDesc;
    ThrowIfFailed(dxgiOutput->GetDesc(&dxgiOutputDesc));

    Console.WriteLine($"DeviceName: {MemoryMarshal.CreateReadOnlySpanFromNullTerminated((char*)dxgiOutputDesc.DeviceName)}");
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static void ThrowIfFailed(HRESULT value, [CallerArgumentExpression("value")] string? valueExpression = null)
{
    if (value.FAILED)
    {
        ThrowExternalException(valueExpression ?? "Method", value);
    }
}

[DoesNotReturn]
static void ThrowExternalException(string methodName, int errorCode)
{
    var message = string.Format("'{0}' failed with an error code of '{1}'", methodName, errorCode);
    throw new ExternalException(message, errorCode);
}
```

**Comment by tannergooding** [comment]
For reference, when compared to the following:

### Example.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.DXGI" Version="2.13.0" />
  </ItemGroup>

</Project>
```

### Program.cs

```csharp
using Silk.NET.Core.Native;
using Silk.NET.DXGI;
using System.Runtime.InteropServices;

unsafe
{
    Guid factory1Guid = IDXGIFactory1.Guid;

    DXGI dxgiApi = DXGI.GetApi();

    IDXGIFactory1* dxgiFactory1 = null;
    IDXGIAdapter1* dxgiAdapter1 = null;
    IDXGIOutput* dxgiOutput = null;

    SilkMarshal.ThrowHResult(dxgiApi.CreateDXGIFactory1(ref factory1Guid, (void**)&dxgiFactory1));

    // Adapter with index 0 should be the one with the output on which the primary desktop is displayed.
    SilkMarshal.ThrowHResult(dxgiFactory1->EnumAdapters1(0, &dxgiAdapter1));

    AdapterDesc1 dxgiAdapterDesc = default(AdapterDesc1);
    SilkMarshal.ThrowHResult(dxgiAdapter1->GetDesc1(&dxgiAdapterDesc));

    Console.WriteLine($"AdapterLuid: {dxgiAdapterDesc.AdapterLuid.High:X8}{dxgiAdapterDesc.AdapterLuid.Low:X8}");
    Console.WriteLine($"Description: {MemoryMarshal.CreateReadOnlySpanFromNullTerminated((char*)dxgiAdapterDesc.Description)}");
    Console.WriteLine($"DeviceId: {dxgiAdapterDesc.DeviceId}");
    Console.WriteLine($"Revision: {dxgiAdapterDesc.Revision}");
    Console.WriteLine($"SubSysId: {dxgiAdapterDesc.SubSysId}");
    Console.WriteLine($"VendorId: {dxgiAdapterDesc.VendorId}");
    Console.WriteLine();

    // Get the first output (with index 0) of the adapter, it should be the one on which the primary desktop is displayed.
    SilkMarshal.ThrowHResult(dxgiAdapter1->EnumOutputs(0, &dxgiOutput));

    OutputDesc dxgiOutputDesc;
    SilkMarshal.ThrowHResult(dxgiOutput->GetDesc(&dxgiOutputDesc));

    Console.WriteLine($"DeviceName: {MemoryMarshal.CreateReadOnlySpanFromNullTerminated((char*)dxgiOutputDesc.DeviceName)}");
}
```

**Comment by tannergooding** [comment]
I get the same output on both for the boxes I've tested on.

```
AdapterLuid: 0000000000011564
Description: AMD Radeon RX 6900 XT
DeviceId: 29631
Revision: 192
SubSysId: 3828882850
VendorId: 4098

DeviceName: \\.\DISPLAY1
```

**Comment by tannergooding** [comment]
Likewise seeing the same on net5.0 and net48

**Comment by Perksey** [comment]
@gofr3 for our reference (not sure if you’ve put it anywhere else) are you using ARM or x86? And 32-bit or 64-bit?

I can’t think of anything we’re doing wrong, our signatures look to be correct and our .NET 5 path will do the same as our !.NET 5 path on the most popular platforms.

**Comment by gofr3** [comment]
Hi @tannergooding and @Perksey ,

Thanks again for your help. I tried the TerraFx vs Silk code and both return the same adapter before throwing an exception on the line listing the outputs:
```
AdapterLuid: 000000000001B3C9
Description: AMD FirePro S7100X
DeviceId: 26921
Revision: 1
SubSysId: 184553474
VendorId: 4098
```

I also tried the same code on .NET 4.8 and it returns:
```
AdapterLuid: 000000000001BB92
Description: Microsoft Basic Render Driver
DeviceId: 140
Revision: 0
SubSysId: 0
VendorId: 5140
```

As this is a really weird problem, I tried the same thing on a different machine and it worked... The machine on which it fails is a bit special as it is accessed over citrix and maybe this does not play well with the Direct X libraries. I just don't understand why it works with 4.8 and not with .NET 5 / .NET 6 but anyway, if it works on a "normal" setup then it is not a Silk.NET issue. Sorry for the false alarm and thanks again for your quick support.

**Comment by Perksey** [comment]
Ah in that case at a guess your GPU driver on your Citrix machine is faulty, and for whatever reason the .NET Framework one is defaulting to the software driver? In any case, doesn't look like this is our issue!

**Comment by tannergooding** [comment]
It may he a difference in 32-bit vs 64-bit process.

You should be able to add a `Console.WriteLine(Environment.Is64BitProcess)` to see if net48 vs net6.0 differ here.

I'd expect that net48 is targeting 32-bit by default and that net3.1/net5.0/net6.0 are targeting 64-bit

**Comment by Perksey** [comment]
Having not heard anything further, I shall close this as user-specific. I don't think there's any Silk bug here!
