### ISSUE TITLE
Xbox Series S gamepad not properly detected

### ISSUE THREAD

**Issue by usertoroot** [dotnet/Silk.NET#856]
# Summary
Xbox Series S gamepad not properly detected, it is seen as Joystick instead of Gamepad.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 6
- GLFW backend

1. Make a basic GLFW window and try to use the Xbox Series S gamepad on Linux.

# Comments
1. Is this an issue on windows?
2. I checked `Silk.NET.GLFW.Glfw.GetGamepadState`, this returned false for the gamepad.
3. I searched around for issues on GLFW related to this but could not find it directly.

# Possible causes
1. Outdated GLFW library?
2. GLFW library does not support this gamepad

# Possible solutions
1. Updated GLFW library
2. Standard implementation of the `gamecontrollerdb.txt` that seems to be floating around various communities supporting many gamepads. Should be loadable via `Silk.NET.GLFW.Glfw.UpdateGamepadMappings`.

Does anybody have any additional ideas that could help with fixing this issue?

**Comment by Perksey** [comment]
Likely an issue with your drivers or GLFW.

**Comment by Perksey** [comment]
Closing due to no response from user, and unlikely to be a Silk.NET bug (rather a native binary bug). User is also using Linux which could be a GLFW version issue. But yeah, no evidence that this is our bug.
