### ISSUE TITLE
[Question] compile and run the opengl and imgui examples

### ISSUE THREAD

**Issue by LuisMerinoP** [dotnet/Silk.NET#876]
Hi there,

I am not familiar with the use of a such a big library and the nuke tool, so apologies for the question if its obvious.
I followed the readme instructions, but finding the next error when doing the `nuke compile` command from the powershell:

`[ERR] Restore: C:\Program Files\dotnet\sdk\6.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: para compilar este proyecto, deben estar instaladas las siguientes cargas de trabajo: ios [<RestOfMyFullPath>\Silk.NET\src\Windowing\Silk.NET.Windowing.Sdl\Silk.NET.Windowing.Sdl.csproj]`

I tried to install the [Silk.NET.Windowing](https://www.nuget.org/packages/Silk.NET.Windowing/) nuget package everywhere, in the source, and in the `src/Windowing` project, but did not achieve to install it. Dont know where exactly I would need to install it as there are many windowing projects in  `src/Windowing`.

On the other hand my main interest is to run the imgui and the opengl examples, so I tried to specifuically build those with the commands shouwn in the [contributing.md](https://github.com/dotnet/Silk.NET/blob/main/CONTRIBUTING.md). 

I did `nuke sln --projects opengl silk.net.vulkan core.win32extras "opengl tutorials" build`
The Silk.NET.gen.sln seems to be generated correctly, but if opened I get among other errors:
[NuGet Error NU1012](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1012?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1012)%26rd%3Dtrue). Seems to be related to android.
[MSB4018: The task failed unexpectedly](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb4018?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.FatalTaskError)%26rd%3Dtrue&view=vs-2022)

As the main `nuke compile` fails, then the specific project building failing might be just a consequence of that.
Any guidance or maybe a little more detailed documentation to make this work would be much appreciated.
Thanks a lot in advanced.

**Comment by roeyskoe** [comment]
That `NETSDK1147` error seems to indicate that you are missing ´ios´ workload. 

Have you installed all of the required workloads?
`dotnet workload install android android-aot ios maui`

**Comment by LuisMerinoP** [comment]
(thught I did that already) Workload id is not recognized in the powershell console. In spanish: `No se reconoce el id. de carga de trabajo android-aot`.

Should [android studio](https://developer.android.com/studio) or [SDK Platform Tools](https://developer.android.com/studio/releases/platform-tools) be installed?

Thanks in advanced

**Comment by LuisMerinoP** [comment]
I also did:

`dotnet workload install maui` and mani projects seem to be restored in the logs, but now I get this error:

`[ERR] Compile: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.Tooling.targets(69,5): error XA5300: No se encontró el directorio de Android SDK. Debe establecerse a través de /p:AndroidSdkDirectory. [<RestOfMyFullPath>\Silk.NET\src\Windowing\Silk.NET.Windowing.Sdl\Silk.NET.Windowing.Sdl.csproj]` 

Seems also related to windowing. 
Y installed android studio just in case, but same.

**Comment by LuisMerinoP** [comment]
thanks for your answer, let me try later in some hours and let you know if that works

**Comment by LuisMerinoP** [comment]
thanks for your answer, let me try later in some hours and'll let you know if that works. Hoever, is that the same as opening Something.csproj and eight-click + build¿¿??.

**Comment by LuisMerinoP** [comment]
Building the specific project from the powershell works! 
`dotnet build ./path/to/Something.csproj`

**Comment by LuisMerinoP** [comment]
Do not know what was happenning before, as I tried right clicking + build to run the app all of the time. 

So after cloning the whole repo, just building and running the respective `csproj` should work or there is something else that needs to be done?? In either case that might be a useful info to include in the readme for a newbie newcomer as myself. 
Thanks for this awesome library, for any comment regarding the question and for your support!
