### ISSUE TITLE
Garbage collector collecting, in empty project only window open

### ISSUE THREAD

**Issue by Kekwleon** [dotnet/Silk.NET#903]
I have no clue, if thats an issue or not. just very annoying  in visual studio profiler pops up very often.(the yellow arrow)

New Project, install via nuget command : Install-Package Silk.NET -Version 2.15.0
and pasted "hello window" code in.

**Comment by Beyley** [comment]
> I have no clue, if thats an issue or not. just very annoying in visual studio profiler pops up very often.(the yellow arrow)
> 
> New Project, install via nuget command : Install-Package Silk.NET -Version 2.15.0 and pasted "hello window" code in.

can you see what its collecting?

**Comment by Kekwleon** [comment]
something called "signature" native event runtime source. sorry very not much knowlegde , about this stuff, what im looking for

**Comment by Kekwleon** [comment]
issue found ,it was a me problem sorry :< my small laptop could not handle too much apps open at once. and triggered propably the gc.
