### ISSUE TITLE
Silk.Net.Assimp read Indices wrong

### ISSUE THREAD

**Issue by JasShao** [dotnet/Silk.NET#929]
I try to load model with Silk.Net.Assimp (NuGet 2.15.0) . 
```
Scene* scene = assimp.ImportFile(file, (uint)(PostProcessSteps.Triangulate | PostProcessSteps.GenerateSmoothNormals | PostProcessSteps.FlipUVs|PostProcessSteps.CalculateTangentSpace));

...

 for (int i = 0; i < mesh->MNumFaces; i++)
  {
      Face face = mesh->MFaces[i];
      for (int j = 0; j < face.MNumIndices; j++)
      {
          indices.Add( face.MIndices[j]);
      }  
  }
```
When I get index within scene->mesh->face->MIndices , I found the data in MIndices array is [0,1,3,4,5,6.....999] .

model : [backpack.zip](https://github.com/dotnet/Silk.NET/files/8760282/backpack.zip)

**Comment by Perksey** [comment]
I genuinely don't believe Silk.NET is doing wrong, please ensure GitHub Discussions are used for questions - the issue tracker is primarily used for bugs we know are caused by Silk.NET themselves!

**Comment by Redhacker1** [comment]
This is how I read indices... and I have not currently experienced the bug, that being said I can try his model real quick and see if it's something done wrong there.

`
                if (CurrentMesh.MFaces != null && CurrentMesh.MNumFaces > 0)
                {
                    ManagedMesh.Indices = new uint[CurrentMesh.MNumFaces][];

                    for (int FaceIndex = 0; FaceIndex < CurrentMesh.MNumFaces; FaceIndex++)
                    {
                        Face CurrentFace = CurrentMesh.MFaces[FaceIndex];

                        ManagedMesh.Indices[FaceIndex] = new uint[CurrentFace.MNumIndices];
                        UnmanagedToManagedCopy(CurrentFace.MIndices, CurrentFace.MNumIndices,
                            ManagedMesh.Indices[FaceIndex]);
                    }
                    ManagedMesh.HasFaces = true;
                }
`

The contents of Unmanaged to managed copy are as follows:
`        
static unsafe bool UnmanagedToManagedCopy<T>(T* source, uint length, Span<T> destination) where T: unmanaged
        {
            if (destination.Length <= length && source != null)
            {
                fixed (void* pDest = destination)
                {
                    Unsafe.CopyBlock(pDest, source, (uint) (length * sizeof(T)));
                }
                return true;
            }
            return false;
        }
`

**Comment by Redhacker1** [comment]
![image](https://user-images.githubusercontent.com/66490743/170079014-35b2d9e4-b794-4c05-9acc-5397da55265c.png)
does this look correct to you, aside from textures?

**Comment by JasShao** [comment]
> ![image](https://user-images.githubusercontent.com/66490743/170079014-35b2d9e4-b794-4c05-9acc-5397da55265c.png) does this look correct to you, aside from textures?

Yes. I will try again. Thank you.
