### ISSUE TITLE
Can I use this repo to get audio file duration without playing it?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnet/Silk.NET#932]
Hello:
I have one audio file: C:\1.mp3.
I want to know the duration of the audio file, usually I have to play the audio file, then I can see its duration.
But can I use this repo to get the audio file duration (in seconds) without playing it?
I am using Windows 10 (Version 21H2), and my IDE is Visual Studio 2022.
Please advise, 
Thanks,

**Comment by Beyley** [comment]
> Hello: I have one audio file: C:\1.mp3. I want to know the duration of the audio file, usually I have to play the audio file, then I can see its duration. But can I use this repo to get the audio file duration (in seconds) without playing it? I am using Windows 10 (Version 21H2), and my IDE is Visual Studio 2022. Please advise, Thanks,

Depends on your needs, id recommend looking into the mp3 file format specification and writing your own parser for the format

**Comment by zydjohnHotmail** [comment]
Hi,
Do you have an example for mp3 file parser using the repo?

**Comment by Beyley** [comment]
> Hi, Do you have an example for mp3 file parser using the repo?

Silk does not provide an mp3 parser, and since you just want to get the length and not play it, Silk wont be much help here

**Comment by Beyley** [comment]
> Hi, I can use .aac format of audio file, do you have parser for this format of audio file?

Not on hand no, we only have an example parser for .wav, and even then we dont read the length

**Comment by ohtrobinson** [comment]
Unless I am mistaken, Silk does not provide any parsers. It's up to you to create them for use with OpenAL, etc.
The easiest thing to parse is a wav file, if you wish to build a parser yourself.
However with a wav file you can calculate its length by just using its file size (usually).

**Comment by zydjohnHotmail** [comment]
OK, thanks!

**Comment by zydjohnHotmail** [comment]
Hello:
Interesting, do you have any formular that I can get its duration from its size.
For example, I have one .wav file, its size is: 210KB. 
Then usually, how many seconds this audio (.wav) file will last?
Do you have any suggestion on how to find such formular?
Thanks,

**Comment by Beyley** [comment]
> Hello: Interesting, do you have any formular that I can get its duration from its size. For example, I have one .wav file, its size is: 210KB. Then usually, how many seconds this audio (.wav) file will last? Do you have any suggestion on how to find such formular? Thanks,

You'll have to read the file for the sample rate and amount of channels and bit width and a lot of other factors before being able to calculate

**Comment by zydjohnHotmail** [comment]
Hello:
I used C# system.speech.Synthesis to generate a wav file, the following is the C# code:
synth.SetOutputToWaveFile(@"C:\temp\test.wav",   
          new SpeechAudioFormatInfo(32000, AudioBitsPerSample.Sixteen, AudioChannel.Mono));  
If the generated wav file size is 210KB using the above parameter, then how do you calcuate its duration?
What formular you can use from the above parameters?
Do you need more information?
Thanks,

**Comment by ohtrobinson** [comment]
In this case, you would do `210000 / (32000 * 2)` to get a length of around 3 and a quarter seconds.

To calculate, it's `File size in bytes / (Sample rate * Number of Channels * (Bits per sample / 8))`.

Of course, as Beyley said before, if you want to get this from any wav file you will need to read the file to get those values.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your calculation.
I will do more testing to make sure the formular works.
By the way, if I use the same C# code, but I generate mp3 or aac format audio file, the formular still works or not.  I use the same C# code to generate audio files in wav, mp3 and aac files, their sizes are quite similar, mp3 has the biggest size, aac is middle, wav is the smallest.
Thanks,

**Comment by ohtrobinson** [comment]
It won't work for compressed files such as mp3 or aac, or even compressed wav files. The only time the calculation will work is if you have uncompressed PCM data.

**Comment by zydjohnHotmail** [comment]
OK, 
Thanks!
