### ISSUE TITLE
Adding FlagsAttribute for various OpenGL Mask enums

### ISSUE THREAD

**Issue by Khitiara** [dotnet/Silk.NET#950]
A number of OpenGL enums for specific overloads (rather than using GLEnum for literally everything) lack FlagsAttribute and thus give the ReSharper inspection BitwiseOperatorOnEnumWithoutFlags (see also #729)
The following are relevant to my uses but others may be affected:
- BufferStorageMask
- ClearBufferMask
- MapBufferAccessMask

**Comment by Perksey** [comment]
cc @Beyley easy one to fix, just need to apply this code https://github.com/dotnet/Silk.NET/blob/main/src/Core/Silk.NET.BuildTools/Cpp/Clang.cs#L51 on non-clang paths as well

**Comment by Beyley** [comment]
Closed by #1251 

Fixed specifically in [this commit](https://github.com/dotnet/Silk.NET/pull/1251/commits/8cc98e8e6a97466d4fdc92d09a4d00ef0fb797de) (?)
