### ISSUE TITLE
System.PlatformNotSupportedException on kde neon

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/Silk.NET#951]
# Summary
A summary of the issue you're experiencing.

# Steps to reproduce
- Platform: KDE neon 5.24
- Framework Version: .NET 6.0
- API: OpenGL
- API Version:  OpenGL Default
1. I made a .net 6.0 library
2. Then I coded this.. https://gist.github.com/Shadowblitz16/71cae6750fe29e8bce85ae654101f644
3. Then I switched my app to be a console app
4. Then I ran it and got this...
```
Unhandled exception. System.PlatformNotSupportedException: Couldn't find a suitable window platform. (GlfwPlatform - not applicable, SdlPlatform - not applicable) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at TinyEngine.Program.Main(String[] args) in /home/shadowblitz16/Documents/dev/C#/TinyEngine/TinyEngine/Program.cs:line 18
```
# Comments
Raylib-cs works fine which uses OpenGL too.

**Comment by Beyley** [comment]
Try installing the GLFW package from your package manager

**Comment by Shadowblitz16** [comment]
> Try installing the GLFW package from your package manager

I think raylib uses glfw and it works fine.
I can try though.

**Comment by Shadowblitz16** [comment]
Installing `libglfw3` by doing `sudo apt-get install libglfw3` worked.
