### ISSUE TITLE
Silk.Net does not working in single-file mode

### ISSUE THREAD

**Issue by kant2002** [dotnet/Silk.NET#958]
Based on my experimentation with NativeAOT and https://github.com/dotnet/runtime/issues/70438 I think dependency on DependencyModel cause problems with single-file mode. 

Is there interest to make Silk.NET work in that single-file and NativeAOT scenarios? If users of lib write games, maybe small self-contained size interested for them.

**Comment by Perksey** [comment]
Can you send a specific error? Silk.NET to our knowledge works fine on NativeAOT with the potential caveat of having to bring your own DLLs (but even that might be fine, don’t remember how the SDK handles that)

**Comment by kant2002** [comment]
I submit Pr. It was simply dependency update. And technically issue was in old version of DependecyModel
