### ISSUE TITLE
Legacy opengl cause GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by sandsc** [dotnet/Silk.NET#966]
use `glBegin glVertex glEnd` cause "GL_INVALID_OPERATION error generated. Calling glFlush from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs." message is outputed by gldebugmessagecallback,
it seems that when calls `glVertex` `wglGetProcAddress` will be called which calls `glFlush` implicitly on windows.

 see also:  
> The basic problem is Microsoft's opengl32.dll calls glFlush from wglGetProcAddress()  
 https://github.com/haskell-opengl/OpenGL/issues/87

**Comment by Redhacker1** [comment]
I happen to agree. Legacy OpenGL should IMHO probably stop actually being supported or bindings generated for it.

**Comment by Beyley** [comment]
> I happen to agree. Legacy OpenGL should IMHO probably stop actually being supported or bindings generated for it if possible

I dont think we should cut support for something in 2.x because one platform has issues with it
