### ISSUE TITLE
WindowOptions.ShouldSwapAutomatically enabled by default

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#967]
# Summary
As tradition with OpenGL, one swaps their own buffers when they are ready. Manual swapping has always been a thing. The fact that it was defaulted to true threw me off when I went to go swap the buffers, making the clicking of the Title bar making this unexpected and easily unintended behavior.

# Steps to reproduce
- Platform: Windows 10 Desktop
- Framework Version: .NET Core 6.0
- API: OpenGL
- API Version: OpenGL 4.6 Core Forward Compatible
See code: https://pastebin.com/uEgCdBBA

# Comments
I propose to have ShouldSwapAutomatically default to off.

**Comment by Beyley** [comment]
> # Summary
> 
> As tradition with OpenGL, one swaps their own buffers when they are ready. Manual swapping has always been a thing. The fact that it was defaulted to true threw me off when I went to go swap the buffers, making the clicking of the Title bar making this unexpected and easily unintended behavior.
> # Steps to reproduce
> 
>     * Platform: Windows 10 Desktop
> 
>     * Framework Version: .NET Core 6.0
> 
>     * API: OpenGL
> 
>     * API Version: OpenGL 4.6 Core Forward Compatible
>       See code: https://pastebin.com/uEgCdBBA
> 
> 
> # Comments
> 
> I propose to have ShouldSwapAutomatically default to off.

2.x wont have any breaking changes at this stage

**Comment by Perksey** [comment]
It’s worth noting when designing Silk.NET we made this choice because we found a lot of beginners confused that their window was blank despite having all of their rendering code written.

But yeah as Beyley said 2.X isn’t having any intentionally breaking changes.
