### ISSUE TITLE
IsVisible not retained on window creation

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#968]
# Summary
I think this is a regression of #66

When the below code is ran with IsVisible = false, the window still appears. I figured the window didn't get created until after OnLoad (so I added IsVisible to OnLoad) or there was a Hide and Show function, but I was surely wrong when the window appeared, then subsequently disappeared.

```C#
public static void Main(string[] args)
{
	
	GraphicsAPI capi = new GraphicsAPI(
		ContextAPI.OpenGL,
		ContextProfile.Core,
		ContextFlags.ForwardCompatible,
		new APIVersion(4, 6)
		);
		
	WindowOptions wo = WindowOptions.Default;
	wo.IsVisible = false;
	wo.Size = new Vector2D<int>(800, 600);
	wo.Title = "OpenGL";
	wo.FramesPerSecond = 120;
	wo.UpdatesPerSecond = 120;
	wo.IsEventDriven = true;
	wo.Samples = 16;
	wo.VSync = true;
	wo.ShouldSwapAutomatically = false;
	wo.API = capi;
		
	window = Window.Create(wo);
	window.IsVisible = false;
	window.Load += OnLoad;
	window.Update += OnUpdate;
	window.Render += OnRender;
	window.Closing += OnClosing;
	window.Run();
		
}
```

# Steps to reproduce
- Platform: Windows Desktop
- Framework Version: .NET Core 6.0
- API: OpenGL
- API Version: OpenGL 4.6 Core Forward Compatible
Full Code here: https://pastebin.com/fHBDKdJH

# Comments
Issue persists despite removing all Options including WindowOptions.API keeping only IsVisible = false.

**Comment by Perksey** [comment]
This was fixed in #902, pending release by a maintainer.

**Comment by tilkinsc** [comment]
Oh okay. I searched but that title doesn't contain any useful key words. Sorry!

**Comment by Perksey** [comment]
Haha no worries :D
