### ISSUE TITLE
Incorrect delegate signature Silk.NET.OpenCL.NotifyCallback

### ISSUE THREAD

**Issue by UCIS** [dotnet/Silk.NET#975]
# Summary
The [Silk.NET.OpenCL.NotifyCallback](https://github.com/dotnet/Silk.NET/blob/main/src/OpenCL/Silk.NET.OpenCL/NotifyCallback.cs) delegate type is used [everywhere a callback function can be specified](https://raw.githubusercontent.com/dotnet/Silk.NET/main/src/OpenCL/Silk.NET.OpenCL/CLOverloads.gen.cs) in the OpenCL API, however the callback functions used in he OpenCL API methods each have different signatures.

The currently implemented NotifyCallback appears to have the signature used by the [clCreateContext API](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clCreateContext.html), which is quite different from the callback signature used by the [setEventCallback API](https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clSetEventCallback.html). This causes callback arguments to be misplaced and possibly worse.

One solution might be to use different delegate types for each of the callbacks. Another option might be to just allow a pointer to 
 be specified so the user can use `Marshal.GetFunctionPointerForDelegate` to a delegate type of their own.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 4.8
- API: OpenCL
- API Version: OpenCL 1.2
1. I queued a memory read (EnqueueReadBuffer) with an event
2. I registered a callback function (SetEventCallback)
3. I noticed the user data I passed to SetEventCallback was not in the userData parameter, but shifted one position to the cb parameter in the callback.

**__If you know how to fix this issue, please submit a pull request instead!__**
Unfortunately it is not yet clear to me how the OpenCL code is generated, otherwise I would have considered submitting a pull request instead.

**Comment by HurricanKai** [comment]
I have no idea about OpenCL, but I highly doubt this is a ST issue. Likely an issue with upstream (wherever that is) definitions.

**Comment by Beyley** [comment]
Fixed by #1251
