### ISSUE TITLE
Imgui for Silk.NET.Core?

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/Silk.NET#978]
Is there a extension for Silk.NET.core that works on dotnet 6?

**Comment by Beyley** [comment]
imgui extensions work fine on dotnet core

**Comment by Shadowblitz16** [comment]
I don't even know which ones to use there is OpenGL and OpenGLES but I don't see a vulkan one.

**Comment by Beyley** [comment]
> I don't even know which ones to use there is OpenGL and OpenGLES but I don't see a vulkan one.

we do not provide one, there is a heavy WIP one but its not for use so we dont pubish it

**Comment by Shadowblitz16** [comment]
ok thankyou
